-- CARREGA_PPNA (owner: SIID_TESTES)


-- ===== PROCEDURE =====

PROCEDURE
  CARREGA_PPNA
IS
  NRESULT NUMBER;
BEGIN
  DELETE GD_FRACCIONAMENTO_PPNA;
  DELETE GD_RISCOS_PPNA;
  DELETE GD_RECIBOS_PPNA;
  COMMIT;
  NRESULT:= PKG_PPNA.LOAD_RECIBOS;
  COMMIT;
  NRESULT:= PKG_PPNA.CALCULA_PPNA;
  COMMIT;
  NRESULT:= PKG_PPNA.UPDT_RECIBOS;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;

