-- CRIA_INFO_ENTIDADES_M91 (owner: SIID_TESTES)


-- ===== PROCEDURE =====

PROCEDURE
  CRIA_INFO_ENTIDADES_M91
IS
  NRESULT NUMBER;

  VALIDA_OBJ NUMBER;

  vTIME1 date;
  vTIME2 date;
  vTIME3 date;
  vTIME4 date;
  vTIME5 date;
  vTIME6 date;
  vTIME7 date;
  vTIME8 date;
  vTIME9 date;

BEGIN

	VALIDA_OBJ := 0;

	vTIME1 := sysdate;
    DBMS_OUTPUT.put_line('INICIO');

	begin

		SELECT COUNT(1)
		INTO VALIDA_OBJ
		FROM USER_TABLES
		WHERE TABLE_NAME = 'GD_ENTIDADES_M91';

		DBMS_OUTPUT.put_line('GD_ENTIDADES_M91 - ' || VALIDA_OBJ);

		if VALIDA_OBJ > 0 then
            DBMS_OUTPUT.put_line('drop table GD_ENTIDADES_M91');
			execute immediate 'drop table GD_ENTIDADES_M91';
            DBMS_OUTPUT.put_line('drop table GD_ENTIDADES_M91 - end');
		end if;

        DBMS_OUTPUT.put_line('create table as GD_ENTIDADES_M91');
		execute immediate 
			q'{create table GD_ENTIDADES_M91 as
			SELECT /*+ ordered USE_HASH(PESSOA ENTIDADE) USE_NL(PAIS desc_cae desccae)*/
				PESSOA.CDIDEPER
				,PESSOA.CDPERSON
				,PESSOA.DSNOMBRE
				,PESSOA.CDPAIS
				,PAIS.DESCRIPL desc_pais
				,ENTIDADE.CDCAE
				,desc_cae.DESCRIPL setor_atividade
			FROM MPERSONA PESSOA
				,CO_ENTIDAD ENTIDADE
				,TMANTENI PAIS
				,TMANTENI desc_cae
				,co_caes desccae
			WHERE 1 = 1
				AND desc_cae.cdtabla(+) = 'CO_GCAES'
				AND desc_cae.codigo(+) = desccae.CDGRUCAE2
				AND desccae.cdcae(+) = ENTIDADE.cdcae
				AND ENTIDADE.CDPERSON = PESSOA.CDPERSON
				AND PAIS.CODIGO = PESSOA.CDPAIS
				AND PAIS.CDTABLA = 'TPAISES'
				AND NVL(PESSOA.FECBAJA, TO_DATE('01-01-2100', 'DD-MM-YYYY')) >= SYSDATE}';

		DBMS_OUTPUT.put_line('create table as GD_ENTIDADES_M91 - end');

		execute immediate 'CREATE UNIQUE INDEX "GD_ENTIDADES_M91_INDX" ON "GD_ENTIDADES_M91" ("CDPERSON") COMPUTE STATISTICS';

		commit;

	exception
		when others then
			DBMS_OUTPUT.put_line(sqlerrm);
	end;

	DBMS_STATS.GATHER_TABLE_STATS(ownname => '"SIID_TESTES"', tabname => '"GD_ENTIDADES_M91"', estimate_percent => 100);
	DBMS_STATS.GATHER_INDEX_STATS('"SIID_TESTES"', '"GD_ENTIDADES_M91_INDX"', estimate_percent => 100);

	vTIME2 := sysdate;
	VALIDA_OBJ := 0;

	begin

		SELECT COUNT(1)
		INTO VALIDA_OBJ
		FROM USER_TABLES
		WHERE TABLE_NAME = 'GD_ENT_CAPITAL_CRED_M91';

		DBMS_OUTPUT.put_line('GD_ENT_CAPITAL_CRED_M91 - ' || VALIDA_OBJ);

		if VALIDA_OBJ > 0 then
			DBMS_OUTPUT.put_line('drop table GD_ENT_CAPITAL_CRED_M91');
			execute immediate 'drop table GD_ENT_CAPITAL_CRED_M91';
			DBMS_OUTPUT.put_line('drop table GD_ENT_CAPITAL_CRED_M91 - end');
		end if;

		DBMS_OUTPUT.put_line('create table as GD_ENT_CAPITAL_CRED_M91');
		execute immediate 
			q'{create table GD_ENT_CAPITAL_CRED_M91 as
			SELECT /*+ ordered */
				ENTIDADE_RISCO.CDPERSON
				,NVL(SUM(DECODE(GARANTIA.CDTIPGAR, 'A', (GARANTIA.IMPCONCO * PKG_FORMULAS_COSEC.FUN_TAXA_CAMBIO(PROPOSTA.CDMOEDA) * DECODE(PROPOSTA.INDCOASEG, 'N', 1, 1 - (PKG_FORMULAS_COSEC.FUN_PERCENTAGEM_TOTAL_COAS(PROPOSTA.CDUNIECO, PROPOSTA.CDRAMO, PROPOSTA.SWESTADO, PROPOSTA.NMPOLIZA, SYSDATE) / 100))), 0)), 0) CAPITAL_DINAMICO
				,NVL(SUM(CASE 
							WHEN GARANTIA.CDTIPGAR != 'A'
								AND GARANTIA.CDRAMO IN (SELECT CDRAMO FROM TRAMOS WHERE CDTIPRAM = 1)
								THEN (GARANTIA.IMPCONCO * PKG_FORMULAS_COSEC.FUN_TAXA_CAMBIO(PROPOSTA.CDMOEDA) * DECODE(PROPOSTA.INDCOASEG, 'N', 1, 1 - (PKG_FORMULAS_COSEC.FUN_PERCENTAGEM_TOTAL_COAS(PROPOSTA.CDUNIECO, PROPOSTA.CDRAMO, PROPOSTA.SWESTADO, PROPOSTA.NMPOLIZA, SYSDATE) / 100)))
							ELSE 0
							END), 0) CAPITAL_NOMINATIVO
				,NVL(SUM(CASE 
							WHEN GARANTIA.CDTIPGAR != 'A'
								AND GARANTIA.CDRAMO IN (SELECT CDRAMO FROM TRAMOS WHERE CDTIPRAM = 1)
								THEN DECODE(GARANTIA.IMPSOLCO, 0, 0, 1)
							ELSE 0
							END), 0) N_GARANTIAS_NOMINATIVAS
                ,NVL(SUM(DECODE(GARANTIA.CDTIPGAR, 'A',DECODE(GARANTIA.IMPSOLCO, 0, 0, 1),0)), 0) N_GARANTIAS_DINAMICAS
				,NVL(COUNT(DISTINCT PROPOSTA.NMPOLIZA), 0) N_APOLICES
			FROM CO_PROROL ENTIDADE_RISCO
				,CO_PROGAR GARANTIA
				,CO_PROPOL PROPOSTA
			WHERE 1 = 1
				AND PROPOSTA.CDUNIECO = ENTIDADE_RISCO.CDUNIECO
				AND PROPOSTA.CDRAMO = ENTIDADE_RISCO.CDRAMO
				AND PROPOSTA.NMPROPUE = ENTIDADE_RISCO.NMPROPUE
				AND PROPOSTA.FEMODIF = (
					SELECT MAX(FEMODIF)
					FROM CO_PROPOL X
					WHERE X.CDUNIECO = PROPOSTA.CDUNIECO
						AND X.CDRAMO = PROPOSTA.CDRAMO
						AND X.NMPROPUE = PROPOSTA.NMPROPUE
					)
				AND GARANTIA.CDUNIECO = ENTIDADE_RISCO.CDUNIECO
				AND GARANTIA.CDRAMO = ENTIDADE_RISCO.CDRAMO
				AND GARANTIA.NMPROPUE = ENTIDADE_RISCO.NMPROPUE
				AND GARANTIA.NMGARANT = ENTIDADE_RISCO.NMGARANT
				/* AND GARANTIA.CDTIPGAR = 'A' */
				AND GARANTIA.SWESTADO IN (
					'D'
					,'M'
					,'PR'
					)
				/* LINHAS INSERIDAS ISSUE 602 - ALTERAR GET_ATRIBUTO_APOLICE_DATA PARA PARAMETRO DATA A MAIOR DE SYSDATE OU DATA INICIO VIGOR APOLICE */
				AND (
					GARANTIA.CDRAMO != '100'
					OR
					--  PKG_FORMULAS_COSEC.GET_ATRIBUTO_APOLICE_DATA(GARANTIA.CDUNIECO,GARANTIA.CDRAMO,GARANTIA.SWESTADO,GARANTIA.NMPOLIZA,11) NOT IN (11,12) OR
					PKG_FORMULAS_COSEC.GET_ATRIBUTO_APOLICE_DATA(GARANTIA.CDUNIECO, GARANTIA.CDRAMO, 'M', GARANTIA.NMPOLIZA, 11, GREATEST(PKG_FORMULAS_COSEC.GET_DT_VIGENCIA_APOLICE(PROPOSTA.CDUNIECO, PROPOSTA.CDRAMO, PROPOSTA.NMPOLIZA, 0, 'I'), SYSDATE), '-1') NOT IN (
						11
						,12
						,16
						,17
						,19
						)
					)
				/* FIM LINHAS INSERIDAS ISSUE 602 */
				AND ENTIDADE_RISCO.STATUS = 'V'
				AND ENTIDADE_RISCO.NMORDINA = (
					SELECT MAX(NMORDINA)
					FROM CO_PROROL X
					WHERE X.CDUNIECO = ENTIDADE_RISCO.CDUNIECO
						AND X.CDRAMO = ENTIDADE_RISCO.CDRAMO
						AND X.NMPROPUE = ENTIDADE_RISCO.NMPROPUE
						AND X.CDPERSON = ENTIDADE_RISCO.CDPERSON
						AND X.NMGARANT = ENTIDADE_RISCO.NMGARANT
						AND X.CDROL = ENTIDADE_RISCO.CDROL
					)
				AND ENTIDADE_RISCO.CDROL = 'ER'
				AND ENTIDADE_RISCO.CDRAMO LIKE '1%'
				AND ENTIDADE_RISCO.CDUNIECO NOT IN (
					SELECT CHAVE
					FROM CFG_VALORES_DOMINIO
					WHERE DOMINIO_ID = 'EXCLUSAO_RISCO'
					)
			GROUP BY ENTIDADE_RISCO.CDPERSON}';

		DBMS_OUTPUT.put_line('create table as GD_ENT_CAPITAL_CRED_M91 - end');

		execute immediate 'CREATE UNIQUE INDEX "GD_ENT_CAPITAL_CRED_M91_INDX" ON "GD_ENT_CAPITAL_CRED_M91" ("CDPERSON") COMPUTE STATISTICS';

		commit;

	exception
		when others then
			DBMS_OUTPUT.put_line(sqlerrm);
	end;

	DBMS_STATS.GATHER_TABLE_STATS(ownname => '"SIID_TESTES"', tabname => '"GD_ENT_CAPITAL_CRED_M91"', estimate_percent => 100);
	DBMS_STATS.GATHER_INDEX_STATS('"SIID_TESTES"', '"GD_ENT_CAPITAL_CRED_M91_INDX"', estimate_percent => 100);

	vTIME3 := sysdate;
	VALIDA_OBJ := 0;

	begin

		SELECT COUNT(1)
		INTO VALIDA_OBJ
		FROM USER_TABLES
		WHERE TABLE_NAME = 'GD_ENT_CAPITAL_CAU_M91';

		DBMS_OUTPUT.put_line('GD_ENT_CAPITAL_CAU_M91 - ' || VALIDA_OBJ);

		if VALIDA_OBJ > 0 then
			DBMS_OUTPUT.put_line('drop table GD_ENT_CAPITAL_CAU_M91');
			execute immediate 'drop table GD_ENT_CAPITAL_CAU_M91';
			DBMS_OUTPUT.put_line('drop table GD_ENT_CAPITAL_CAU_M91 - end');
		end if;

		DBMS_OUTPUT.put_line('create table as GD_ENT_CAPITAL_CAU_M91');

		execute immediate 
			q'{create table GD_ENT_CAPITAL_CAU_M91 as
			SELECT /*+ ordered USE_NL(z ENTIDADE_RISCO) USE_HASH(CAPITAL APOLICE SIT_RISCO)*/ ---optimizer_features_enable('10.2.0.4')  
				ENTIDADE_RISCO.CDPERSON
				,NVL(SUM(CAPITAL.PTCAPITA * PKG_FORMULAS_COSEC.FUN_TAXA_CAMBIO(APOLICE.CDMONEDA) * DECODE(APOLICE.CDTIPCOA, 'N', 1, 1 - (PKG_FORMULAS_COSEC.FUN_PERCENTAGEM_TOTAL_COAS(APOLICE.CDUNIECO, APOLICE.CDRAMO, APOLICE.ESTADO, APOLICE.NMPOLIZA, DECODE(APOLICE.OTTEMPOT, 'R', APOLICE.FEPROREN, APOLICE.FEVENCIM)) / 100))), 0) CAPITAL
				,NVL(COUNT(SIT_RISCO.nmsituac), 0) N_GARANTIAS
				,NVL(COUNT(DISTINCT APOLICE.NMPOLIZA), 0) N_APOLICES
			FROM tramos z
				,MPOLIPER ENTIDADE_RISCO
				,MPOLICAP CAPITAL
				,MPOLIZAS APOLICE
                ,MPOLISIT SIT_RISCO		
			WHERE 1 = 1
				AND APOLICE.ESTADO = 'M'
				AND APOLICE.CDUNIECO = ENTIDADE_RISCO.CDUNIECO
				AND APOLICE.CDRAMO = ENTIDADE_RISCO.CDRAMO
				AND APOLICE.ESTADO = ENTIDADE_RISCO.ESTADO
				AND APOLICE.NMPOLIZA = ENTIDADE_RISCO.NMPOLIZA
				AND APOLICE.NMSUPLEM = (
					SELECT MAX(NMSUPLEM)
					FROM MPOLIZAS X
					WHERE X.CDUNIECO = APOLICE.CDUNIECO
						AND X.CDRAMO = APOLICE.CDRAMO
						AND X.ESTADO = APOLICE.ESTADO
						AND X.NMPOLIZA = APOLICE.NMPOLIZA
						AND X.STATUS = 'V'
					)
				AND PKG_FORMULAS_COSEC.IS_APOLICE_VALIDA(APOLICE.CDUNIECO, APOLICE.CDRAMO, APOLICE.ESTADO, APOLICE.NMPOLIZA) = 'S'
					AND SIT_RISCO.CDUNIECO = ENTIDADE_RISCO.CDUNIECO
					AND SIT_RISCO.CDRAMO = ENTIDADE_RISCO.CDRAMO
					AND SIT_RISCO.ESTADO = ENTIDADE_RISCO.ESTADO
					AND SIT_RISCO.NMPOLIZA = ENTIDADE_RISCO.NMPOLIZA
					AND SIT_RISCO.NMSITUAC = ENTIDADE_RISCO.NMSITUAC
					AND SIT_RISCO.NMSUPLEM = (
						SELECT MAX(NMSUPLEM)
						FROM MPOLISIT X
						WHERE X.CDUNIECO = SIT_RISCO.CDUNIECO
							AND X.CDRAMO = SIT_RISCO.CDRAMO
							AND X.ESTADO = SIT_RISCO.ESTADO
							AND X.NMPOLIZA = SIT_RISCO.NMPOLIZA
							AND X.NMSITUAC = SIT_RISCO.NMSITUAC
							AND X.NMSUPLEM <= TO_CHAR(SYSDATE, 'J') || '99999999999'
						)
				AND SIT_RISCO.STATUS = 'V' 
				AND CAPITAL.CDUNIECO = ENTIDADE_RISCO.CDUNIECO
				AND CAPITAL.CDRAMO = ENTIDADE_RISCO.CDRAMO
				AND CAPITAL.ESTADO = ENTIDADE_RISCO.ESTADO
				AND CAPITAL.NMPOLIZA = ENTIDADE_RISCO.NMPOLIZA
				AND CAPITAL.NMSITUAC = ENTIDADE_RISCO.NMSITUAC /* NÃO FAZ SENTIDO...TEM DE SER VALIDADO */
				AND CAPITAL.CDCAPITA = 1
				AND CAPITAL.NMSUPLEM = (
					SELECT MAX(NMSUPLEM)
					FROM MPOLICAP X
					WHERE X.CDUNIECO = CAPITAL.CDUNIECO
						AND X.CDRAMO = CAPITAL.CDRAMO
						AND X.ESTADO = CAPITAL.ESTADO
						AND X.NMPOLIZA = CAPITAL.NMPOLIZA
						AND X.NMSITUAC = CAPITAL.NMSITUAC
						AND X.CDCAPITA = CAPITAL.CDCAPITA
						AND X.NMSUPLEM <= TO_CHAR(SYSDATE, 'J') || '99999999999'
					)
				AND CAPITAL.STATUS = 'V'
				AND ENTIDADE_RISCO.STATUS = 'V'
				AND ENTIDADE_RISCO.NMSUPLEM = (
					SELECT MAX(NMSUPLEM)
					FROM MPOLIPER X
					WHERE X.CDUNIECO = ENTIDADE_RISCO.CDUNIECO
						AND X.CDRAMO = ENTIDADE_RISCO.CDRAMO
						AND X.ESTADO = ENTIDADE_RISCO.ESTADO
						AND X.NMPOLIZA = ENTIDADE_RISCO.NMPOLIZA
						AND X.CDPERSON = ENTIDADE_RISCO.CDPERSON
						AND X.NMSITUAC = ENTIDADE_RISCO.NMSITUAC
						AND X.CDROL = ENTIDADE_RISCO.CDROL
						AND X.NMSUPLEM <= TO_CHAR(SYSDATE, 'J') || '99999999999'
					)
				AND ENTIDADE_RISCO.CDROL = 'RC'
				AND ENTIDADE_RISCO.ESTADO = 'M'
				AND ENTIDADE_RISCO.CDRAMO = z.cdramo
				/*AND ENTIDADE_RISCO.nmsituac BETWEEN 1
			AND 20*/
				AND ENTIDADE_RISCO.CDUNIECO NOT IN (
					SELECT CHAVE
					FROM CFG_VALORES_DOMINIO
					WHERE DOMINIO_ID = 'EXCLUSAO_RISCO'
					)
				AND z.cdtipora = '2'
			GROUP BY ENTIDADE_RISCO.CDPERSON}';

		DBMS_OUTPUT.put_line('create table as GD_ENT_CAPITAL_CAU_M91 - END');

		execute immediate 'CREATE UNIQUE INDEX "GD_ENT_CAPITAL_CAU_M91_INDX" ON "GD_ENT_CAPITAL_CAU_M91" ("CDPERSON") COMPUTE STATISTICS';

		commit;

	exception
		when others then
			DBMS_OUTPUT.put_line(sqlerrm);
	end;

	DBMS_STATS.GATHER_TABLE_STATS(ownname => '"SIID_TESTES"', tabname => '"GD_ENT_CAPITAL_CAU_M91"', estimate_percent => 100);
	DBMS_STATS.GATHER_INDEX_STATS('"SIID_TESTES"', '"GD_ENT_CAPITAL_CAU_M91_INDX"', estimate_percent => 100);

	vTIME4 := sysdate;
	VALIDA_OBJ := 0;

	begin

		SELECT COUNT(1)
		INTO VALIDA_OBJ
		FROM USER_TABLES
		WHERE TABLE_NAME = 'GD_ENT_PLAF_CRE_M91';

		DBMS_OUTPUT.put_line('GD_ENT_PLAF_CRE_M91 - ' || VALIDA_OBJ);

		if VALIDA_OBJ > 0 then
			DBMS_OUTPUT.put_line('drop table GD_ENT_PLAF_CRE_M91');
			execute immediate 'drop table GD_ENT_PLAF_CRE_M91';
			DBMS_OUTPUT.put_line('drop table GD_ENT_PLAF_CRE_M91 - end');
		end if;

		DBMS_OUTPUT.put_line('create table as GD_ENT_PLAF_CRE_M91');
		execute immediate 
			q'{create table GD_ENT_PLAF_CRE_M91 as
			SELECT c.cdperson
				,NVL(c.ptimpind, 0) INDIVIDUAL
				,NVL(c.ptimpglo, 0) GLOBAL
				,datafin
				,cddeciso
			FROM co_plafocre c
			WHERE 1 = 1
				AND c.dataini = (
					SELECT MAX(cr.dataini)
					FROM co_plafocre cr
					WHERE cr.cdperson = c.cdperson
					)
				AND C.NMPLAFON = (
					SELECT MAX(X.NMPLAFON)
					FROM CO_PLAFOCRE X
					WHERE C.CDPERSON = X.CDPERSON
						AND C.DATAINI = X.DATAINI
					)
			}';

		DBMS_OUTPUT.put_line('create table as GD_ENT_PLAF_CRE_M91 - end');

		execute immediate 'CREATE UNIQUE INDEX "GD_ENT_PLAF_CRE_M91_INDX" ON "GD_ENT_PLAF_CRE_M91" ("CDPERSON") COMPUTE STATISTICS';

		commit;

	exception
		when others then
			DBMS_OUTPUT.put_line(sqlerrm);
	end;

	DBMS_STATS.GATHER_TABLE_STATS(ownname => '"SIID_TESTES"', tabname => '"GD_ENT_PLAF_CRE_M91"', estimate_percent => 100);
	DBMS_STATS.GATHER_INDEX_STATS('"SIID_TESTES"', '"GD_ENT_PLAF_CRE_M91_INDX"', estimate_percent => 100);

	vTIME5 := sysdate;
	VALIDA_OBJ:=0;

	begin

		SELECT COUNT(1)
		INTO VALIDA_OBJ
		FROM USER_TABLES
		WHERE TABLE_NAME = 'GD_ENT_PLAF_CAU_M91';

		DBMS_OUTPUT.put_line('GD_ENT_PLAF_CAU_M91 - ' || VALIDA_OBJ);

		if VALIDA_OBJ > 0 then
			DBMS_OUTPUT.put_line('drop table GD_ENT_PLAF_CAU_M91');
			execute immediate 'drop table GD_ENT_PLAF_CAU_M91';
			DBMS_OUTPUT.put_line('drop table GD_ENT_PLAF_CAU_M91 - end');
		end if;

		DBMS_OUTPUT.put_line('create table as GD_ENT_PLAF_CAU_M91');
		execute immediate 
			q'{create table GD_ENT_PLAF_CAU_M91 as
			SELECT d.cdperson
				,ptimport
				,datafin
				,cddeciso
			FROM co_plafonca d
			WHERE 1 = 1
				AND (
					d.dataini
					,d.NMPLAFON
					) = (
					SELECT MAX(x.dataini)
						,MAX(x.NMPLAFON)
					FROM co_plafonca x
					WHERE x.cdperson = d.cdperson
					)
				AND d.DATAINI != d.DATAFIN
			}';

		DBMS_OUTPUT.put_line('create table as GD_ENT_PLAF_CAU_M91 - end');

		execute immediate 'CREATE UNIQUE INDEX "GD_ENT_PLAF_CAU_M91_INDX" ON "GD_ENT_PLAF_CAU_M91" ("CDPERSON") COMPUTE STATISTICS';

		commit;

	exception
		when others then
			DBMS_OUTPUT.put_line(sqlerrm);
	end;

	DBMS_STATS.GATHER_TABLE_STATS(ownname => '"SIID_TESTES"', tabname => '"GD_ENT_PLAF_CAU_M91"', estimate_percent => 100);
	DBMS_STATS.GATHER_INDEX_STATS('"SIID_TESTES"', '"GD_ENT_PLAF_CAU_M91_INDX"', estimate_percent => 100);

	vTIME6 := sysdate;
	VALIDA_OBJ:=0;

	begin

		SELECT COUNT(1)
		INTO VALIDA_OBJ
		FROM USER_TABLES
		WHERE TABLE_NAME = 'GD_ENTIDADES_GRUPOS_M91';

		DBMS_OUTPUT.put_line('GD_ENTIDADES_GRUPOS_M91 - ' || VALIDA_OBJ);

		if VALIDA_OBJ > 0 then
			DBMS_OUTPUT.put_line('drop table GD_ENTIDADES_GRUPOS_M91');
			execute immediate 'drop table GD_ENTIDADES_GRUPOS_M91';
			DBMS_OUTPUT.put_line('drop table GD_ENTIDADES_GRUPOS_M91 - end');
		end if;

		DBMS_OUTPUT.put_line('create table as GD_ENTIDADES_GRUPOS_M91');

		execute immediate 
			q'{create table GD_ENTIDADES_GRUPOS_M91 as
			SELECT /*+ ordered */
				ATRIBUTO_PESSOA.CDPERSON
				,GRUPO_ENTIDADE.DSGRUENT
			FROM TVALOPER ATRIBUTO_PESSOA
				,CO_ENTIREL REL_ENTIDADE
				,CO_GRUPENT GRUPO_ENTIDADE
			WHERE ATRIBUTO_PESSOA.CDATRIBU = '21'
				AND SYSDATE >= GRUPO_ENTIDADE.DATAINI
				AND SYSDATE < NVL(GRUPO_ENTIDADE.DATAFIM, SYSDATE + 1)
				AND REL_ENTIDADE.CDPERFIL = ATRIBUTO_PESSOA.OTVALOR
				AND REL_ENTIDADE.CDGRUENT = GRUPO_ENTIDADE.CDGRUENT
				AND REL_ENTIDADE.SWDOMINA = 'S'}';

		DBMS_OUTPUT.put_line('create table as GD_ENTIDADES_GRUPOS_M91 - END');

		execute immediate 'CREATE UNIQUE INDEX "GD_ENTIDADES_GRUPOS_M91_INDX" ON "GD_ENTIDADES_GRUPOS_M91" ("CDPERSON") COMPUTE STATISTICS';

		commit;

	exception
		when others then
			DBMS_OUTPUT.put_line(sqlerrm);
	end;

	DBMS_STATS.GATHER_TABLE_STATS(ownname => '"SIID_TESTES"', tabname => '"GD_ENTIDADES_GRUPOS_M91"', estimate_percent => 100);
	DBMS_STATS.GATHER_INDEX_STATS('"SIID_TESTES"', '"GD_ENTIDADES_GRUPOS_M91_INDX"', estimate_percent => 100);

	vTIME7 := sysdate;
	VALIDA_OBJ := 0;

	begin

		SELECT COUNT(1)
		INTO VALIDA_OBJ
		FROM USER_TABLES
		WHERE TABLE_NAME = 'GD_ENTIDADES_RATING_M91';

		DBMS_OUTPUT.put_line('GD_ENTIDADES_RATING_M91 - ' || VALIDA_OBJ);

		if VALIDA_OBJ > 0 then
			DBMS_OUTPUT.put_line('drop table GD_ENTIDADES_RATING_M91');
			execute immediate 'drop table GD_ENTIDADES_RATING_M91';
			DBMS_OUTPUT.put_line('drop table GD_ENTIDADES_RATING_M91 - end');
		end if;

		DBMS_OUTPUT.put_line('create table as GD_ENTIDADES_RATING_M91');
		execute immediate 
			q'{create table GD_ENTIDADES_RATING_M91 as
			SELECT Y.CDPERSON
				,Y.CDVALOR
			FROM MPROCMOD Y
			WHERE 1 = 1
				AND Y.NMORDINA = (
					SELECT MAX(X.NMORDINA)
					FROM MPROCMOD X
					WHERE X.CDPERSON = Y.CDPERSON
						AND X.FEPROCES <= TRUNC(SYSDATE)
					)}';

		DBMS_OUTPUT.put_line('create table as GD_ENTIDADES_RATING_M91');

		execute immediate 'CREATE UNIQUE INDEX "GD_ENTIDADES_RATING_M91_INDX" ON "GD_ENTIDADES_RATING_M91" ("CDPERSON") COMPUTE STATISTICS';

		commit;

	exception
		when others then
			DBMS_OUTPUT.put_line(sqlerrm);
	end;

	DBMS_STATS.GATHER_TABLE_STATS(ownname => '"SIID_TESTES"', tabname => '"GD_ENTIDADES_RATING_M91"', estimate_percent => 100);
	DBMS_STATS.GATHER_INDEX_STATS('"SIID_TESTES"', '"GD_ENTIDADES_RATING_M91_INDX"', estimate_percent => 100);

	vTIME8 := sysdate;
	VALIDA_OBJ:=0;

	begin

		SELECT COUNT(1)
		INTO VALIDA_OBJ
		FROM USER_TABLES
		WHERE TABLE_NAME = 'GD_ENT_PEDIDO_INFO_M91';

		DBMS_OUTPUT.put_line('GD_ENT_PEDIDO_INFO_M91 - ' || VALIDA_OBJ);

		if VALIDA_OBJ > 0 then
			DBMS_OUTPUT.put_line('drop table GD_ENT_PEDIDO_INFO_M91');
			execute immediate 'drop table GD_ENT_PEDIDO_INFO_M91';
			DBMS_OUTPUT.put_line('drop table GD_ENT_PEDIDO_INFO_M91 - end');
		end if;

		DBMS_OUTPUT.put_line('create table as GD_ENT_PEDIDO_INFO_M91');
		execute immediate 
			q'{create table GD_ENT_PEDIDO_INFO_M91 as
			SELECT CDPERSON
				,CDFUERES
				,FEPEDIDO
				,FERESPOS
				,CDESTADO
				,nmpedido
			FROM CO_PEDIDOS PEDIDO
			WHERE 1 = 1
				AND (
					cdperson
					,nmpedido
					) = (
					SELECT max_nmpedido.cdperson
						,MAX(max_nmpedido.nmpedido)
					FROM CO_PEDIDOS max_nmpedido
					WHERE 1 = 1
						AND (
							cdperson
							,fepedido
							) = (
							SELECT MAX_PEDIDO.cdperson
								,MAX(MAX_PEDIDO.fepedido)
							FROM CO_PEDIDOS MAX_PEDIDO
							WHERE 1 = 1
								AND MAX_PEDIDO.CDPERSON = max_nmpedido.CDPERSON
							GROUP BY MAX_PEDIDO.cdperson
							)
						AND max_nmpedido.CDPERSON = PEDIDO.CDPERSON
					GROUP BY max_nmpedido.cdperson
					)
			}';

		DBMS_OUTPUT.put_line('create table as GD_ENT_PEDIDO_INFO_M91 - end');

		execute immediate 'CREATE UNIQUE INDEX "GD_ENT_PEDIDO_INFO_M91_INDX" ON "GD_ENT_PEDIDO_INFO_M91" ("CDPERSON") COMPUTE STATISTICS';

		commit;

	exception
		when others then
			DBMS_OUTPUT.put_line(sqlerrm);
	end;

	DBMS_STATS.GATHER_TABLE_STATS(ownname => '"SIID_TESTES"', tabname => '"GD_ENT_PEDIDO_INFO_M91"', estimate_percent => 100);
	DBMS_STATS.GATHER_INDEX_STATS('"SIID_TESTES"', '"GD_ENT_PEDIDO_INFO_M91_INDX"', estimate_percent => 100);

	vTIME9 := sysdate;

	DBMS_OUTPUT.put_line('Tempo de 1: ' || (vTIME2-vTIME1)*60*60*24);
	DBMS_OUTPUT.put_line('Tempo de 2: ' || (vTIME3-vTIME2)*60*60*24);
	DBMS_OUTPUT.put_line('Tempo de 3: ' || (vTIME4-vTIME3)*60*60*24);
	DBMS_OUTPUT.put_line('Tempo de 4: ' || (vTIME5-vTIME4)*60*60*24);
	DBMS_OUTPUT.put_line('Tempo de 5: ' || (vTIME6-vTIME5)*60*60*24);
	DBMS_OUTPUT.put_line('Tempo de 6: ' || (vTIME7-vTIME6)*60*60*24);
	DBMS_OUTPUT.put_line('Tempo de 7: ' || (vTIME8-vTIME7)*60*60*24);
	DBMS_OUTPUT.put_line('Tempo de 8: ' || (vTIME9-vTIME8)*60*60*24);
	DBMS_OUTPUT.put_line('Tempo Total: ' || (vTIME9-vTIME1)*60*60*24);

EXCEPTION
  WHEN OTHERS THEN
	DBMS_OUTPUT.put_line(sqlerrm);
    ROLLBACK;
END;
