-- FUN_CHECK_UNIQUE (owner: SIID_TESTES)


-- ===== FUNCTION =====

FUNCTION FUN_CHECK_UNIQUE ( P_MODELO   IN VARCHAR2
                            , P_PARAMETROS IN LISTA_PARAMETROS) RETURN NUMBER
IS

  CURSOR PARAMETROS_MODELO(P_MODELO IN VARCHAR2, P_NOME IN VARCHAR2, P_VALOR IN VARCHAR2) IS
    SELECT
      P.N_PARAMETRO
	, 'PARAMETRO'||TRIM(TO_CHAR(N_PARAMETRO,'00')) COLUNA
    , P.NOME
	, 'AND PARAMETRO'||TRIM(TO_CHAR(N_PARAMETRO,'00'))||' = '''||P_VALOR||''' ' WHERE_CLS
    FROM
      DOC_MODELOS_DOCUMENTO  D
    , SVR_PARAMETROS_REPORT  P
    WHERE 1=1
    AND P.NOME         = P_NOME
    AND D.REPORT_ID    = P.REPORT_ID
    AND P.CHECK_UNIQUE = 'U' /* PARAMETRO UNICO */
    AND D.ID           = P_MODELO;


  N_DOCUMENTO NUMBER := -1;
  N_PAR       NUMBER := 0;

  CFROM VARCHAR2(2000);
  CWHERE VARCHAR2(2000);
  CSQL   VARCHAR2(4000);

BEGIN

  DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'HH24:MI:SS'));

  CFROM:='SELECT COUNT(ID) FROM SVR_DOCUMENTOS ';
  CWHERE:='WHERE 1=1';
  
  FOR IDX IN 1..P_PARAMETROS.COUNT LOOP

    FOR RW IN PARAMETROS_MODELO(P_MODELO,P_PARAMETROS(IDX).NOME, P_PARAMETROS(IDX).VALOR) LOOP
      CWHERE := CWHERE||RW.WHERE_CLS;
	  N_PAR := N_PAR + 1;
    END LOOP;

	END LOOP;

  CSQL := CFROM||CWHERE;

  IF N_PAR > 0 THEN
    EXECUTE IMMEDIATE CSQL INTO N_DOCUMENTO;
  END IF;

  DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'HH24:MI:SS')||' -> '||N_DOCUMENTO);

  RETURN N_DOCUMENTO;

EXCEPTION
  WHEN OTHERS THEN
    RETURN -2;
END;

