-- GERA_PARAMETROS_POR_ERRO (owner: SIID_TESTES)


-- ===== PROCEDURE =====

PROCEDURE GERA_PARAMETROS_POR_ERRO(P_ID_INI IN NUMBER, P_ID_FIM IN NUMBER DEFAULT NULL)
AS
  CURSOR DOCS_PERDIDOS IS
    SELECT 
      *
    FROM 
      SVR_DOCUMENTOS
    WHERE 1=1
      AND ID BETWEEN P_ID_INI AND NVL(P_ID_FIM, P_ID_INI)
    ORDER BY ID;
    
  CURSOR PARAMS_DOC(P_MODELO IN VARCHAR2,P_NOME IN VARCHAR2) IS
    SELECT
      P.REPORT_ID
    , P.NOME
    FROM
      SVR_PARAMETROS_REPORT P
    , DOC_MODELOS_DOCUMENTO M
    WHERE 1=1
      AND M.REPORT_ID = P.REPORT_ID
      AND M.ID          = P_MODELO
      AND P.NOME        = P_NOME;
      
    CURSOR REGISTOS_PERDIDOS(P_DOCUMENTO IN NUMBER) IS
      SELECT
        SUBSTR(DESCRICAO, 1, INSTR(DESCRICAO,'=')-2) PARAMETRO
      , SUBSTR(DESCRICAO, INSTR(DESCRICAO,'=')+2)    VALOR
      , DESCRICAO
      FROM 
        ERR_ERROS_SIID
      WHERE 1=1
        AND DOCUMENTO_ID=P_DOCUMENTO
        AND INSTR(DESCRICAO,'=') != 0;
        
    BEGIN
      FOR RW IN DOCS_PERDIDOS LOOP
        FOR PS IN PARAMS_DOC(RW.MODELO_ID, 'P_ID') LOOP
          BEGIN
          
          INSERT INTO SVR_PARAMETROS_REPORT(REPORT_ID,N_PARAMETRO,NOME,TIPO_PARAMETRO_RF,OBRIGATORIO,CHECK_UNIQUE,VALIDO,DESCRICAO,CRIADO_POR,DATA_CRIACAO,ACTUALIZADO_POR,DATA_ACTUALIZACAO)
          VALUES(PS.REPORT_ID, (select max(PARAM.n_parametro) + 1 from SVR_PARAMETROS_REPORT PARAM where 1=1 and PARAM.report_id=PS.REPORT_ID),'P_ID',1,'N','N','S','P_ID',user,sysdate, null,null);
   
          EXCEPTION
          WHEN OTHERS THEN
            NULL;
          END;
        END LOOP;
        FOR PS IN PARAMS_DOC(RW.MODELO_ID, 'P_MODELO_ID') LOOP
          BEGIN
          
          INSERT INTO SVR_PARAMETROS_REPORT(REPORT_ID,N_PARAMETRO,NOME,TIPO_PARAMETRO_RF,OBRIGATORIO,CHECK_UNIQUE,VALIDO,DESCRICAO,CRIADO_POR,DATA_CRIACAO,ACTUALIZADO_POR,DATA_ACTUALIZACAO)
          VALUES(PS.REPORT_ID, (select max(PARAM.n_parametro) + 1 from SVR_PARAMETROS_REPORT PARAM where 1=1 and PARAM.report_id=PS.REPORT_ID),'P_MODELO_ID',1,'N','N','S','P_MODELO_ID',user,sysdate, null,null);
        
          EXCEPTION
          WHEN OTHERS THEN
            NULL;
          END;
        END LOOP;
        FOR X IN REGISTOS_PERDIDOS (RW.ID) LOOP
          FOR PS IN PARAMS_DOC(RW.MODELO_ID, X.PARAMETRO) LOOP
          BEGIN
            
          INSERT INTO SVR_PARAMETROS_REPORT(REPORT_ID,N_PARAMETRO,NOME,TIPO_PARAMETRO_RF,OBRIGATORIO,CHECK_UNIQUE,VALIDO,DESCRICAO,CRIADO_POR,DATA_CRIACAO,ACTUALIZADO_POR,DATA_ACTUALIZACAO)
          VALUES(PS.REPORT_ID, (select max(PARAM.n_parametro) + 1 from SVR_PARAMETROS_REPORT PARAM where 1=1 and PARAM.report_id=PS.REPORT_ID),X.PARAMETRO,1,'N','N','S',X.PARAMETRO,user,sysdate, null,null);
    
          EXCEPTION
          WHEN OTHERS THEN
            NULL;
          END;
        END LOOP;
      END LOOP;
    END LOOP;
END GERA_PARAMETROS_POR_ERRO;
