-- GERA_PARAMETROS_DOCUMENTOS (owner: SIID_TESTES)


-- ===== PROCEDURE =====

PROCEDURE GERA_PARAMETROS_DOCUMENTOS( P_DATA_INI IN DATE, P_DATA_FIM IN DATE, P_MODELO_ID IN VARCHAR2 DEFAULT '%', P_DOC_ID IN VARCHAR2 DEFAULT NULL) IS
  CURSOR DOCS_SEMPAR IS
    SELECT 
      * 
    FROM 
      SVR_DOCUMENTOS DOCS 
    WHERE 1=1
      AND  MODELO_ID LIKE P_MODELO_ID||'%'
      AND ( SELECT COUNT(*) 
            FROM SVR_PARAMETROS_REPORT X
            WHERE 1=1
            AND X.REPORT_ID=DOCS.REPORT_ID) < ( SELECT COUNT(*) 
                                            FROM SVR_PARAMETROS_REPORT Y
                                            WHERE 1=1
                                              AND Y.OBRIGATORIO='S' 
                                              AND Y.REPORT_ID=DOCS.REPORT_ID)
      AND DATA_PEDIDO BETWEEN P_DATA_INI AND P_DATA_FIM
      AND ID = NVL(P_DOC_ID, ID);
      
  CURSOR PARAMS_REPORT(P_REPORT_ID IN VARCHAR2,P_NOME_PARAM IN VARCHAR2) IS
    SELECT
      P.REPORT_ID
    , P.NOME
    FROM
      SVR_PARAMETROS_REPORT P
    WHERE
        P.REPORT_ID = P_REPORT_ID
    AND P.NOME        = P_NOME_PARAM;
    
  CURSOR PARAMS_DOC (P_REPORT_ID IN VARCHAR2, P_DOC_ID IN NUMBER) IS
    SELECT 
      PR.REPORT_ID
    , PR.NOME
    , PR.TIPO_PARAMETRO_RF
    , PR.OBRIGATORIO
    , PR.CHECK_UNIQUE
    , PR.VALIDO
    , ERR.MODELO_ID
    , ERR.DESCRICAO
    , SUBSTR(ERR.DESCRICAO,INSTR(ERR.DESCRICAO,PR.NOME)+LENGTH(PR.NOME)+3) VALOR_PARAMETRO
    FROM 
      SVR_PARAMETROS_REPORT PR
    , ERR_ERROS_SIID ERR 
    WHERE 
        PR.REPORT_ID   = P_REPORT_ID
    AND ERR.DOCUMENTO_ID = P_DOC_ID
    AND SUBSTR(ERR.DESCRICAO,INSTR(ERR.DESCRICAO,PR.NOME),LENGTH(PR.NOME))=PR.NOME
    AND NOT EXISTS (SELECT 1 
                    FROM SVR_PARAMETROS_REPORT X
                    WHERE 1=1
                    AND X.REPORT_ID =P_REPORT_ID 
                    AND X.TIPO_PARAMETRO_RF= PR.TIPO_PARAMETRO_RF)
    ORDER BY PR.REPORT_ID;
    
  CURSOR GERA_IDOC (P_REPORT_ID IN VARCHAR2, P_DOC_ID IN NUMBER) IS
    SELECT 
      PR.REPORT_ID
    , PR.NOME
    , PR.TIPO_PARAMETRO_RF
    , PR.OBRIGATORIO
    , PR.CHECK_UNIQUE
    , PR.VALIDO
    , ERR.MODELO_ID
    , ERR.DESCRICAO
    , SUBSTR(ERR.DESCRICAO,INSTR(ERR.DESCRICAO,PR.NOME)+LENGTH(PR.NOME)+3) VALOR_PARAMETRO
    FROM 
      SVR_PARAMETROS_REPORT PR
    , ERR_ERROS_SIID ERR 
    WHERE 
        PR.REPORT_ID   = P_REPORT_ID
    AND ERR.DOCUMENTO_ID = P_DOC_ID
    AND SUBSTR(ERR.DESCRICAO,INSTR(ERR.DESCRICAO,PR.NOME),LENGTH(PR.NOME))=PR.NOME
    ORDER BY PR.REPORT_ID;
  AUX_IDOC VARCHAR2(500);
BEGIN
  DBMS_OUTPUT.PUT_LINE('VAMOS COMECAR');
  FOR RW IN DOCS_SEMPAR LOOP
  BEGIN
    AUX_IDOC:=RW.MODELO_ID;
    DBMS_OUTPUT.PUT_LINE('MODELO: '||RW.MODELO_ID||CHR(10)||'TEMPLATE: '||RW.REPORT_ID);
    FOR PS IN PARAMS_REPORT(RW.REPORT_ID, 'P_ID') LOOP
       DBMS_OUTPUT.PUT_LINE(PS.REPORT_ID||'-'||RW.ID||'-'||RW.ID||'@');
       
       INSERT INTO SVR_PARAMETROS_REPORT(REPORT_ID,N_PARAMETRO,NOME,TIPO_PARAMETRO_RF,OBRIGATORIO,CHECK_UNIQUE,VALIDO,DESCRICAO,CRIADO_POR,DATA_CRIACAO,ACTUALIZADO_POR,DATA_ACTUALIZACAO)
       VALUES(PS.REPORT_ID, (select max(PARAM.n_parametro) + 1 from SVR_PARAMETROS_REPORT PARAM where 1=1 and PARAM.report_id=PS.REPORT_ID),'P_ID',1,'N','N','S','P_ID',user,sysdate, null,null);
       
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('AGORA O PARAMETRO DO MODELO!');
    FOR PS IN PARAMS_REPORT(RW.REPORT_ID, 'P_MODELO_ID') LOOP
      DBMS_OUTPUT.PUT_LINE(PS.REPORT_ID||'-'||RW.ID||'-'||RW.MODELO_ID||'@');
      INSERT INTO SVR_PARAMETROS_REPORT(REPORT_ID,N_PARAMETRO,NOME,TIPO_PARAMETRO_RF,OBRIGATORIO,CHECK_UNIQUE,VALIDO,DESCRICAO,CRIADO_POR,DATA_CRIACAO,ACTUALIZADO_POR,DATA_ACTUALIZACAO)
      VALUES(PS.REPORT_ID, (select max(PARAM.n_parametro) + 1 from SVR_PARAMETROS_REPORT PARAM where 1=1 and PARAM.report_id=PS.REPORT_ID),'P_MODELO_ID',1,'N','N','S','P_MODELO_ID',user,sysdate, null,null);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('...E OS RESTANTES!');
    FOR PARS_RW IN PARAMS_DOC(RW.REPORT_ID, RW.ID) LOOP
      DBMS_OUTPUT.PUT_LINE(PARS_RW.REPORT_ID||'-'||RW.ID||'-'||PARS_RW.VALOR_PARAMETRO||'@');
      
      --INSERT INTO SVR_PARAMETROS_REPORT(REPORT_ID,N_PARAMETRO,NOME,TIPO_PARAMETRO_RF,OBRIGATORIO,CHECK_UNIQUE,VALIDO,DESCRICAO,CRIADO_POR,DATA_CRIACAO,ACTUALIZADO_POR,DATA_ACTUALIZACAO)
      --VALUES(PS.REPORT_ID, (select max(PARAM.n_parametro) + 1 from SVR_PARAMETROS_REPORT PARAM where 1=1 and PARAM.report_id=PS.REPORT_ID),'P_ID',1,'N','N','S','P_ID',user,sysdate, null,null);
      
    END LOOP;
    FOR PARS_RW IN GERA_IDOC(RW.REPORT_ID, RW.ID) LOOP
      IF PARS_RW.CHECK_UNIQUE='U' THEN
        AUX_IDOC:=AUX_IDOC||'|'||PARS_RW.VALOR_PARAMETRO;
      END IF;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('ACTUALIZA IDOC');
    UPDATE SVR_DOCUMENTOS SET IDOC=AUX_IDOC WHERE ID=RW.ID;
    AUX_IDOC:=NULL;
--    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN 
      DBMS_OUTPUT.PUT_LINE('FALHOU :'||RW.ID);
  END;
  END LOOP;
END GERA_PARAMETROS_DOCUMENTOS;
