-- GET_GAR_ID (owner: SIID_TESTES)


-- ===== FUNCTION =====

FUNCTION Get_Gar_Id ( P_MODELO   IN VARCHAR2
                      , P_PARAMETROS IN LISTA_PARAMETROS) RETURN NUMBER
IS

  CURSOR PARAMETROS_MODELO(P_MODELO IN VARCHAR2, P_NOME IN VARCHAR2) IS
    SELECT
      P.N_PARAMETRO
    , P.NOME
    FROM
      DOC_MODELOS_DOCUMENTO  D
    , SVR_PARAMETROS_REPORT  P
    WHERE
        P.NOME = P_NOME
    AND D.REPORT_ID = P.REPORT_ID
    AND D.ID = P_MODELO;

  N_DOCUMENTO NUMBER := -1;

  CFROM VARCHAR2(2000);
  CWHERE VARCHAR2(2000);
  CSQL   VARCHAR2(4000);

  N_P_ID NUMBER;

BEGIN

  DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'HH24:MI:SS'));

  FOR I IN 1..P_PARAMETROS.COUNT LOOP

    FOR RW IN PARAMETROS_MODELO(P_MODELO,P_PARAMETROS(I).NOME) LOOP
      N_P_ID := RW.N_PARAMETRO;
    END LOOP;

    IF I= 1 THEN
      CFROM := 'SELECT A1.DOCUMENTO_ID FROM SVR_PARAMETROS_DOCUMENTO A'||I;
      CWHERE:=' WHERE A'||I||'.PARAMREP_ID = '||N_P_ID||' AND A'||I||'.VALOR = '''||P_PARAMETROS(I).VALOR||'''';
    ELSE
      CFROM := CFROM||', SVR_PARAMETROS_DOCUMENTO A'||I;
      CWHERE:= CWHERE||' AND A1.DOCUMENTO_ID = A'||I||'.DOCUMENTO_ID AND A'||I||'.PARAMREP_ID = '||N_P_ID||' AND A'||I||'.VALOR = '''||P_PARAMETROS(I).VALOR||'''';
    END IF;

  END LOOP;

  CSQL := CFROM||CWHERE;

  EXECUTE IMMEDIATE CSQL INTO N_DOCUMENTO;

  DBMS_OUTPUT.PUT_LINE(SUBSTR(CSQL,1,200));
  DBMS_OUTPUT.PUT_LINE(SUBSTR(CSQL,201,200));
  DBMS_OUTPUT.PUT_LINE(SUBSTR(CSQL,401,200));

  DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'HH24:MI:SS')||' -> '||N_DOCUMENTO);

  RETURN N_DOCUMENTO;

END;

