-- GET_DATAOCURR_SIN (owner: SIID_TESTES)


-- ===== FUNCTION =====

FUNCTION GET_DATAOCURR_SIN( PI_CDUNIECO IN NUMBER
                          , PI_CDRAMO   IN NUMBER
                          , PI_AAAPERTU IN NUMBER
                          , PI_STATUS   IN VARCHAR2
                          , PI_NMSINIES IN NUMBER) RETURN DATE DETERMINISTIC
IS
  AUX_RESULT  DATE;
  NMIGRADO    NUMBER;
BEGIN
  SELECT
    COUNT(*)
  INTO
    nMIGRADO
  FROM
    GD_SINISTROS_MIGRADOS
  WHERE
     AAAPERTU         >= PI_AAAPERTU
  AND CDRAMO           = PI_CDRAMO
  AND LIMITE_MIGRACAO  > PI_NMSINIES;
  SELECT
    DECODE( NMIGRADO, 0, COMUNICACAO.FECOMUNI
                    , COMUNICACAO.FEOCAME) AUX_RESULT
  INTO
     AUX_RESULT
  FROM
    CO_COAME  COMUNICACAO
  , MSINIEST SINISTRO
  WHERE
      COMUNICACAO.CDUNIECO = SINISTRO.CDUNIECO
  AND COMUNICACAO.CDTIPORA = SINISTRO.CDTIPORA
  AND COMUNICACAO.NMCOMAME = SINISTRO.NMCOMAME
  AND COMUNICACAO.NMPROAME = SINISTRO.NMPROAME
  AND SINISTRO.NMSINIES    = PI_NMSINIES
  AND SINISTRO.STATUS      = PI_STATUS
  AND SINISTRO.AAAPERTU    = PI_AAAPERTU
  AND SINISTRO.CDRAMO      = PI_CDRAMO
  AND SINISTRO.CDUNIECO    = PI_CDUNIECO;
  RETURN AUX_RESULT;
EXCEPTION
  WHEN OTHERS THEN
    RETURN TO_DATE('01-01-1800','DD-MM-YYYY');
END GET_DATAOCURR_SIN;

