-- GET_DT_POSICAO_SUPLEMENTOS (owner: SIID_TESTES)


-- ===== FUNCTION =====

FUNCTION GET_DT_POSICAO_SUPLEMENTOS ( PI_CDUNIECO IN NUMBER
                              , PI_CDRAMO   IN VARCHAR2
                              , PI_ESTADO   IN VARCHAR2
                              , PI_NMPOLIZA IN NUMBER)
							  RETURN DATE IS

V_DATA MPOLIZAS.FEPROREN%TYPE :=NULL;

BEGIN

	SELECT Least(sysdate, DECODE(APOLICE.OTTEMPOT, 'T', APOLICE.FEVENCIM, APOLICE.FEPROREN - 1)) DT_MIN
	INTO V_DATA
	FROM MPOLIZAS APOLICE
	WHERE 1 = 1
		AND APOLICE.NMSUPLEM = (
			SELECT MAX(X.NMSUPLEM)
			FROM MPOLIZAS X
			WHERE 1 = 1
				AND X.NMSUPLEM <= TO_CHAR(sysdate, 'J') || '99999999999'
				AND X.NMPOLIZA = APOLICE.NMPOLIZA
				AND X.CDRAMO = APOLICE.CDRAMO
				AND X.ESTADO = APOLICE.ESTADO
				AND X.CDUNIECO = APOLICE.CDUNIECO
			)
		AND APOLICE.NMPOLIZA = PI_NMPOLIZA
		AND APOLICE.ESTADO = PI_ESTADO
		AND APOLICE.CDRAMO = PI_CDRAMO
		AND APOLICE.CDUNIECO = PI_CDUNIECO;

	RETURN V_DATA;
	
EXCEPTION
  WHEN OTHERS THEN
     RETURN null;
END;
