-- GET_COUNT_TAB (owner: SIID_TESTES)


-- ===== FUNCTION =====

FUNCTION GET_COUNT_TAB(p_TABELA IN VARCHAR2, P_OWNER IN VARCHAR2 DEFAULT USER) RETURN NUMBER
IS
  nCount NUMBER:=0;
BEGIN

  EXECUTE IMMEDIATE
    'SELECT COUNT(*) FROM '||P_TABELA INTO NCOUNT;

  RETURN NCOUNT;

END GET_COUNT_TAB;

