-- GET_PAR_VALOR (owner: SIID_TESTES)


-- ===== FUNCTION =====

FUNCTION GET_PAR_VALOR(P_LISTA IN LISTA_PARAMETROS, P_PARAMETRO IN VARCHAR2) RETURN VARCHAR2
AS
BEGIN
  FOR IDX IN P_LISTA.FIRST..P_LISTA.LAST LOOP
    IF P_LISTA(IDX).NOME = P_PARAMETRO THEN
      RETURN P_LISTA(IDX).VALOR;
    END IF;
  END LOOP;

  RETURN NULL;
END;

