-- GET_REFDOC (owner: SIID_TESTES)


-- ===== FUNCTION =====

FUNCTION GET_REFDOC( P_DEP IN VARCHAR2, P_DOC_ID IN NUMBER DEFAULT -1) RETURN VARCHAR2
IS
  cResult VARCHAR2(20);
  cSQL    VARCHAR2(2000);
  cDEP	  VARCHAR2(20):= P_DEP;
  dDEP	  VARCHAR2(20):= P_DEP;
BEGIN

	IF NVL(P_DOC_ID,-1) >= 0 THEN
		SELECT
			N_REFERENCIA
		INTO
			cResult
		FROM
			SVR_DOCUMENTOS
		WHERE
			ID = P_DOC_ID;
		IF cResult IS NOT NULL THEN
			RETURN cResult;
		END IF;
	END IF;

	IF (P_DEP = 'US' or P_DEP = 'UC') THEN
		cDEP := 'DSC';
		dDEP := 'DSC';
	END IF;

	IF (P_DEP = 'DFR') THEN
		dDEP := 'DFA';
	END IF;


	cSQL:= 'SELECT '''
		||UPPER(dDEP)||'/''||trim(TO_CHAR("'||cDEP||'_DOCSEQ".NEXTVAL,''000000'')) FROM DUAL';

	DBMS_OUTPUT.PUT_LINE(cSQL);
	EXECUTE IMMEDIATE cSQL INTO cResult;
	DBMS_OUTPUT.PUT_LINE('RESULTADO:' ||cRESULT);
	DBMS_OUTPUT.PUT_LINE('AQUI');
	IF NVL(P_DOC_ID,-1) >= 0 THEN
		DBMS_OUTPUT.PUT_LINE('ENTREI ');
		DBMS_OUTPUT.PUT_LINE('param:'|| P_DOC_ID);
		DBMS_OUTPUT.PUT_LINE('RESULTADO:' ||cRESULT);
		UPDATE
			SVR_DOCUMENTOS
		SET
			N_REFERENCIA = cResult
		WHERE
			ID = P_DOC_ID;

		DBMS_OUTPUT.PUT_LINE('FAZER COMMIT');
		COMMIT;
	END IF;
    DBMS_OUTPUT.PUT_LINE('FINAL');
	return cRESULT;
EXCEPTION
	WHEN OTHERS THEN
		RETURN UPPER(dDEP)||'/XXXXXX';
END GET_REFDOC;
