-- GET_REF_RECIBO (owner: SIID_TESTES)


-- ===== FUNCTION =====

FUNCTION GET_REF_RECIBO( P_REF IN VARCHAR2, P_DOC_ID IN NUMBER DEFAULT -1) RETURN VARCHAR2
IS
  cResult VARCHAR2(20);
BEGIN
  IF NVL(P_DOC_ID,-1) >= 0 THEN
    SELECT
	  N_REFERENCIA
	INTO
	  cResult
	FROM
	  SVR_DOCUMENTOS
	WHERE
	  ID = P_DOC_ID;
	IF cResult IS NULL THEN
	  cResult := P_REF;
      UPDATE
	    SVR_DOCUMENTOS
      SET
	    N_REFERENCIA = cResult
      WHERE
	    ID = P_DOC_ID;
      COMMIT;
	END IF;
  END IF;
  return cRESULT;
EXCEPTION
  WHEN OTHERS THEN
    RETURN 'XXXXX/XXXXXX';
END GET_REF_RECIBO;

