-- GET_ANO (owner: SIID_TESTES)


-- ===== FUNCTION =====

FUNCTION GET_ANO( P_DATA IN VARCHAR2) RETURN NUMBER DETERMINISTIC
AS
BEGIN
  RETURN TO_NUMBER(TO_CHAR(ADD_MONTHS(TO_DATE(P_DATA,'MON-RR','NLS_DATE_LANGUAGE=PORTUGUESE'),-1),'RRRR'));
END;

