-- INS_PARAMETROS_DOC (owner: SIID_TESTES)


-- ===== FUNCTION =====

FUNCTION INS_PARAMETROS_DOC(P_MODELO_ID IN VARCHAR2, P_ID IN NUMBER DEFAULT 0, P_DATA_INICIO IN DATE DEFAULT NULL, P_DATA_FIM IN DATE DEFAULT SYSDATE) RETURN NUMBER
IS
 CURSOR DOCS_SEMPAR IS
    SELECT
      DOCS.ID              
    , DOCS.MODELO_ID       
    , DOCS.REPORT_ID     
    , DOCS.AMBIENTE_ID     
    , DOCS.IMPRESSORA_ID   
    , DOCS.LOTE_ORDEM      
    , DOCS.N_IMPRESSOES    
    , DOCS.N_ANEXOS        
    , DOCS.N_COPIAS        
    , DOCS.N_CAPAS         
    , DOCS.N_VIAS          
    , DOCS.LOTE_ID         
    , DOCS.N_REFERENCIA    
    , DOCS.ULTIMA_VIA_POR  
    , DOCS.IMPRESSO_POR    
    , DOCS.DATA_IMPRESSAO  
    , DOCS.DATA_PEDIDO     
    , DOCS.TIPO_OUTPUT     
    , DOCS.NOME_OUTPUT     
    , DOCS.IDOC            
    , DOCS.VERSAO          
    , DOCS.DATA_ARQUIVO    
    , DOCS.ARQUIVADO       
    , DOCS.CRIADO_POR      
    , DOCS.EXECUTADO_POR   
    , DOCS.DATA_EXECUCAO   
    , DOCS.DESTINATARIO    
    , DOCS.MORADA          
    , DOCS.CODIGO_POSTAL   
    , DOCS.PAIS            
    , DOCS.ATRIBUTO1       
    , DOCS.ATRIBUTO2       
    , DOCS.ATRIBUTO3       
    , DOCS.ATRIBUTO4       
    , MODEL.FORMA_CONTROLO_RF
    FROM
      SVR_DOCUMENTOS DOCS
    , DOC_MODELOS_DOCUMENTO MODEL
    WHERE
        DOCS.MODELO_ID = 'D15.L3'
    AND MODEL.ID = DOCS.MODELO_ID
    AND DOCS.DATA_PEDIDO BETWEEN NVL(P_DATA_INICIO, TO_DATE('01-01-1900')) AND NVL(P_DATA_FIM,SYSDATE)
    AND DOCS.ID > NVL(P_ID,0);
  CURSOR PARAMS_REPORT(P_REPORT_ID IN VARCHAR2,P_NOME_PARAM IN VARCHAR2) IS
    SELECT
      P.REPORT_ID
    , P.NOME
    FROM
      SVR_PARAMETROS_REPORT P
    WHERE
        P.REPORT_ID = P_REPORT_ID
    AND P.NOME        = P_NOME_PARAM;
  CURSOR PARAMS_DOC (P_REPORT_ID IN VARCHAR2, P_DOC_ID IN NUMBER) IS
    SELECT
      PR.REPORT_ID
    , PR.NOME
    , PR.TIPO_PARAMETRO_RF
    , PR.REPORT_ID REP
    , PR.OBRIGATORIO
    , PR.CHECK_UNIQUE
    , PR.VALIDO
    , ERR.MODELO_ID
    , ERR.DESCRICAO
    , SUBSTR(ERR.DESCRICAO,INSTR(ERR.DESCRICAO,PR.NOME)+LENGTH(PR.NOME)+3) VALOR_PARAMETRO
    FROM
      SVR_PARAMETROS_REPORT PR
    , ERR_ERROS_SIID ERR
    WHERE
        PR.REPORT_ID   = P_REPORT_ID
    AND ERR.DOCUMENTO_ID = P_DOC_ID
    AND SUBSTR(ERR.DESCRICAO,INSTR(ERR.DESCRICAO,PR.NOME),LENGTH(PR.NOME))=PR.NOME
    ORDER BY PR.REPORT_ID;
  NCOUNT   NUMBER:=0;
  AUX_IDOC VARCHAR2(500);
BEGIN
  DBMS_OUTPUT.PUT_LINE('VAMOS COMECAR');
  FOR RW IN DOCS_SEMPAR LOOP
    AUX_IDOC:=RW.MODELO_ID;
    DBMS_OUTPUT.PUT_LINE('MODELO: '||RW.MODELO_ID||CHR(10)||'REPORT: '||RW.REPORT_ID);
    FOR PS IN PARAMS_REPORT(RW.REPORT_ID, 'P_ID') LOOP
    BEGIN
       DBMS_OUTPUT.PUT_LINE(PS.REPORT_ID||'-'||RW.ID||'-'||RW.ID||'@');
       --INSERT INTO SVR_PARAMETROS_REPORT VALUES(PS.REPORT_ID,RW.ID, RW.ID);
    EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('N?O ACTUALIZOU P_ID');
    END;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('AGORA O PARAMETRO DO MODELO!');
    FOR PS IN PARAMS_REPORT(RW.REPORT_ID, 'P_MODELO_ID') LOOP
    BEGIN
       DBMS_OUTPUT.PUT_LINE(PS.REPORT_ID||'-'||RW.ID||'-'||RW.MODELO_ID||'@');
       --INSERT INTO SVR_PARAMETROS_REPORT VALUES(PS.ID,RW.ID, RW.MODELO_ID);
    EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('N?O ACTUALIZOU P_MODELO_ID');
    END;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('...E OS RESTANTES!');
    FOR PARS_RW IN PARAMS_DOC(RW.REPORT_ID, RW.ID) LOOP
      IF PARS_RW.CHECK_UNIQUE='U' THEN
        AUX_IDOC:=AUX_IDOC||'|'||PARS_RW.VALOR_PARAMETRO;
      END IF;
      BEGIN
        DBMS_OUTPUT.PUT_LINE(PARS_RW.NOME||'('||PARS_RW.REPORT_ID||')'||'-'||RW.ID||'-'||PARS_RW.VALOR_PARAMETRO||'@');
        --INSERT INTO SVR_PARAMETROS_REPORT VALUES(PARS_RW.REPORT_ID,RW.ID,PARS_RW.VALOR_PARAMETRO);
      EXCEPTION
        WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('N?O INTRODUZIU '||PARS_RW.NOME);
      END;
    END LOOP;
    IF RW.FORMA_CONTROLO_RF IN ('U','V') THEN
      DBMS_OUTPUT.PUT_LINE('ACTUALIZA IDOC:'||AUX_IDOC);
      UPDATE SVR_DOCUMENTOS SET IDOC=AUX_IDOC WHERE ID=RW.ID;
    END IF;
    AUX_IDOC:=NULL;
--    COMMIT;
    NCOUNT:=NCOUNT+1;
  END LOOP;
  RETURN NCOUNT;
END INS_PARAMETROS_DOC;
