-- PCK_COSEC_DSI1 (owner: SIID_TESTES)


-- ===== SPEC (PACKAGE) =====

PACKAGE PCK_COSEC_DSI1 AS
	   FUNCTION GET_TOMAPOL (V_CDUNIECO NUMBER, V_CDRAMO NUMBER,V_ESTADO VARCHAR2, V_NMPOLIZA NUMBER) RETURN NUMBER;
	   	   FUNCTION GET_ER_PG (PI_CDUNIECO CO_PROROL.CDUNIECO%TYPE, PI_CDRAMO   CO_PROROL.CDRAMO%TYPE, PI_NMPROPUE CO_PROROL.NMPROPUE%TYPE, PI_NMGARANT CO_PROROL.NMGARANT%TYPE) RETURN NUMBER;
END PCK_COSEC_DSI1;


-- ===== BODY (PACKAGE BODY) =====

PACKAGE BODY PCK_COSEC_DSI1 AS

FUNCTION GET_TOMAPOL (V_CDUNIECO  NUMBER,   V_CDRAMO   NUMBER,
                      V_ESTADO    VARCHAR2, V_NMPOLIZA NUMBER) RETURN NUMBER AS

RET MPOLIPER.CDPERSON%TYPE := 0;

BEGIN
   SELECT CDPERSON
   INTO RET
   FROM MPOLIPER a
   WHERE a.CDUNIECO = v_cdunieco
     AND a.CDRAMO   = v_cdramo
     AND a.ESTADO   = V_ESTADO
     AND a.NMPOLIZA = V_NMPOLIZA
	 AND A.STATUS = 'V'
	 AND A.CDROL = 'TO'
     AND a.NMSUPLEM = (SELECT MAX(NMSUPLEM)
                       FROM MPOLIPER AA
                       WHERE AA.CDUNIECO = A.CDUNIECO
                         AND AA.CDRAMO   = A.CDRAMO
                         AND AA.ESTADO   = A.ESTADO
                         AND AA.NMPOLIZA = A.NMPOLIZA
						 AND AA.STATUS = A.STATUS
						 AND AA.CDROL = A.CDROL);

   RETURN RET;

EXCEPTION
  WHEN OTHERS THEN
     RETURN 0;
END;


FUNCTION GET_ER_PG (PI_CDUNIECO CO_PROROL.CDUNIECO%TYPE,
		 		    PI_CDRAMO   CO_PROROL.CDRAMO%TYPE,
                    PI_NMPROPUE CO_PROROL.NMPROPUE%TYPE,
					PI_NMGARANT CO_PROROL.NMGARANT%TYPE) RETURN NUMBER AS
RET NUMBER(9) := 0;

V_NMPROPUE  CO_PROROL.NMPROPUE%TYPE;

BEGIN



	 SELECT MAX(NMSOLICI)
	 INTO V_NMPROPUE
	 FROM MPOLIZAS WHERE
	 	  CDUNIECO=PI_CDUNIECO AND CDRAMO=PI_CDRAMO AND ESTADO='M' AND NMPOLIZA=PI_NMPROPUE;


  SELECT A.CDPERSON
  INTO RET
  FROM CO_PROROL A
  WHERE A.CDUNIECO = PI_CDUNIECO
    AND A.CDRAMO   = PI_CDRAMO
    AND A.NMPROPUE = V_NMPROPUE
    AND A.CDROL    = (SELECT DECODE(PI_CDRAMO,201,'CR',CDROLRIE) FROM MPARAPRO WHERE CDRAMO= PI_CDRAMO)
    AND A.NMGARANT = PI_NMGARANT
    AND A.STATUS   = 'V'
    AND A.NMORDINA = (SELECT MAX(B.NMORDINA)
                      FROM CO_PROROL B
                      WHERE   B.CDUNIECO = A.CDUNIECO
                          AND B.CDRAMO   = A.CDRAMO
                          AND B.NMPROPUE = A.NMPROPUE
                          AND B.CDROL    = A.CDROL
                          AND B.NMGARANT = A.NMGARANT
                          AND B.STATUS   = A.STATUS);
  RETURN RET;
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      RETURN 0;
END;



END PCK_COSEC_DSI1;

