-- PKG_INSTALL_DOC (owner: SIID_TESTES)


-- ===== SPEC (PACKAGE) =====

PACKAGE Pkg_Install_Doc
AS

--* CONSTANTES PROPRIAS QUESTIONAR INFORMAC?ES SOBRE PACKAGE
--*
--* CRIADO POR  : JOSE VIEGAS
--* DATA CRIACAO: 25-11-2004
--* OBSERVAC?O  : A) ESTA SECC?O DEVE ESTAR NO INICIO DO PACKAGE SEMPRE
--*               B) SEMPRE QUE FOR EFECTUADA ALGUMA ALTERAC?O AO PACKAGE
--*                  DEVEM SER ACTUALIZADAS AS CONSTANTES DO PACKAGE BODY
--*                  "VERSAO", "DATA_VERSAO" & "AUTOR_VERSAO".
--*
INFO_VERSAO          CONSTANT VARCHAR2(100):='VERSAO';
INFO_DATA_VERSAO     CONSTANT VARCHAR2(100):='DATA_VERSAO';
INFO_AUTOR_PACKAGE   CONSTANT VARCHAR2(100):='AUTOR_PACKAGE';
INFO_AUTOR_VERSAO    CONSTANT VARCHAR2(100):='AUTOR_VERSAO';
INFO_DATA_PACKAGE    CONSTANT VARCHAR2(100):='DATA_PACKAGE';
INFO_DATA_INSTALACAO CONSTANT VARCHAR2(100):='DATA_INSTALACAO';
INFO_OWNER           CONSTANT VARCHAR2(100):='OWNER';
/*
-* NOME      : GET_PACKINFO
-* OBJECTIVO : MANTER INFORMAC?O SOBRE VERS?O DO PACKAGE
-* UTILIZACAO: PKG_FORMULAS_COSEC.GET_PACKINFO('VERSAO');
-* AUTOR     : Eng. Jose Viegas
-* DATA      : 25-11-2004
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PACKINFO (P_TIPO_INFO VARCHAR2 DEFAULT 'COMPLETE') RETURN VARCHAR2;

FUNCTION TEMPLATE_NOVO (P_NOME_FICHEIRO VARCHAR2) RETURN NUMBER;

FUNCTION DOCUMENTO_NOVO (P_DOCUMENTO_ID VARCHAR2) RETURN NUMBER;

PROCEDURE COPIA_PERMISSOES(P_DOC_BASE VARCHAR2, P_DOC_DESTINO VARCHAR2);

END Pkg_Install_Doc;

-- ===== BODY (PACKAGE BODY) =====

PACKAGE BODY Pkg_Install_Doc AS
/*
-*
-* ULTIMAS ALTERAC?ES AO PACKAGE
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== ===================================================
-*   09-11-2006 JOSE VIEGAS     Criac?o do Pacote
*/
  VERSAO         CONSTANT NUMBER:=001;
  DATA_VERSAO    CONSTANT DATE:= TO_DATE('09-11-2006 18:00','DD-MM-YYYY HH24:MI');
  AUTOR_PACKAGE  CONSTANT VARCHAR2(100):='Eng. Jose Viegas';
  AUTOR_VERSAO   CONSTANT VARCHAR2(100):='JOSE VIEGAS';
/*
-* NOME      : GET_PACKINFO
-* OBJECTIVO : MANTER INFORMAC?O SOBRE VERS?O DO PACKAGE
-* UTILIZACAO: PKG_FORMULAS_COSEC.GET_PACKINFO('VERSAO');
-* AUTOR     : Eng. Jose Viegas
-* DATA      : 25-11-2004
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
  FUNCTION GET_PACKINFO (P_TIPO_INFO VARCHAR2 DEFAULT 'COMPLETE') RETURN VARCHAR2 IS
    AUX VARCHAR2(200);
  BEGIN
    IF P_TIPO_INFO = INFO_VERSAO THEN  /* DEVOLVE VERS?O DO PACKAGE */
      RETURN 'v'||TO_CHAR(VERSAO);
    ELSIF P_TIPO_INFO = INFO_DATA_VERSAO THEN
      RETURN TO_CHAR(DATA_VERSAO,'YYYY-MM-DD HH24:MI');
    ELSIF P_TIPO_INFO = INFO_AUTOR_PACKAGE THEN
      RETURN AUTOR_PACKAGE;
    ELSIF P_TIPO_INFO = INFO_AUTOR_VERSAO THEN
      RETURN AUTOR_VERSAO;
    ELSIF P_TIPO_INFO = INFO_DATA_PACKAGE THEN
      BEGIN
        SELECT
          TO_CHAR(CREATED,'YYYY-MM-DD HH24:MI')
        INTO
          AUX
        FROM
          ALL_OBJECTS
        WHERE
            OBJECT_NAME='PKG_FORMULAS_COSEC'
        AND OBJECT_TYPE='PACKAGE BODY'
        AND OWNER = (SELECT USERNAME FROM USER_USERS);
        RETURN AUX;
      EXCEPTION
        WHEN OTHERS THEN
         RETURN 'PKG_FORMULAS_COSEC v'||VERSAO||'('||TO_CHAR(DATA_VERSAO,'YYMMDDHH24MI')||')';
      END;
    ELSIF P_TIPO_INFO = INFO_DATA_INSTALACAO THEN
      BEGIN
        SELECT
          TO_CHAR(LAST_DDL_TIME,'YYYY-MM-DD HH24:MI')
        INTO
          AUX
        FROM
          ALL_OBJECTS
        WHERE
            OBJECT_NAME='PKG_FORMULAS_COSEC'
        AND OBJECT_TYPE='PACKAGE BODY'
        AND OWNER = (SELECT USERNAME FROM USER_USERS);
        RETURN AUX;
      EXCEPTION
        WHEN OTHERS THEN
         RETURN 'PKG_FORMULAS_COSEC v'||VERSAO||'('||TO_CHAR(DATA_VERSAO,'YYMMDDHH24MI')||')';
      END;
    ELSIF P_TIPO_INFO = INFO_OWNER THEN
      SELECT USERNAME INTO AUX FROM USER_USERS;
      RETURN AUX;
    ELSE
      RETURN 'PKG_FORMULAS_COSEC v'||VERSAO||'('||TO_CHAR(DATA_VERSAO,'YYMMDDHH24MI')||')';
    END IF;
  END GET_PACKINFO;

  FUNCTION TEMPLATE_NOVO (P_NOME_FICHEIRO VARCHAR2) RETURN NUMBER
  IS
    nIDNOVO  NUMBER;
    nIDTESTE NUMBER;
  BEGIN

    SELECT
      ID_TEMPLATE_REPORT_SEQ.NEXTVAL
    , ID
    INTO
      nIDNOVO
    , nIDTESTE
    FROM
      SVR_REPORT_SIID@COSEC
    WHERE
      NOME_FICHEIRO=P_NOME_FICHEIRO;

    INSERT INTO
      SVR_REPORT_SIID
    (
      ID
    , NOME
    , VALIDO
    , NOME_FICHEIRO
    , DIRECTORIA_BASE
    , DIRECTORIA_DESTINO
    , OBSERVACAO
    , CRIADO_POR
    , DATA_CRIACAO
    )
    SELECT
      nIDNOVO
    , NOME
    , VALIDO
    , NOME_FICHEIRO
    , DIRECTORIA_BASE
    , DIRECTORIA_DESTINO
    , OBSERVACAO
    , USER
    , SYSDATE
    FROM
      SVR_REPORT_SIID@COSEC
    WHERE
      ID = NIDTESTE;


    INSERT INTO
      SVR_PARAMETROS_REPORT
    (
      N_PARAMETRO
    , NOME
    , TIPO_PARAMETRO_RF
    , REPORT_ID
    , OBRIGATORIO
    , CHECK_UNIQUE
    , VALIDO
    , DESCRICAO
    , CRIADO_POR
    , DATA_CRIACAO
    )
    SELECT
      N_PARAMETRO
    , NOME
    , TIPO_PARAMETRO_RF
    , nIDNOVO
    , OBRIGATORIO
    , CHECK_UNIQUE
    , VALIDO
    , DESCRICAO
    , USER
    , SYSDATE
    FROM
      SVR_PARAMETROS_REPORT
    WHERE
        REPORT_ID = NIDTESTE;

    RETURN 1;

  EXCEPTION
    WHEN OTHERS THEN
      RETURN -1;
  END TEMPLATE_NOVO;

  FUNCTION DOCUMENTO_NOVO (P_DOCUMENTO_ID VARCHAR2) RETURN NUMBER
  IS
    nTempID VARCHAR2(10);
  BEGIN

    BEGIN
      SELECT
        NOVOTEMPLATE.ID
      INTO
        nTempID
      FROM
        DOC_MODELOS_DOCUMENTO@COSEC DOC
      , SVR_REPORT_SIID@COSEC   TEMP
      , SVR_REPORT_SIID         NOVOTEMPLATE
      WHERE
          DOC.ID = P_DOCUMENTO_ID
      AND TEMP.ID = DOC.REPORT_ID
      AND TEMP.NOME_FICHEIRO = NOVOTEMPLATE.NOME_FICHEIRO;
    EXCEPTION
      WHEN OTHERS THEN
         RETURN 0;
    END;

    INSERT INTO
      DOC_MODELOS_DOCUMENTO
    (
      ID
    , TIPO_DOCUMENTO_RF
    , REPORT_ID
    , N_ANEXOS
    , N_COPIAS
    , FORMA_CONTROLO_RF
    , MAX_IMPRESSOES
    , DATA_INICIO
    , DATA_FIM
    , DESCRICAO
    , GENERICO_ID
    , CRIADO_POR
    , DATA_CRIACAO
    )
    SELECT
      ID
    , TIPO_DOCUMENTO_RF
    , nTempID
    , N_ANEXOS
    , N_COPIAS
    , FORMA_CONTROLO_RF
    , MAX_IMPRESSOES
    , DATA_INICIO
    , DATA_FIM
    , DESCRICAO
    , GENERICO_ID
    , USER
    , SYSDATE
    FROM
      DOC_MODELOS_DOCUMENTO@COSEC
    WHERE
      ID=P_DOCUMENTO_ID;

    INSERT INTO
      DOC_SECCOES_DOCUMENTO
    (
      MODELO_ID
    , TIPOSEC_ID
    , ALINEA
    , TITULO
    , TIPOCNTD_ID
    , TEXTO
    , IMAGEM
    , FORMULA_ID
    , CRIADO_POR
    , DATA_CRIACAO
    )
    SELECT
      MODELO_ID
    , TIPOSEC_ID
    , ALINEA
    , TITULO
    , TIPOCNTD_ID
    , TEXTO
    , IMAGEM
    , FORMULA_ID
    , USER
    , SYSDATE
    FROM
      DOC_SECCOES_DOCUMENTO@COSEC
    WHERE
      MODELO_ID = P_DOCUMENTO_ID;

    INSERT INTO
      DOC_CONDICOES_APR
    (
      MODELO_ID
    , TIPOSEC_ID
    , ALINEA
    , CDUNIECO
    , CDRAMO
    , CONTEXTO_ID
    , ATRIBUTO1
    , ATRIBUTO2
    , ATRIBUTO3
    , ATRIBUTO4
    , ATRIBUTO5
    , ATRIBUTO6
    , ATRIBUTO7
    , ATRIBUTO8
    , DATA_INICIO
    , DATA_FIM
    , CRIADO_POR
    , DATA_CRIACAO
    )
    SELECT
      MODELO_ID
    , TIPOSEC_ID
    , ALINEA
    , CDUNIECO
    , CDRAMO
    , CONTEXTO_ID
    , ATRIBUTO1
    , ATRIBUTO2
    , ATRIBUTO3
    , ATRIBUTO4
    , ATRIBUTO5
    , ATRIBUTO6
    , ATRIBUTO7
    , ATRIBUTO8
    , SYSDATE-1
    , DATA_FIM
    , USER
    , SYSDATE
    FROM
      DOC_CONDICOES_APR@COSEC
    WHERE
      MODELO_ID = P_DOCUMENTO_ID;

    RETURN 1;

  EXCEPTION
    WHEN OTHERS THEN
      RETURN -1;
  END DOCUMENTO_NOVO;

  PROCEDURE COPIA_PERMISSOES(P_DOC_BASE VARCHAR2, P_DOC_DESTINO VARCHAR2)
  IS
  BEGIN

    INSERT INTO DOC_IMPRESSORAS_DOC
    (
      MODELO_ID
    , AMBIENTE_ID
    , IMPRESSORA_ID
    , DATA_INICIO
    , DATA_FIM
    , CRIADO_POR
    , DATA_CRIACAO
    )
    SELECT
      P_DOC_DESTINO
    , AMBIENTE_ID
    , IMPRESSORA_ID
    , DATA_INICIO
    , DATA_FIM
    , USER
    , SYSDATE
    FROM
      DOC_IMPRESSORAS_DOC
    WHERE
      MODELO_ID = P_DOC_BASE;

   /* INSERT INTO
      DOC_PERMISSOES_IMPRESSAO
    (
      MODELO_ID
    , CDDEPARTA
    , CDEMPLEA
    , DATA_INICIO
    , DATA_FIM
    , TIPOPERM_ID
    , CRIADO_POR
    , DATA_CRIACAO
    )
    SELECT
      P_DOC_DESTINO
    , CDDEPARTA
    , CDEMPLEA
    , DATA_INICIO
    , DATA_FIM
    , TIPOPERM_ID
    , USER
    , SYSDATE
    FROM
     DOC_PERMISSOES_IMPRESSAO
    WHERE
      MODELO_ID = P_DOC_BASE;
*/

  END COPIA_PERMISSOES;



END Pkg_Install_Doc;
