-- PKG_FORMULAS_TESTE (owner: SIID_TESTES)


-- ===== SPEC (PACKAGE) =====

PACKAGE PKG_FORMULAS_TESTE AS

/*
   NOME : GET_DECLARACOES_EM_FALTA
   *  OBJECTIVO : RETORNA AS DECLARAC?ES DE VENDA EM FALTA DESDE A DATA DE EMISS?O
   *  UTILIZAC?O:
   *  VERS?O    : 1.0
   *  CRIADO POR: JOAO BONINA
*/
FUNCTION GET_DECLARACOES_EM_FALTA(PIN_CDUNIECO IN INTEGER
						, PIN_CDRAMO IN INTEGER
						, PIN_NMPOLIZA IN INTEGER) RETURN VARCHAR2;


 PRAGMA RESTRICT_REFERENCES (GET_DECLARACOES_EM_FALTA,WNDS);
/*
   NOME : FUN_DATA_EXIGIBILIDADE
   *  OBJECTIVO : Data de Exigibilidade
   *  VERS?O    : 1.0
   *  CRIADO POR: BRIGIDA RAMOS
   *  DATA CRIACAO: 27-JUl-2004
*/
FUNCTION FUN_DATA_EXIGIBILIDADE (PI_CDTIPRAM IN NUMBER
		 		,PI_MODPAG IN NUMBER
				,PI_CDTIPRECI IN NUMBER
				,PI_FEINICIO IN DATE
				,PI_FEEMISIO IN DATE 
				,PI_VALOR IN NUMBER)  RETURN DATE;

PRAGMA RESTRICT_REFERENCES (FUN_DATA_EXIGIBILIDADE,WNDS);						
 

/*
   NOME : FUN_MAX_DATA
   *  OBJECTIVO : RETORNA A MAIOR DE DUAS DATAS
   *  UTILIZAC?O:
   *  VERS?O    : 1.0
   *  CRIADO POR: BRIGIDA RAMOS
*/
FUNCTION FUN_MAX_DATA(PI_DT1 IN DATE 
					, PI_DT2 IN DATE
					) RETURN DATE;


PRAGMA RESTRICT_REFERENCES (FUN_MAX_DATA,WNDS);


END PKG_FORMULAS_TESTE;


-- ===== BODY (PACKAGE BODY) =====

PACKAGE BODY PKG_FORMULAS_TESTE AS

/*
   NOME : GET_DECLARACOES_EM_FALTA
   *  OBJECTIVO : RETORNA AS DECLARAC?ES DE VENDA EM FALTA DESDE A DATA DE EMISS?O
   *  UTILIZAC?O:
   *  VERS?O    : 1.0
   *  CRIADO POR: JOAO BONINA
*/
FUNCTION GET_DECLARACOES_EM_FALTA(PIN_CDUNIECO IN INTEGER, PIN_CDRAMO IN INTEGER, PIN_NMPOLIZA IN INTEGER) RETURN VARCHAR2 AS
	DECLS_EM_FALTA VARCHAR2(5000);
	DATA MPOLIZAS.FEEFECTO%TYPE;
--	DUMMY CO_DECVEN.FEPERDEC%TYPE;
	DUMMY NUMBER;
	SEPARADOR_ANO VARCHAR2(4);
	PRI_MES_ANO NUMBER;
	PRI_VIGENCIA NUMBER;

	CURSOR VIGENCIAS IS
	SELECT
	  APOL.FEEMISIO
	 ,APOL.FEEFECTO
	 ,APOL.FEPROREN
     ,ATRIB.OTVALOR
	FROM
	  MPOLIZAS APOL
	 ,TVALOPOL ATRIB
	WHERE 1=1
	AND ATRIB.CDATRIBU = 15
	AND ATRIB.CDRAMO   = APOL.CDRAMO
	AND ATRIB.CDUNIECO = APOL.CDUNIECO
	AND ATRIB.NMPOLIZA = APOL.NMPOLIZA
	AND ATRIB.ESTADO   = APOL.ESTADO
	AND ATRIB.NMSUPLEM = (
	                     SELECT
						   MAX(X.NMSUPLEM)
						 FROM
						   TVALOPOL X
						 WHERE
						 1=1
						 AND X.CDUNIECO = ATRIB.CDUNIECO
						 AND X.CDRAMO   = ATRIB.CDRAMO
						 AND X.NMPOLIZA = ATRIB.NMPOLIZA
						 AND X.ESTADO   = ATRIB.ESTADO
						 AND X.CDATRIBU = ATRIB.CDATRIBU
						 AND  X.NMSUPLEM  <= TO_CHAR(DECODE(APOL.OTTEMPOT, 'T', APOL.FEVENCIM, APOL.FEPROREN),'J')||'99999999999'
						 )
	AND APOL.NMRENOVA >= (
	                     SELECT
						   MAX(X.NMRENOVA-1)
						 FROM
						   MPOLIZAS X
				 		 WHERE
						     X.NMPOLIZA = APOL.NMPOLIZA
						 AND X.ESTADO = APOL.ESTADO
						 AND X.CDRAMO = APOL.CDRAMO
						 AND X.CDUNIECO = APOL.CDUNIECO
				         )
 	AND APOL.NMPOLIZA = PIN_NMPOLIZA
	AND APOL.CDRAMO   = PIN_CDRAMO
	AND APOL.CDUNIECO = PIN_CDUNIECO;

BEGIN
	SEPARADOR_ANO := '1500';
	PRI_MES_ANO := 1;
	PRI_VIGENCIA := 1;

	FOR RW IN VIGENCIAS LOOP
		IF PRI_VIGENCIA = 0 THEN
			DATA := RW.FEEFECTO;
		ELSE
			DATA := ADD_MONTHS(RW.FEEFECTO, RW.OTVALOR);
			PRI_VIGENCIA := 0;
		END IF;
		WHILE (DATA < RW.FEPROREN) LOOP
		BEGIN
			IF (DATA >= ADD_MONTHS(SYSDATE, -1)) THEN
				RETURN DECLS_EM_FALTA;
			ELSE
				BEGIN
			 	SELECT COUNT(DECVEN.FEPERDEC)
				INTO DUMMY
				FROM CO_DECVEN DECVEN
				WHERE
				1=1
				AND DECVEN.FEPERDEC = TO_CHAR(DATA, 'MON-RR')
				AND DECVEN.NMORDEN  = 1
				AND DECVEN.nmpoliza = PIN_NMPOLIZA
				AND DECVEN.CDRAMO   = PIN_CDRAMO
  				AND DECVEN.cdunieco = PIN_CDUNIECO;
				IF DUMMY=0 then
					IF DECLS_EM_FALTA IS NULL THEN
						IF SEPARADOR_ANO != TO_CHAR(DATA, 'RRRR') THEN
							SEPARADOR_ANO := TO_CHAR(DATA, 'RRRR');
							PRI_MES_ANO := 0;
							IF SEPARADOR_ANO = TO_CHAR(ADD_MONTHS(DATA, -1), 'RRRR') THEN
								DECLS_EM_FALTA := CHR(10)||SEPARADOR_ANO||CHR(10)||TRIM(TO_CHAR(ADD_MONTHS(DATA, -1), 'MONTH'));
							ELSE
								DECLS_EM_FALTA := TRIM(TO_CHAR(ADD_MONTHS(DATA, -12), 'RRRR'))||CHR(10)||TRIM(TO_CHAR(ADD_MONTHS(DATA, -1), 'MONTH'));
							END IF;
						ELSE
							DECLS_EM_FALTA := TRIM(TO_CHAR(ADD_MONTHS(DATA, -1), 'MONTH'));
						END IF;
					ELSE
						IF SEPARADOR_ANO != TO_CHAR(DATA, 'RRRR') THEN
							SEPARADOR_ANO := TO_CHAR(DATA, 'RRRR');
							PRI_MES_ANO := 1;
							IF SEPARADOR_ANO = TO_CHAR(ADD_MONTHS(DATA, -1), 'RRRR') THEN
								DECLS_EM_FALTA := DECLS_EM_FALTA||CHR(10)||SEPARADOR_ANO||CHR(10)||TRIM(TO_CHAR(ADD_MONTHS(DATA, -1), 'MONTH'));
							ELSE
								DECLS_EM_FALTA := DECLS_EM_FALTA||', '||TRIM(TO_CHAR(ADD_MONTHS(DATA, -1), 'MONTH'))||CHR(10)||SEPARADOR_ANO||CHR(10);
							END IF;
						ELSE
							IF PRI_MES_ANO = 1 THEN
								PRI_MES_ANO := 0;
								DECLS_EM_FALTA := DECLS_EM_FALTA||TRIM(TO_CHAR(ADD_MONTHS(DATA, -1), 'MONTH'));
							ELSE
								DECLS_EM_FALTA := DECLS_EM_FALTA||', '||TRIM(TO_CHAR(ADD_MONTHS(DATA, -1), 'MONTH'));
							END IF;
						END IF;
					END IF;
				END IF;
                END;
				DATA := ADD_MONTHS(DATA, RW.OTVALOR);
			END IF;
		END;
		END LOOP;
	END LOOP;
	RETURN DECLS_EM_FALTA;
END;

FUNCTION FUN_MAX_DATA(PI_DT1 IN DATE 
					, PI_DT2 IN DATE
					) RETURN DATE
					
IS
BEGIN
  			IF (PI_DT1>=PI_DT2) THEN
			   RETURN PI_DT1;
			ELSE
				RETURN PI_DT2;
			END IF;
END FUN_MAX_DATA;									




FUNCTION FUN_DATA_EXIGIBILIDADE (PI_CDTIPRAM IN NUMBER
		 		,PI_MODPAG IN NUMBER
				,PI_CDTIPRECI IN NUMBER
				,PI_FEINICIO IN DATE
				,PI_FEEMISIO IN DATE
				,PI_VALOR IN NUMBER )  RETURN DATE

IS



BEGIN
	
	
	IF (PI_CDTIPRECI IN (79,82,83,90,91,92,95,96,97)) THEN
	   RETURN PI_FEEMISIO+30;
	
	ELSE
		IF (PI_VALOR>=0) THEN
	
			IF (PI_CDTIPRECI=0) THEN
			    RETURN FUN_MAX_DATA(PI_FEINICIO,PI_FEEMISIO);
			END IF;

			IF (PI_CDTIPRECI=1) THEN
				RETURN FUN_MAX_DATA(PI_FEINICIO,PI_FEEMISIO+40);
			END IF;

			IF (PI_CDTIPRECI=2) THEN
				IF (PI_CDTIPRAM=1) THEN
				   IF (PI_MODPAG=1) THEN
				   	  RETURN FUN_MAX_DATA(PI_FEINICIO,PI_FEEMISIO);
			   	    ELSE
					  RETURN FUN_MAX_DATA(PI_FEINICIO,PI_FEEMISIO+40);
				    END IF;	
				ELSE 
					  RETURN FUN_MAX_DATA(PI_FEINICIO,PI_FEEMISIO+40);
			   	END IF;				 			
			END IF;

			IF (PI_CDTIPRECI=3) THEN
				IF (PI_CDTIPRAM=1) THEN	
				  RETURN FUN_MAX_DATA(PI_FEINICIO,PI_FEEMISIO);	
				ELSE	
				  RETURN FUN_MAX_DATA(PI_FEINICIO,PI_FEEMISIO+40);
				END IF;
			END IF;
		
			IF (PI_CDTIPRECI=4) THEN
   			   RETURN FUN_MAX_DATA(PI_FEINICIO,PI_FEEMISIO+40);
			END IF;

			IF (PI_CDTIPRECI=7) THEN
			   RETURN FUN_MAX_DATA(PI_FEINICIO,PI_FEEMISIO+40);
			END IF;	

			IF (PI_CDTIPRECI=8) THEN
				IF (PI_CDTIPRAM=1) THEN
 				    RETURN FUN_MAX_DATA(PI_FEINICIO,PI_FEEMISIO);	
				ELSE
			   		RETURN FUN_MAX_DATA(PI_FEINICIO,PI_FEEMISIO+40);
				END IF;
			END IF;       
		
			IF (PI_CDTIPRECI=93) THEN
			   RETURN FUN_MAX_DATA(PI_FEINICIO,PI_FEEMISIO+40);
			END IF;

			IF (PI_CDTIPRECI=98) THEN
			   RETURN FUN_MAX_DATA(PI_FEINICIO,PI_FEEMISIO+40);
			END IF;
		
			IF (PI_CDTIPRECI=99) THEN
			   RETURN FUN_MAX_DATA(PI_FEINICIO,PI_FEEMISIO+40);
			END IF;

		ELSE
				RETURN NULL;
		END IF; 	

	 END IF;	
	
	 RETURN NULL;
	 
END FUN_DATA_EXIGIBILIDADE;

END;

