-- PKG_RESSEGURO_COSEC (owner: SIID_TESTES)


-- ===== SPEC (PACKAGE) =====

PACKAGE "PKG_RESSEGURO_COSEC" AS
--* CONSTANTES PROPRIAS QUESTIONAR INFORMAC?ES SOBRE PACKAGE
--*
--* CRIADO POR  : JOSE VIEGAS
--* DATA CRIACAO: 25-11-2004
--* OBSERVAC?O  : A) ESTA SECC?O DEVE ESTAR NO INICIO DO PACKAGE SEMPRE
--*               B) SEMPRE QUE FOR EFECTUADA ALGUMA ALTERAC?O AO PACKAGE
--*                  DEVEM SER ACTUALIZADAS AS CONSTANTES DO PACKAGE BODY
--*                  "VERSAO", "DATA_VERSAO" & "AUTOR_VERSAO".
--*
INFO_VERSAO          CONSTANT VARCHAR2(100):='VERSAO';
INFO_DATA_VERSAO     CONSTANT VARCHAR2(100):='DATA_VERSAO';
INFO_AUTOR_PACKAGE   CONSTANT VARCHAR2(100):='AUTOR_PACKAGE';
INFO_AUTOR_VERSAO    CONSTANT VARCHAR2(100):='AUTOR_VERSAO';
INFO_DATA_PACKAGE    CONSTANT VARCHAR2(100):='DATA_PACKAGE';
INFO_DATA_INSTALACAO CONSTANT VARCHAR2(100):='DATA_INSTALACAO';
INFO_OWNER           CONSTANT VARCHAR2(100):='OWNER';
/*
-* NOME      : GET_PACKINFO
-* OBJECTIVO : MANTER INFORMAC?O SOBRE VERS?O DO PACKAGE
-* UTILIZACAO: PKG_FORMULAS_COSEC.GET_PACKINFO('VERSAO');
-* AUTOR     : Eng. Jose Viegas
-* DATA      : 25-11-2004
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PACKINFO (P_TIPO_INFO VARCHAR2 DEFAULT 'COMPLETE') RETURN VARCHAR2;
/*
-* NOME      : GET_SHARE_TRATADO
-* OBJECTIVO : RETORNA A PERCENTAGEM DE PARTICIPAC?O DA COMPANHIA NO TRATADO DE QUOTA-PARTE
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 11-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_SHARE_TRATADO    ( PI_MODALI   IN NUMBER
		 	       ,PI_CDAGRUPA IN VARCHAR2
           		       ,PI_CDCIA    IN VARCHAR2
				) RETURN NUMBER ;
/*
-* NOME      : GET_BALANCO_PERIODO
-* OBJECTIVO : RETORNA O VALOR DO BALANCO PARA O PERIODO, RESSEGURADORA E TRATADO ESCOLHIDO
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 11-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_BALANCO_PERIODO (PI_CDCIA IN VARCHAR2
			      ,PI_TRATADO IN VARCHAR2
			      ,PI_ANO IN VARCHAR2
			      ,PI_TRIMESTRE IN VARCHAR2) RETURN NUMBER;
/*
-* NOME      : GET_BALANCODIR_PERIODO
-* OBJECTIVO : RETORNA O VALOR DO BALANCO PARA O PERIODO, RESSEGURADORA E TRATADO ESCOLHIDO
-*		CDCONLIQ=921
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 14-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_BALANCODIR_PERIODO (PI_CDCIA IN VARCHAR2
			      ,PI_TRATADO IN VARCHAR2
			      ,PI_ANO IN VARCHAR2
			      ,PI_TRIMESTRE IN VARCHAR2) RETURN NUMBER;
/*
-* NOME      : GET_CONTABILIDADE
-* OBJECTIVO : RETORNA O SALDO CONTABILISTICO PARA UMA DETERMINADA RESEGURADORA NUM DETERMINADO PERIODO
-* UTILIZACAO:
-* AUTOR     : JOSE VIEGAS
-* DATA      : 01-08-2006
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_CONTABILIDADE (PI_CDCIA IN VARCHAR2
			   ,PI_ANO IN VARCHAR2
			   ,PI_TRIMESTRE IN VARCHAR2
                           ,PI_MODALI IN VARCHAR2 ) RETURN NUMBER ;
/*
-* NOME      : GET_SALDOFIN_ANTERIOR
-* OBJECTIVO : RETORNA O SALDO FINANCEIRO PARA UMA DETERMINADA RESEGURADORA NUM DETERMINADO PERIODO
-*		CDCONLIQ=922
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 14-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_SALDOFIN_ANTERIOR (PI_CDCIA IN VARCHAR2
			      ,PI_ANO IN VARCHAR2
			      ,PI_TRIMESTRE IN VARCHAR2) RETURN NUMBER;
/*
-* NOME      : GET_SALDOFIN_ACTUAL
-* OBJECTIVO : RETORNA O SALDO FINANCEIRO PARA UMA DETERMINADA RESEGURADORA NUM DETERMINADO PERIODO
-*		CDCONLIQ=922
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 22-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_SALDOFIN_ACTUAL (PI_CDCIA IN VARCHAR2
			      ,PI_ANO IN VARCHAR2
			      ,PI_TRIMESTRE IN VARCHAR2) RETURN NUMBER ;
/*
-* NOME      : GET_SALDOTEC_CAUCAO
-* OBJECTIVO : RETORNA O SALDO TECNICO  PARA UM DETERMINADO PERIODO
-*		CDCONLIQ=921 E CDAGRUPA=QPCAUC?O
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 22-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_SALDOTEC_CAUCAO (PI_CDCIA IN VARCHAR2
			      ,PI_ANO IN VARCHAR2
			      ,PI_TRIMESTRE IN VARCHAR2) RETURN NUMBER ;
/*
-* NOME      : GET_SALDOTEC_CREDITO
-* OBJECTIVO : RETORNA O SALDO TECNICO  PARA UM DETERMINADO PERIODO
-*		CDCONLIQ=921 E CDAGRUPA=QPCREDTO
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 22-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_SALDOTEC_CREDITO (PI_CDCIA IN VARCHAR2
			      ,PI_ANO IN VARCHAR2
			      ,PI_TRIMESTRE IN VARCHAR2) RETURN NUMBER ;
/*
-* NOME      : GET_SALDOTEC_FACULTATIVO
-* OBJECTIVO : RETORNA O SALDO TECNICO  PARA UM DETERMINADO PERIODO
-*		CDCONLIQ=921 E CDAGRUPA=FAC./OL.
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 22-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_SALDOTEC_FACULTATIVO (PI_CDCIA IN VARCHAR2
			      ,PI_ANO IN VARCHAR2
			      ,PI_TRIMESTRE IN VARCHAR2) RETURN NUMBER ;
/*
-* NOME      : GET_SALDO_PAGAMENTOS
-* OBJECTIVO : RETORNA O VALOR DOS PAGAMENTOS  PARA UM DETERMINADO PERIODO
-*		CDCONLIQ=800
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 22-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_SALDO_PAGAMENTOS (PI_CDCIA IN VARCHAR2
			      ,PI_ANO IN VARCHAR2
			      ,PI_TRIMESTRE IN VARCHAR2) RETURN NUMBER;
/*
-* NOME      : GET_SALDO_BALANCO
-* OBJECTIVO : RETORNA O VALOR DO BALANCO
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 22-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_SALDO_BALANCO    (PI_CDCIA IN VARCHAR2
			      ,PI_ANO IN VARCHAR2
			      ,PI_TRIMESTRE IN VARCHAR2) RETURN NUMBER ;
/*
-* NOME      : GET_IBNR_RESERVES_PERIODO
-* OBJECTIVO : RETORNA O VALOR DOS CONCEITOS 202 + 201 PARA UM DETERMINADO PERIODO
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 15-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_IBNR_RESERVES_PERIODO (PI_CDCIA IN VARCHAR2
			      ,PI_TRATADO IN VARCHAR2
			      ,PI_ANO IN VARCHAR2
			      ,PI_TRIMESTRE IN VARCHAR2
			      ,PI_CDRAMO IN VARCHAR2) RETURN NUMBER ;
/*
-* NOME      : GET_IBNR_RESERVES
-* OBJECTIVO : RETORNA O VALOR DOS CONCEITOS 202 + 201 PARA UM DETERMINADO PERIODO
-* UTILIZACAO: R6.C1
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 15-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_IBNR_RESERVES (PI_CDCIA IN VARCHAR2
			      ,PI_TRATADO IN VARCHAR2
			      ,PI_ANO IN VARCHAR2
			      ,PI_TRIMESTRE IN VARCHAR2
			      ) RETURN NUMBER ;
/*
-* NOME      : GET_PERC_COMISSAO_RESSEG
-* OBJECTIVO : RETORNA A PERCENTAGEM DE COMISSAO DE RESSEGURO
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 17-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PERC_COMISSAO_RESSEG (PI_CDCIA IN VARCHAR2
			    ,PI_CDCONTRE IN VARCHAR2
			    ,PI_NMCESRAM IN NUMBER
			    ,PI_DTEMISSAO IN DATE
			    ,PI_NMPOLIZA IN NUMBER
			    ,PI_ESTADO  IN VARCHAR2
			    ,PI_CDRAMO IN NUMBER
			    ,PI_CDUNIECO IN NUMBER
			    ) RETURN NUMBER ;
/*
-* NOME      : GET_ANOS_EXERCICIO
-* OBJECTIVO : RETORNA OS ANOS DE EXERCICIO A CONSIDERAR
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 24-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_ANOS_EXERCICIO   (PI_ANO_EXERCICIO IN NUMBER
			      ,PI_ANO_OCORRENCIA IN NUMBER
			      ,PI_ANO_CORRENTE IN NUMBER
			      ) RETURN VARCHAR2;
/*
-* NOME      : GET_COMISSAO_DEFINITIVA
-* OBJECTIVO : RETORNA A PERCENTAGEM DA COMISSAO DEFINITIVA
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 25-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_COMISSAO_DEFINITIVA (PI_CDAGRUPA IN VARCHAR2
				  ,PI_MODALI IN VARCHAR2
				  ,PI_LRATIO IN NUMBER
			      ) RETURN NUMBER;
/*
-* NOME      : GET_LOSS_RATIO
-* OBJECTIVO : RETORNA O LOSS RATIO
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 25-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_LOSS_RATIO (  PI_CDCIA    IN NUMBER
			  ,PI_CDAGRUPA IN VARCHAR2
			  ,PI_MODALI IN VARCHAR2
			  ,PI_EXERCICIO IN NUMBER
		      ) RETURN NUMBER ;
/*
-* NOME      : GET_PRCT_DESP_GERAIS
-* OBJECTIVO : RETORNA O VALOR DA PERCENTAGEM DE TRATADO PARA DESPESAS GERAIS
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 28-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PRCT_DESP_GERAIS(  PI_MODALI    IN NUMBER
				,PI_CDAGRUPA IN VARCHAR2
		      ) RETURN NUMBER;
/*
-* NOME      : GET_TRIMESTRE
-* OBJECTIVO : RETORNA O TRIMESTRE A QUE PERTENCE UMA DETERMINADA DATA
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 28-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_TRIMESTRE (PI_DATA IN DATE) RETURN NUMBER;
/*
-* NOME      : GET_PRCT_PART_RESULT
-* OBJECTIVO : RETORNA O VALOR DA PERCENTAGEM DE PARTICIPACAO DE RESULTADOS
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 08-03-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PRCT_PART_RESULT(  PI_MODALI    IN NUMBER
				,PI_CDAGRUPA IN VARCHAR2
		     		 ) RETURN NUMBER;

/*
-* NOME      : GET_PART_ANO
-* UTILIZACAO: R6.C5
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 06-12-2007
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PART_ANO (PI_CDCIA IN VARCHAR2
			   ,P_ANO_EXERCICIO IN VARCHAR2
			   ,P_ANO_SUBSCRICAO IN VARCHAR2) RETURN NUMBER ;

/*
-* NOME      : GET_PROVISAO
-* OBJECTIVO : RETORNA O VALOR DOS CONCEITOS 201 PARA UM DETERMINADO PERIODO
-* UTILIZACAO: R6.C4 e R6.C5
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 15-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PROVISAO (PI_CDCIA IN VARCHAR2
			      ,PI_ANO IN VARCHAR2
			      ,PI_TRIMESTRE IN VARCHAR2
                              ,PI_MODALI IN VARCHAR2) RETURN NUMBER;
/*
-* NOME      : GET_IBNR
-* OBJECTIVO : RETORNA O VALOR DOS CONCEITOS 202  PARA UM DETERMINADO PERIODO
-* UTILIZACAO: R6.C4 e R6.C5
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 15-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_IBNR (PI_CDCIA IN VARCHAR2
			      ,PI_ANO IN VARCHAR2
			      ,PI_TRIMESTRE IN VARCHAR2
                              ,PI_MODALI IN VARCHAR2 ) RETURN NUMBER ;
/*
-* NOME      : GET_PROVISAO_CONCEITO
-* OBJECTIVO : RETORNA O VALOR DOS CONCEITOS 201 PARA UM DETERMINADO PERIODO
-* UTILIZACAO: R6.C4
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 15-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PROVISAO_CONCEITO (PI_CDCIA IN VARCHAR2
			      ,PI_CDAGRUPA IN VARCHAR2
				,PI_ANO IN VARCHAR2
			      ,PI_TRIMESTRE IN VARCHAR2
                              ,PI_MODALI IN VARCHAR2) RETURN NUMBER;
/*
-* NOME      : GET_IBNR_CONCEITO
-* OBJECTIVO : RETORNA O VALOR DOS CONCEITOS 202  PARA UM DETERMINADO PERIODO
-* UTILIZACAO: R6.C4
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 15-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_IBNR_CONCEITO (PI_CDCIA IN VARCHAR2
			,PI_CDAGRUPA IN VARCHAR2
			      ,PI_ANO IN VARCHAR2
			      ,PI_TRIMESTRE IN VARCHAR2
                              ,PI_MODALI IN VARCHAR2) RETURN NUMBER ;
/*
-* NOME      : GET_PREMIO_RESERVE
-* OBJECTIVO : RETORNA O VALOR DOS CONCEITOS 203 PARA UM DETERMINADO PERIODO
-* UTILIZACAO: R6.C5
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 15-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PREMIO_RESERVE (PI_CDCIA IN VARCHAR2
			      ,PI_ANO IN VARCHAR2
			      ,PI_TRIMESTRE IN VARCHAR2
                              ,PI_MODALI IN VARCHAR2) RETURN NUMBER;

FUNCTION GET_PREMIO_RESERVE_TRAT (PI_CDCIA IN VARCHAR2
			      ,PI_TRATADO IN VARCHAR2
				  ,PI_ANO IN VARCHAR2
			      ,PI_TRIMESTRE IN VARCHAR2
                  ,PI_MODALI IN VARCHAR2
				  ) RETURN NUMBER;
/*
-* NOME      : GET_TIPOCONTR_RESSEG
-* OBJECTIVO : RETORNA O TIPO DE CONTRATO DE RESSEGURO
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 11-05-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_TIPOCONTR_RESSEG ( P_CDUNIECO IN NUMBER
                                , P_CDRAMO IN NUMBER
				, P_AAAPERTU IN NUMBER
				, P_STATUS IN VARCHAR2
				, P_NMSINIES IN NUMBER
                                , P_DATA_REF IN DATE) RETURN VARCHAR2;
/*
-* NOME      : GET_PART_DESPESAS
-* UTILIZACAO: R6.C5
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 15-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PART_DESPESAS (PI_CDCIA IN VARCHAR2
			      ,P_ANO_EXERCICIO IN VARCHAR2
			      ,P_ANO_SUBSCRICAO IN VARCHAR2
                              ) RETURN NUMBER;
/*
-* NOME      : GET_CEDENCIA
-* UTILIZACAO: M151
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 11-06-2007
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_CEDENCIA       (PI_CDUNIECO IN NUMBER
                             ,PI_CDRAMO IN NUMBER
                             ,PI_ESTADO IN VARCHAR2
                             ,PI_NMPOLIZA IN NUMBER
                             ) RETURN VARCHAR2;


/*
-* NOME      : GET_AJUSTE_COMISSAO
-* UTILIZACAO: R6.C4
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 06-12-2007
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_AJUSTE_COMISSAO (PI_CDCIA IN VARCHAR2
               ,P_CDAGRUPA IN VARCHAR2
			   ,P_ANO_EXERCICIO IN VARCHAR2
			   ,P_ANO_SUBSCRICAO IN VARCHAR2) RETURN NUMBER ;

/*
-* NOME      : GET_PART_ANO_TRAT
-* UTILIZACAO: R6.C1
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 06-12-2007
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PART_ANO_TRAT (PI_CDCIA IN VARCHAR2
			   ,P_ANO_EXERCICIO IN VARCHAR2
			   ,P_ANO_SUBSCRICAO IN VARCHAR2
			   ,P_TRATADO IN VARCHAR2) RETURN NUMBER ;

/*
-* NOME      : GET_PART_ANO_TRAT_388
-* UTILIZACAO: R6.C1
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 06-12-2007
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PART_ANO_TRAT_388 (PI_CDCIA IN VARCHAR2
			   ,P_ANO_EXERCICIO IN VARCHAR2
			   ,P_ANO_SUBSCRICAO IN VARCHAR2
			   ,P_TRATADO IN VARCHAR2) RETURN NUMBER ;

/*
-* NOME      : GET_PART_DESPESAS_TRAT
-* UTILIZACAO: R6.C5
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 15-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PART_DESPESAS_TRAT (PI_CDCIA IN VARCHAR2
         ,P_TRATADO IN VARCHAR2
			   ,P_ANO_EXERCICIO IN VARCHAR2
			   ,P_ANO_SUBSCRICAO IN VARCHAR2
			   ) RETURN NUMBER;
/****************************/
 PRAGMA RESTRICT_REFERENCES (GET_PACKINFO,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_SHARE_TRATADO,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_BALANCO_PERIODO,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_BALANCODIR_PERIODO,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_SALDOFIN_ANTERIOR,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_SALDOFIN_ACTUAL,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_SALDOTEC_CAUCAO,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_SALDOTEC_CREDITO,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_SALDOTEC_FACULTATIVO,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_CONTABILIDADE,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_SALDO_PAGAMENTOS,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_IBNR_RESERVES_PERIODO,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_PERC_COMISSAO_RESSEG,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_SALDO_BALANCO,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_ANOS_EXERCICIO,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_COMISSAO_DEFINITIVA,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_LOSS_RATIO,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_PRCT_DESP_GERAIS,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_TRIMESTRE,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_PRCT_PART_RESULT,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_IBNR_RESERVES,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_IBNR,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_PROVISAO,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_PROVISAO_CONCEITO,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_IBNR_CONCEITO,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_PREMIO_RESERVE,WNDS);
  PRAGMA RESTRICT_REFERENCES (GET_PREMIO_RESERVE_TRAT,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_TIPOCONTR_RESSEG,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_PART_DESPESAS,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_PART_DESPESAS_TRAT,WNDS);
 PRAGMA RESTRICT_REFERENCES (GET_CEDENCIA,WNDS);
 PRAGMA RESTRICT_REFERENCES ( GET_PART_ANO,WNDS);
  PRAGMA RESTRICT_REFERENCES ( GET_PART_ANO_TRAT,WNDS);
    PRAGMA RESTRICT_REFERENCES ( GET_PART_ANO_TRAT_388,WNDS);
  PRAGMA RESTRICT_REFERENCES ( GET_AJUSTE_COMISSAO,WNDS);

END Pkg_Resseguro_Cosec;

-- ===== BODY (PACKAGE BODY) =====

PACKAGE BODY "PKG_RESSEGURO_COSEC" AS
/*
-*
-* ULTIMAS ALTERAC?ES AO PACKAGE
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== ===================================================
-*   25-11-2004 JOSE VIEGAS     Acrescentado controlo de vers?es do package
-*   14-02-2005 BRIGIDA RAMOS   Acrescentada func?o GET_BALANCO_PERIODO
-*   14-02-2005 BRIGIDA RAMOS   Acrescentada func?o GET_BALANCODIR_PERIODO
-*   14-02-2005 BRIGIDA RAMOS   Acrescentada func?o GET_SALDOFIN_ANTERIOR
-*   15-02-2005 BRIGIDA RAMOS   Acrescentada func?o GET_IBNR_RESERVES_PERIODO
-*   17-02-2005 BRIGIDA RAMOS   Acrescentada func?o GET_PERC_COMISSAO_RESSEG
-*   22-02-2005 BRIGIDA RAMOS   Acrescentada func?o GET_SALDOFIN_ACTUAL
-*   22-02-2005 BRIGIDA RAMOS   Acrescentada func?o GET_SALDOTEC_CAUCAO
-*   22-02-2005 BRIGIDA RAMOS   Acrescentada func?o GET_SALDOTEC_CREDITO
-*   22-02-2005 BRIGIDA RAMOS   Acrescentada func?o GET_SALDOTEC_FACULTATIVO
-*   22-02-2005 BRIGIDA RAMOS   Acrescentada func?o GET_SALDO_PAGAMENTOS
-*   22-02-2005 BRIGIDA RAMOS   Acrescentada func?o GET_SALDO_BALANCO
-*   24-02-2005 BRIGIDA RAMOS   Acrescentada func?o GET_ANOS_EXERCICIO
-*   24-02-2005 BRIGIDA RAMOS   Acrescentada func?o GET_COMISSAO_DEFINITIVA
-*   24-02-2005 BRIGIDA RAMOS   Acrescentada func?o GET_LOSS_RATION
-*   28-02-2005 BRIGIDA RAMOS   Acrescentada func?o GET_PRCT_DESP_GERAIS
-*   28-02-2005 BRIGIDA RAMOS   Acrescentada func?o GET_TRIMESTRE
-*   08-03-2005 BRIGIDA RAMOS   Acrescentada func?o GET_PRCT_PART_RESULT
-*   15-03-2005 BRIGIDA RAMOS   Correcc?o func?o GET_SALDOFIN_ANTERIOR
-*   15-03-2005 BRIGIDA RAMOS   Correcc?o func?o GET_SALDOFIN_ACTUAL
-*   16-03-2005 BRIGIDA RAMOS   Correcc?o func?o GET_IBNR_RESERVES_PERIODO
-*   16-03-2005 BRIGIDA RAMOS   Acrescentada func?o GET_IBNR_RESERVES
-*   16-03-2005 BRIGIDA RAMOS   Acrescentada func?o GET_IBNR
-*   16-03-2005 BRIGIDA RAMOS   Acrescentada func?o GET_PROVISAO
-*   16-03-2005 BRIGIDA RAMOS   Acrescentada func?o GET_IBNR_CONCEITO
-*   16-03-2005 BRIGIDA RAMOS   Acrescentada func?o GET_PROVISAO_CONCEITO
-*   16-03-2005 BRIGIDA RAMOS   Acrescentada func?o GET_PREMIO_RESERVE
-*   21-03-2005 BRIGIDA RAMOS   Correcc?o func?o GET_SALDOFIN_ANTERIOR
-*   21-03-2005 BRIGIDA RAMOS   Correcc?o func?o GET_SALDOFIN_ACTUAL
-*   11-05-2005 BRIGIDA RAMOS   Nova func?o GET_TIPOCONTR_RESSEG
-*   19-05-2005 BRIGIDA RAMOS   Nova func?o GET_SHARE_TRATADO
-*   01-08-2006 JOSE VIEGAS     NOVA FUNC?O GET_CONTABILIDADE PARA SELECCIONAR IMPRRESS?O
-*   03-01-2007 JOSE VIEGAS     ALTERAC?O DA FUNC?O GET_PROVISAO
-*   11-06-2007 BRIGIDA RAMOS   ACRESCENTADA FUNC?O GET_CEDENCIA
*/
  VERSAO         CONSTANT NUMBER:=017;
  DATA_VERSAO    CONSTANT DATE:= TO_DATE('11-06-2007 10:30','DD-MM-YYYY HH24:MI');
  AUTOR_PACKAGE  CONSTANT VARCHAR2(100):='Eng. Jose Viegas';
  AUTOR_VERSAO   CONSTANT VARCHAR2(100):='BRIGIDA RAMOS';
/*
-* NOME      : GET_PACKINFO
-* OBJECTIVO : MANTER INFORMAC?O SOBRE VERS?O DO PACKAGE
-* UTILIZACAO: PKG_RESSEGURO_COSEC.GET_PACKINFO('VERSAO');
-* AUTOR     : Eng. Jose Viegas
-* DATA      : 25-11-2004
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
  FUNCTION GET_PACKINFO (P_TIPO_INFO VARCHAR2 DEFAULT 'COMPLETE') RETURN VARCHAR2 IS
    AUX VARCHAR2(200);
  BEGIN
    IF P_TIPO_INFO = INFO_VERSAO THEN  /* DEVOLVE VERS?O DO PACKAGE */
      RETURN 'v'||TO_CHAR(VERSAO);
    ELSIF P_TIPO_INFO = INFO_DATA_VERSAO THEN
      RETURN TO_CHAR(DATA_VERSAO,'YYYY-MM-DD HH24:MI');
    ELSIF P_TIPO_INFO = INFO_AUTOR_PACKAGE THEN
      RETURN AUTOR_PACKAGE;
    ELSIF P_TIPO_INFO = INFO_AUTOR_VERSAO THEN
      RETURN AUTOR_VERSAO;
    ELSIF P_TIPO_INFO = INFO_DATA_PACKAGE THEN
      BEGIN
        SELECT
          TO_CHAR(CREATED,'YYYY-MM-DD HH24:MI')
        INTO
          AUX
        FROM
          ALL_OBJECTS
        WHERE
            OBJECT_NAME='PKG_FORMULAS_COSEC'
        AND OBJECT_TYPE='PACKAGE BODY'
        AND OWNER = (SELECT USERNAME FROM USER_USERS);
        RETURN AUX;
      EXCEPTION
        WHEN OTHERS THEN
         RETURN 'PKG_FORMULAS_COSEC v'||VERSAO||'('||TO_CHAR(DATA_VERSAO,'YYMMDDHH24MI')||')';
      END;
    ELSIF P_TIPO_INFO = INFO_DATA_INSTALACAO THEN
      BEGIN
        SELECT
          TO_CHAR(LAST_DDL_TIME,'YYYY-MM-DD HH24:MI')
        INTO
          AUX
        FROM
          ALL_OBJECTS
        WHERE
            OBJECT_NAME='PKG_FORMULAS_COSEC'
        AND OBJECT_TYPE='PACKAGE BODY'
        AND OWNER = (SELECT USERNAME FROM USER_USERS);
        RETURN AUX;
      EXCEPTION
        WHEN OTHERS THEN
         RETURN 'PKG_FORMULAS_COSEC v'||VERSAO||'('||TO_CHAR(DATA_VERSAO,'YYMMDDHH24MI')||')';
      END;
    ELSIF P_TIPO_INFO = INFO_OWNER THEN
      SELECT USERNAME INTO AUX FROM USER_USERS;
      RETURN AUX;
    ELSE
      RETURN 'PKG_FORMULAS_COSEC v'||VERSAO||'('||TO_CHAR(DATA_VERSAO,'YYMMDDHH24MI')||')';
    END IF;
  END GET_PACKINFO;
/*
-* NOME      : GET_CONTABILIDADE
-* OBJECTIVO : RETORNA SE UMA DETERMINADA COMPANHIA TEM CONTAS TECNICAS PARA APRESENTAR
-* UTILIZACAO:
-* AUTOR     : JOSE VIEGAS
-* DATA      : 01-08-2006
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*/
FUNCTION GET_CONTABILIDADE (PI_CDCIA IN VARCHAR2
               ,PI_ANO IN VARCHAR2
               ,PI_TRIMESTRE IN VARCHAR2
                           ,PI_MODALI IN VARCHAR2 ) RETURN NUMBER IS
  AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
  AUX_MES   MPRELIQR.CDAGRUPA%TYPE;
BEGIN
  SELECT
    NVL(SUM(NVL(LIQUIDACAO.PTIMPORT,0)),0)
  INTO
    AUX_VALOR
  FROM
    MPRELIQR LIQUIDACAO
  WHERE
      1=1
  AND LIQUIDACAO.CDCONLIQ IN (921,800)
  AND TRUNC((TO_CHAR(LIQUIDACAO.FEPRELIQ,'MM')+2)/3) = PI_TRIMESTRE
  AND TO_CHAR(LIQUIDACAO.FEPRELIQ,'YYYY') = PI_ANO
  AND LIQUIDACAO.CDCIA  =PI_CDCIA ;
  IF AUX_VALOR= 0 THEN
    AUX_MES:=LTRIM(TO_CHAR(PI_TRIMESTRE*3,'00'));
    SELECT
      NVL(SUM(NVL(LIQUIDACAO.PTIMPORT,0)) ,0)
    INTO
      AUX_VALOR
    FROM
      MPRELIQR LIQUIDACAO
    WHERE
        1=1
    AND LIQUIDACAO.CDCONLIQ = 201
    AND TRUNC(LIQUIDACAO.FEPRELIQ)=LAST_DAY(TO_DATE('01-'||AUX_MES||'-'||PI_ANO,'DD-MM-YYYY'))
    AND LIQUIDACAO.MODALI =PI_MODALI
    AND LIQUIDACAO.CDCIA  =PI_CDCIA ;
  END IF;
  RETURN AUX_VALOR;
EXCEPTION
 WHEN OTHERS THEN RETURN 0;
END GET_CONTABILIDADE;
/*
-* NOME      : GET_SHARE_TRATADO
-* OBJECTIVO : RETORNA A PERCENTAGEM DE PARTICIPAC?O DA COMPANHIA NO TRATADO DE QUOTA-PARTE
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 11-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_SHARE_TRATADO    ( PI_MODALI   IN NUMBER
                    ,PI_CDAGRUPA IN VARCHAR2
                          ,PI_CDCIA    IN VARCHAR2
                ) RETURN NUMBER IS
AUX_PERC  TCONTCIA.PORCPART%TYPE;
AUX_CDPLAN TCONTCIA.CDPLAN%TYPE;
AUX_CDCONTRE TCONTCIA.CDCONTRE%TYPE;
BEGIN
     IF(PI_CDAGRUPA='QPCAUC?O') THEN
        AUX_CDPLAN:='PCA1';
        AUX_CDCONTRE:='QPCAUCAO';
     ELSE
        AUX_CDPLAN:='PCR1';
        AUX_CDCONTRE:='QPCRECOM';
      END IF;
     SELECT PORCPART INTO AUX_PERC
     FROM
     TCONTCIA
     WHERE
     1=1
     AND CDCIA=PI_CDCIA
     AND CDTRASPA=0
     AND CDPLAN=AUX_CDPLAN
     AND CDCONTRE=AUX_CDCONTRE
     AND CDPERPLA=PI_MODALI-1976;
     RETURN AUX_PERC;
EXCEPTION
 WHEN  NO_DATA_FOUND THEN RETURN 0;
 WHEN OTHERS THEN RETURN NULL;
END GET_SHARE_TRATADO;
/*
-* NOME      : GET_BALANCO_PERIODO
-* OBJECTIVO : RETORNA O VALOR DO BALANCO PARA O PERIODO, RESSEGURADORA E TRATADO ESCOLHIDO
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 11-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_BALANCO_PERIODO (PI_CDCIA IN VARCHAR2
                  ,PI_TRATADO IN VARCHAR2
                  ,PI_ANO IN VARCHAR2
                  ,PI_TRIMESTRE IN VARCHAR2) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
AUX_PCOMMISSION MPRELIQR.PTIMPORT%TYPE;
AUX_ACOMMISSION MPRELIQR.PTIMPORT%TYPE;
AUX_ANOS MPRELIQR.MODALI%TYPE;
AUX_C NUMBER;
BEGIN

    SELECT COUNT(*) INTO AUX_C
    FROM
    MPRELIQR LIQUIDACAO
    ,GD_CONTABILIDADE_RESSEGURO SINAL
    WHERE
    1=1
        AND SINAL.GENERO_CONTABILIDADE_ID='CONTABILIDADE TECNICA'
    AND SINAL.CDCONLIQ=LIQUIDACAO.CDCONLIQ
--    AND LIQUIDACAO.CDCONLIQ IN (100,103,151,152,204,301,206,304,351,401,126,308,311)
    AND LIQUIDACAO.CDCONLIQ IN (100,103,151,152,204,301,206,304,351,401)
    AND TRUNC((TO_CHAR(LIQUIDACAO.FEPRELIQ,'MM')+2)/3) = PI_TRIMESTRE
    AND TO_CHAR(LIQUIDACAO.FEPRELIQ,'YYYY') = PI_ANO
    AND LIQUIDACAO.CDCIA  =PI_CDCIA
    AND LIQUIDACAO.CDAGRUPA  =PI_TRATADO;

--DBMS_OUTPUT.PUT_LINE('TRIMESTRE:'||PI_TRIMESTRE);
--DBMS_OUTPUT.PUT_LINE('ANO:'||PI_ANO);
--DBMS_OUTPUT.PUT_LINE('CDCIA:'||PI_CDCIA);
--DBMS_OUTPUT.PUT_LINE('TRATADO:'||PI_TRATADO);

    IF AUX_C >0 THEN

    SELECT SUM(NVL(LIQUIDACAO.PTIMPORT*SINAL.SINAL,0))
    INTO AUX_VALOR
    FROM
    MPRELIQR LIQUIDACAO
    ,GD_CONTABILIDADE_RESSEGURO SINAL
    WHERE
    1=1
        AND SINAL.GENERO_CONTABILIDADE_ID='CONTABILIDADE TECNICA'
    AND SINAL.CDCONLIQ=LIQUIDACAO.CDCONLIQ
--    AND LIQUIDACAO.CDCONLIQ IN (100,103,151,152,204,301,206,304,351,401,126,308,311)
    AND LIQUIDACAO.CDCONLIQ IN (100,103,151,152,204,301,206,304,351,401)
    AND TRUNC((TO_CHAR(LIQUIDACAO.FEPRELIQ,'MM')+2)/3) = PI_TRIMESTRE
    AND TO_CHAR(LIQUIDACAO.FEPRELIQ,'YYYY') = PI_ANO
    AND LIQUIDACAO.CDCIA  =PI_CDCIA
    AND LIQUIDACAO.CDAGRUPA  =PI_TRATADO;

    ELSE

    AUX_VALOR:=0;

    END IF;


    AUX_ANOS:=2004;
    AUX_PCOMMISSION:=0;
    AUX_ACOMMISSION:=0;
    IF PI_TRIMESTRE=4 THEN
    WHILE AUX_ANOS<=PI_ANO-2 LOOP
     /**** SALDO AJUSTE COMISS?O ***/
      AUX_ACOMMISSION:=AUX_ACOMMISSION+(-1*( NVL (PKG_RESSEGURO_COSEC.GET_AJUSTE_COMISSAO (PI_CDCIA,PI_TRATADO,PI_ANO,AUX_ANOS),0)-NVL (    PKG_RESSEGURO_COSEC.GET_AJUSTE_COMISSAO (PI_CDCIA,PI_TRATADO,TO_CHAR(PI_ANO-1),AUX_ANOS),0)));

     /**** SALDO P/L COMISS?O  ****/
     --AUX_PCOMMISSION:=AUX_PCOMMISSION+(-1*( NVL(PKG_RESSEGURO_COSEC.GET_PART_ANO_TRAT(PI_CDCIA,PI_ANO,AUX_ANOS,PI_TRATADO),0)-NVL(PKG_RESSEGURO_COSEC.GET_PART_ANO_TRAT(PI_CDCIA,PI_ANO-1,AUX_ANOS,PI_TRATADO),0)));
     AUX_PCOMMISSION:=AUX_PCOMMISSION+(-1*( NVL(PKG_RESSEGURO_COSEC.GET_PART_ANO_TRAT_388(PI_CDCIA,PI_ANO,AUX_ANOS,PI_TRATADO),0)));
     AUX_ANOS:=AUX_ANOS+1;
    END LOOP;
    END IF;
    RETURN AUX_VALOR+AUX_PCOMMISSION+AUX_ACOMMISSION;


EXCEPTION
        WHEN OTHERS THEN RETURN NULL;
END GET_BALANCO_PERIODO;
/*
-* NOME      : GET_BALANCODIR_PERIODO
-* OBJECTIVO : RETORNA O VALOR DO BALANCO PARA O PERIODO, RESSEGURADORA E TRATADO ESCOLHIDO
-*        CDCONLIQ=921
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 14-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_BALANCODIR_PERIODO (PI_CDCIA IN VARCHAR2
                  ,PI_TRATADO IN VARCHAR2
                  ,PI_ANO IN VARCHAR2
                  ,PI_TRIMESTRE IN VARCHAR2) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
BEGIN
    SELECT SUM(LIQUIDACAO.PTIMPORT) INTO AUX_VALOR
    FROM
    MPRELIQR LIQUIDACAO
    WHERE
    1=1
    AND LIQUIDACAO.CDCONLIQ=921
    AND TRUNC((TO_CHAR(LIQUIDACAO.FEPRELIQ,'MM')+2)/3) = PI_TRIMESTRE
    AND TO_CHAR(LIQUIDACAO.FEPRELIQ,'YYYY') = PI_ANO
    AND LIQUIDACAO.CDCIA  =PI_CDCIA
    AND LIQUIDACAO.CDAGRUPA  =PI_TRATADO;
    RETURN AUX_VALOR;
EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
END GET_BALANCODIR_PERIODO;
/*
-* NOME      : GET_SALDOFIN_ANTERIOR
-* OBJECTIVO : RETORNA O SALDO FINANCEIRO PARA UMA DETERMINADA RESEGURADORA NUM DETERMINADO PERIODO
-*        CDCONLIQ=922
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 14-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*   15-03-2005 BRIGIDA RAMOS    sUBSTITUIC?O DE MPRELIQR POR MCTASTEC
-*/
FUNCTION GET_SALDOFIN_ANTERIOR (PI_CDCIA IN VARCHAR2
                  ,PI_ANO IN VARCHAR2
                  ,PI_TRIMESTRE IN VARCHAR2) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
AUX_ANO NUMBER;
AUX_TRIMESTRE NUMBER;
BEGIN
    IF (PI_TRIMESTRE=1) THEN
        AUX_ANO:=PI_ANO-1;
        AUX_TRIMESTRE:=4;
    ELSE
        AUX_ANO:=PI_ANO;
        AUX_TRIMESTRE:=PI_TRIMESTRE-1;
    END IF;
    SELECT
          NVL(DECODE(LIQUIDACAO.SALDODEB,0,LIQUIDACAO.SALDOHAB,LIQUIDACAO.SALDODEB*-1),0) INTO AUX_VALOR
    FROM
    MCTASTEC LIQUIDACAO
    WHERE
    1=1
    AND LIQUIDACAO.CDCONLIQ=922
    AND TRUNC((TO_CHAR(LIQUIDACAO.FECIERRE,'MM')+2)/3) = AUX_TRIMESTRE
    AND TO_CHAR(LIQUIDACAO.FECIERRE,'YYYY') = AUX_ANO
    AND LIQUIDACAO.CDCIA  =PI_CDCIA ;
    RETURN AUX_VALOR;
EXCEPTION
 WHEN OTHERS THEN RETURN 0;
END GET_SALDOFIN_ANTERIOR;
/*
-* NOME      : GET_SALDOFIN_ACTUAL
-* OBJECTIVO : RETORNA O SALDO FINANCEIRO PARA UMA DETERMINADA RESEGURADORA NUM DETERMINADO PERIODO
-*        CDCONLIQ=922
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 22-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*   15-03-2005 BRIGIDA RAMOS    sUBSTITUIC?O DE MPRELIQR POR MCTASTEC
-*/
FUNCTION GET_SALDOFIN_ACTUAL (PI_CDCIA IN VARCHAR2
                  ,PI_ANO IN VARCHAR2
                  ,PI_TRIMESTRE IN VARCHAR2) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
BEGIN
    SELECT
          NVL(DECODE(LIQUIDACAO.SALDODEB,0,LIQUIDACAO.SALDOHAB,LIQUIDACAO.SALDODEB*-1),0) INTO AUX_VALOR
    FROM
    MCTASTEC LIQUIDACAO
    WHERE
    1=1
    AND LIQUIDACAO.CDCONLIQ=922
    AND TRUNC((TO_CHAR(LIQUIDACAO.FECIERRE,'MM')+2)/3) = PI_TRIMESTRE
    AND TO_CHAR(LIQUIDACAO.FECIERRE,'YYYY') = PI_ANO
    AND LIQUIDACAO.CDCIA  =PI_CDCIA ;
    RETURN AUX_VALOR;
EXCEPTION
 WHEN OTHERS THEN RETURN 0;
END GET_SALDOFIN_ACTUAL;
/*
-* NOME      : GET_SALDOTEC_CAUCAO
-* OBJECTIVO : RETORNA O SALDO TECNICO  PARA UM DETERMINADO PERIODO
-*        CDCONLIQ=921 E CDAGRUPA=QPCAUC?O
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 22-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_SALDOTEC_CAUCAO (PI_CDCIA IN VARCHAR2
                  ,PI_ANO IN VARCHAR2
                  ,PI_TRIMESTRE IN VARCHAR2) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
BEGIN
    SELECT
          NVL(SUM(NVL(LIQUIDACAO.PTIMPORT,0)),0) INTO AUX_VALOR
    FROM
    MPRELIQR LIQUIDACAO
    WHERE
    1=1
    AND LIQUIDACAO.CDCONLIQ=921
    AND LIQUIDACAO.CDAGRUPA='QPCAUC?O'
    AND TRUNC((TO_CHAR(LIQUIDACAO.FEPRELIQ,'MM')+2)/3) = PI_TRIMESTRE
    AND TO_CHAR(LIQUIDACAO.FEPRELIQ,'YYYY') = PI_ANO
    AND LIQUIDACAO.CDCIA  =PI_CDCIA ;
    RETURN AUX_VALOR;
EXCEPTION
 WHEN OTHERS THEN RETURN NULL;
END GET_SALDOTEC_CAUCAO;
/*
-* NOME      : GET_SALDOTEC_CREDITO
-* OBJECTIVO : RETORNA O SALDO TECNICO  PARA UM DETERMINADO PERIODO
-*        CDCONLIQ=921 E CDAGRUPA=QPCREDTO
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 22-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_SALDOTEC_CREDITO (PI_CDCIA IN VARCHAR2
                  ,PI_ANO IN VARCHAR2
                  ,PI_TRIMESTRE IN VARCHAR2) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
BEGIN
    SELECT
          NVL(SUM(NVL(LIQUIDACAO.PTIMPORT,0)),0) INTO AUX_VALOR
    FROM
    MPRELIQR LIQUIDACAO
    WHERE
    1=1
    AND LIQUIDACAO.CDCONLIQ=921
    AND LIQUIDACAO.CDAGRUPA='QPCREDTO'
    AND TRUNC((TO_CHAR(LIQUIDACAO.FEPRELIQ,'MM')+2)/3) = PI_TRIMESTRE
    AND TO_CHAR(LIQUIDACAO.FEPRELIQ,'YYYY') = PI_ANO
    AND LIQUIDACAO.CDCIA  =PI_CDCIA ;
    RETURN AUX_VALOR;
EXCEPTION
 WHEN OTHERS THEN RETURN NULL;
END GET_SALDOTEC_CREDITO;
/*
-* NOME      : GET_SALDOTEC_FACULTATIVO
-* OBJECTIVO : RETORNA O SALDO TECNICO  PARA UM DETERMINADO PERIODO
-*        CDCONLIQ=921 E CDAGRUPA=FAC./OL.
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 22-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_SALDOTEC_FACULTATIVO (PI_CDCIA IN VARCHAR2
                  ,PI_ANO IN VARCHAR2
                  ,PI_TRIMESTRE IN VARCHAR2) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
BEGIN
    SELECT
          NVL(SUM(NVL(LIQUIDACAO.PTIMPORT,0)),0) INTO AUX_VALOR
    FROM
    MPRELIQR LIQUIDACAO
    WHERE
    1=1
    AND LIQUIDACAO.CDCONLIQ=921
    AND LIQUIDACAO.CDAGRUPA='FAC./OL.'
    AND TRUNC((TO_CHAR(LIQUIDACAO.FEPRELIQ,'MM')+2)/3) = PI_TRIMESTRE
    AND TO_CHAR(LIQUIDACAO.FEPRELIQ,'YYYY') = PI_ANO
    AND LIQUIDACAO.CDCIA  =PI_CDCIA ;
    RETURN AUX_VALOR;
EXCEPTION
 WHEN OTHERS THEN RETURN NULL;
END GET_SALDOTEC_FACULTATIVO;
/*
-* NOME      : GET_SALDO_PAGAMENTOS
-* OBJECTIVO : RETORNA O VALOR DOS PAGAMENTOS  PARA UM DETERMINADO PERIODO
-*        CDCONLIQ=800
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 22-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_SALDO_PAGAMENTOS (PI_CDCIA IN VARCHAR2
                  ,PI_ANO IN VARCHAR2
                  ,PI_TRIMESTRE IN VARCHAR2) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
BEGIN
    SELECT
          NVL(SUM(NVL(LIQUIDACAO.PTIMPORT,0)),0) INTO AUX_VALOR
    FROM
    MPRELIQR LIQUIDACAO
    WHERE
    1=1
    AND LIQUIDACAO.CDCONLIQ=800
    AND TRUNC((TO_CHAR(LIQUIDACAO.FEPRELIQ,'MM')+2)/3) = PI_TRIMESTRE
    AND TO_CHAR(LIQUIDACAO.FEPRELIQ,'YYYY') = PI_ANO
    AND LIQUIDACAO.CDCIA  =PI_CDCIA ;
    RETURN AUX_VALOR;
EXCEPTION
 WHEN OTHERS THEN RETURN NULL;
END GET_SALDO_PAGAMENTOS;
/*
-* NOME      : GET_SALDO_BALANCO
-* OBJECTIVO : RETORNA O VALOR DO BALANCO
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 22-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_SALDO_BALANCO    (PI_CDCIA IN VARCHAR2
                  ,PI_ANO IN VARCHAR2
                  ,PI_TRIMESTRE IN VARCHAR2) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
BEGIN
    SELECT
         NVL(GET_SALDOFIN_ANTERIOR(PI_CDCIA,PI_ANO,PI_TRIMESTRE),0)+ NVL(GET_SALDOTEC_FACULTATIVO(PI_CDCIA,PI_ANO,PI_TRIMESTRE),0)+
     NVL(GET_SALDOTEC_CREDITO(PI_CDCIA,PI_ANO,PI_TRIMESTRE),0)+NVL(GET_SALDOTEC_CAUCAO(PI_CDCIA,PI_ANO,PI_TRIMESTRE),0) INTO AUX_VALOR
    FROM
    DUAL;
    RETURN AUX_VALOR;
EXCEPTION
 WHEN OTHERS THEN RETURN NULL;
END GET_SALDO_BALANCO;
/*
-* NOME      : GET_IBNR_RESERVES_PERIODO
-* OBJECTIVO : RETORNA O VALOR DOS CONCEITOS 202 + 201 PARA UM DETERMINADO PERIODO
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 15-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_IBNR_RESERVES_PERIODO (PI_CDCIA IN VARCHAR2
                  ,PI_TRATADO IN VARCHAR2
                  ,PI_ANO IN VARCHAR2
                  ,PI_TRIMESTRE IN VARCHAR2
                  ,PI_CDRAMO IN VARCHAR2) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
AUX_MES   MPRELIQR.CDAGRUPA%TYPE;
BEGIN
    AUX_MES:=PI_TRIMESTRE*3;
    IF AUX_MES<10 THEN
        AUX_MES:='0'||AUX_MES;
    ELSE
        AUX_MES:=AUX_MES;
    END IF;
    SELECT SUM(NVL(LIQUIDACAO.PTIMPORT,0)) INTO AUX_VALOR
    FROM
    MPRELIQR LIQUIDACAO
    WHERE
    1=1
    AND LIQUIDACAO.CDCONLIQ IN (201,202)
    AND LIQUIDACAO.CDRAMO LIKE PI_CDRAMO||'%'
    AND TRUNC(LIQUIDACAO.FEPRELIQ)=LAST_DAY(TO_DATE('01-'||AUX_MES||'-'||PI_ANO,'DD-MM-YYYY'))
    AND LIQUIDACAO.CDCIA  =PI_CDCIA
    AND LIQUIDACAO.CDAGRUPA  =PI_TRATADO;
    RETURN AUX_VALOR;
EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
END GET_IBNR_RESERVES_PERIODO;
/*
-* NOME      : GET_IBNR_RESERVES
-* OBJECTIVO : RETORNA O VALOR DOS CONCEITOS 202 + 201 PARA UM DETERMINADO PERIODO
-* UTILIZACAO: R6.C1
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 15-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_IBNR_RESERVES (PI_CDCIA IN VARCHAR2
                  ,PI_TRATADO IN VARCHAR2
                  ,PI_ANO IN VARCHAR2
                  ,PI_TRIMESTRE IN VARCHAR2) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
AUX_MES   MPRELIQR.CDAGRUPA%TYPE;
BEGIN
    AUX_MES:=PI_TRIMESTRE*3;
    IF AUX_MES<10 THEN
        AUX_MES:='0'||AUX_MES;
    ELSE
        AUX_MES:=AUX_MES;
    END IF;
    SELECT SUM(NVL(LIQUIDACAO.PTIMPORT,0)) INTO AUX_VALOR
    FROM
    MPRELIQR LIQUIDACAO
    WHERE
    1=1
    AND LIQUIDACAO.CDCONLIQ IN (201,202)
    AND TRUNC(LIQUIDACAO.FEPRELIQ)=LAST_DAY(TO_DATE('01-'||AUX_MES||'-'||PI_ANO,'DD-MM-YYYY'))
    AND LIQUIDACAO.CDCIA  =PI_CDCIA
    AND LIQUIDACAO.CDAGRUPA  =PI_TRATADO;
    RETURN AUX_VALOR;
EXCEPTION
    WHEN OTHERS THEN RETURN 0;
END GET_IBNR_RESERVES;
/*
-* NOME      : GET_PERC_COMISSAO_RESSEG
-* OBJECTIVO : RETORNA A PERCENTAGEM DE COMISSAO DE RESSEGURO
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 17-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PERC_COMISSAO_RESSEG (PI_CDCIA IN VARCHAR2
                ,PI_CDCONTRE IN VARCHAR2
                ,PI_NMCESRAM IN NUMBER
                ,PI_DTEMISSAO IN DATE
                ,PI_NMPOLIZA IN NUMBER
                ,PI_ESTADO  IN VARCHAR2
                ,PI_CDRAMO IN NUMBER
                ,PI_CDUNIECO IN NUMBER
                ) RETURN NUMBER IS
AUX_PERCENTAGEM CO_CNTCI.PORCOMIS%TYPE;
BEGIN
    IF (PI_CDCONTRE LIKE 'OL%') THEN
        SELECT
           PCOMISSAO.PORCOMIS INTO AUX_PERCENTAGEM
        FROM
         CO_ENOPOL ENOPOL
        ,CO_CNTCI PCOMISSAO
        WHERE
        1=1
        AND PCOMISSAO.CDBOUQUE=ENOPOL.CDBOUQUE
        AND PCOMISSAO.CDCIA=PI_CDCIA
        --AND PI_DTEMISSAO BETWEEN ENOPOL.FEINICIO AND NVL(ENOPOL.FEFINAL,SYSDATE)
        AND ENOPOL.NMPOLIZA=PI_NMPOLIZA
        AND ENOPOL.ESTADO=PI_ESTADO
        AND ENOPOL.CDRAMO=PI_CDRAMO
        AND ENOPOL.CDUNIECO=PI_CDUNIECO
        AND ENOPOL.CDCONTRE=PI_CDCONTRE;
    ELSE
        SELECT TO_NUMBER(OTVALOR) INTO AUX_PERCENTAGEM
        FROM
         TVALOFAP
        WHERE
        1=1
        AND NMCESRAM=PI_NMCESRAM
        AND CDCIA=PI_CDCIA;
    END IF;
    RETURN AUX_PERCENTAGEM;
EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
END GET_PERC_COMISSAO_RESSEG;
/*
-* NOME      : GET_ANOS_EXERCICIO
-* OBJECTIVO : RETORNA OS ANOS DE EXERCICIO A CONSIDERAR
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 24-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_ANOS_EXERCICIO   (PI_ANO_EXERCICIO IN NUMBER
                  ,PI_ANO_OCORRENCIA IN NUMBER
                      ,PI_ANO_CORRENTE IN NUMBER
                  ) RETURN VARCHAR2 IS
BEGIN
    IF (PI_ANO_EXERCICIO-PI_ANO_OCORRENCIA+1>=3) THEN
        IF (PI_ANO_CORRENTE BETWEEN (PI_ANO_EXERCICIO-3) AND PI_ANO_EXERCICIO) THEN
        RETURN 'S';
        ELSE
        RETURN 'N';
        END IF;
    /*ELSE
        IF (PI_ANO_EXERCICIO-PI_ANO_OCORRENCIA+1>3) THEN
        IF (PI_ANO_CORRENTE=PI_ANO_EXERCICIO) THEN
           RETURN 'S';
        ELSE
           RETURN 'N';
        END IF;
        ELSE
            RETURN NULL;
        END IF;*/
    ELSE
        RETURN 'N';
    END IF;
END GET_ANOS_EXERCICIO;
/*
-* NOME      : GET_COMISSAO_DEFINITIVA
-* OBJECTIVO : RETORNA A PERCENTAGEM DA COMISSAO DEFINITIVA
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 25-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_COMISSAO_DEFINITIVA (PI_CDAGRUPA IN VARCHAR2
                  ,PI_MODALI IN VARCHAR2
                  ,PI_LRATIO IN NUMBER
                  ) RETURN NUMBER IS
AUX_VALOR TTAPVAAT.OTVALOR01%TYPE;
BEGIN
    SELECT COMISSAO.OTVALOR01 INTO AUX_VALOR
    FROM
        TTAPTABL TABELA
        ,TTAPVAAT COMISSAO
    WHERE
    1=1
    AND COMISSAO.OTCLAVE3 = ( SELECT MIN(X.OTCLAVE3)
                  FROM TTAPVAAT X
                  WHERE
                  1=1
                  AND TO_NUMBER(REPLACE(X.OTCLAVE3,'.',',')) > PI_LRATIO
                  AND X.OTCLAVE2=COMISSAO.OTCLAVE2
                  AND X.OTCLAVE1=COMISSAO.OTCLAVE1
                  AND X.NMTABLA=COMISSAO.NMTABLA
                 )
    AND COMISSAO.OTCLAVE2=PI_MODALI
    AND COMISSAO.OTCLAVE1=PI_CDAGRUPA
    AND COMISSAO.NMTABLA=TABELA.NMTABLA
    AND TABELA.CDTABLA='CO_COMIS';
    RETURN TO_NUMBER(REPLACE(AUX_VALOR,'.',','));
    EXCEPTION
    WHEN OTHERS THEN
    RETURN 0;
END GET_COMISSAO_DEFINITIVA;
/*
-* NOME      : GET_LOSS_RATIO
-* OBJECTIVO : RETORNA O LOSS RATIO
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 25-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_LOSS_RATIO (  PI_CDCIA    IN NUMBER
              ,PI_CDAGRUPA IN VARCHAR2
              ,PI_MODALI IN VARCHAR2
              ,PI_EXERCICIO IN NUMBER
              ) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
BEGIN
    SELECT SUM(NVL(PTIMPORT,0)) INTO AUX_VALOR
    FROM
    MPRELIQR
    WHERE
    1=1
    AND CDCONLIQ=124
    AND TO_CHAR(FEPRELIQ,'YYYY')=PI_EXERCICIO
    AND MODALI=PI_MODALI
    AND CDAGRUPA=PI_CDAGRUPA
    AND CDCIA=PI_CDCIA;
    RETURN AUX_VALOR;
EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
END GET_LOSS_RATIO;
/*
-* NOME      : GET_PRCT_DESP_GERAIS
-* OBJECTIVO : RETORNA O VALOR DA PERCENTAGEM DE TRATADO PARA DESPESAS GERAIS
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 28-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PRCT_DESP_GERAIS(  PI_MODALI    IN NUMBER
                ,PI_CDAGRUPA IN VARCHAR2
              ) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
BEGIN
    SELECT TO_NUMBER(REPLACE(PRCT.OTVALOR01,'.',',')) INTO AUX_VALOR
    FROM
    TTAPTABL TABELA
    ,TTAPVAAT PRCT
    WHERE
    1=1
    AND PRCT.OTCLAVE1=PI_CDAGRUPA
    AND PRCT.OTCLAVE2=PI_MODALI
    AND PRCT.NMTABLA=TABELA.NMTABLA
    AND TABELA.CDTABLA='DESPGREA';
    RETURN AUX_VALOR;
EXCEPTION
    WHEN OTHERS THEN RETURN 0;
END GET_PRCT_DESP_GERAIS;
/*
-* NOME      : GET_TRIMESTRE
-* OBJECTIVO : RETORNA O TRIMESTRE A QUE PERTENCE UMA DETERMINADA DATA
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 28-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_TRIMESTRE (PI_DATA IN DATE) RETURN NUMBER IS
AUX_TRIMESTRE NUMBER;
BEGIN
    SELECT TRUNC((TO_CHAR(PI_DATA,'MM')+2)/3)  INTO AUX_TRIMESTRE FROM DUAL;
    RETURN AUX_TRIMESTRE;
END GET_TRIMESTRE;
/*
-* NOME      : GET_PRCT_PART_RESULT
-* OBJECTIVO : RETORNA O VALOR DA PERCENTAGEM DE PARTICIPACAO DE RESULTADOS
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 08-03-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PRCT_PART_RESULT(  PI_MODALI    IN NUMBER
                ,PI_CDAGRUPA IN VARCHAR2
                      ) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
BEGIN
    SELECT TO_NUMBER(REPLACE(PRCT.OTVALOR01,'.',',')) INTO AUX_VALOR
    FROM
    TTAPTABL TABELA
    ,TTAPVAAT PRCT
    WHERE
    1=1
    AND PRCT.OTCLAVE1=PI_CDAGRUPA
    AND PRCT.OTCLAVE2=PI_MODALI
    AND PRCT.NMTABLA=TABELA.NMTABLA
    AND TABELA.CDTABLA='PARTBENE';
    RETURN AUX_VALOR;
EXCEPTION
    WHEN OTHERS THEN RETURN 0;
END GET_PRCT_PART_RESULT;
/*
-* NOME      : GET_IBNR
-* OBJECTIVO : RETORNA O VALOR DOS CONCEITOS 202  PARA UM DETERMINADO PERIODO
-* UTILIZACAO: R6.C5
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 15-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_IBNR (PI_CDCIA IN VARCHAR2
                  ,PI_ANO IN VARCHAR2
                  ,PI_TRIMESTRE IN VARCHAR2
                              ,PI_MODALI IN VARCHAR2) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
AUX_MES   MPRELIQR.CDAGRUPA%TYPE;
BEGIN
    AUX_MES:=PI_TRIMESTRE*3;
    IF AUX_MES<10 THEN
        AUX_MES:='0'||AUX_MES;
    ELSE
        AUX_MES:=AUX_MES;
    END IF;
    SELECT SUM(NVL(LIQUIDACAO.PTIMPORT,0)) INTO AUX_VALOR
    FROM
    MPRELIQR LIQUIDACAO
    WHERE
    1=1
    AND LIQUIDACAO.CDCONLIQ IN (202)
    AND TRUNC(LIQUIDACAO.FEPRELIQ)=LAST_DAY(TO_DATE('01-'||AUX_MES||'-'||PI_ANO,'DD-MM-YYYY'))
        AND LIQUIDACAO.MODALI=PI_MODALI
    AND LIQUIDACAO.CDCIA  =PI_CDCIA ;
    RETURN AUX_VALOR;
EXCEPTION
    WHEN OTHERS THEN RETURN 0;
END GET_IBNR;
/*
-* NOME      : GET_PROVISAO
-* OBJECTIVO : RETORNA O VALOR DOS CONCEITOS 201 PARA UM DETERMINADO PERIODO
-* UTILIZACAO: R6.C5
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 15-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*   01-08-2006    JOSE VIEGAS      SIMPLIFICAC?O DA OBTENC?O AUX_MES
-*   03-01-2007   JOSE VIEGAS   RESTRIC?O DO FACULTATIVO
-*/
FUNCTION GET_PROVISAO (PI_CDCIA IN VARCHAR2
                  ,PI_ANO IN VARCHAR2
                  ,PI_TRIMESTRE IN VARCHAR2
                              ,PI_MODALI IN VARCHAR2 ) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
AUX_MES   MPRELIQR.CDAGRUPA%TYPE;
BEGIN
    AUX_MES:=LTRIM(TO_CHAR(PI_TRIMESTRE*3,'00'));
    SELECT SUM(LIQUIDACAO.PTIMPORT) INTO AUX_VALOR
    FROM
    MPRELIQR LIQUIDACAO
    WHERE
    1=1
    AND LIQUIDACAO.CDCONLIQ = 201
      AND DECODE(LIQUIDACAO.CDAGRUPA,'FAC./OL.','N','S')='S'  /* 03-01-2007 */
    AND TRUNC(LIQUIDACAO.FEPRELIQ)=LAST_DAY(TO_DATE('01-'||AUX_MES||'-'||PI_ANO,'DD-MM-YYYY'))
        AND LIQUIDACAO.MODALI=PI_MODALI
    AND LIQUIDACAO.CDCIA  =PI_CDCIA ;
    RETURN AUX_VALOR;
EXCEPTION
    WHEN OTHERS THEN RETURN 0;
END GET_PROVISAO;
/*
-* NOME      : GET_IBNR_CONCEITO
-* OBJECTIVO : RETORNA O VALOR DOS CONCEITOS 202  PARA UM DETERMINADO PERIODO
-* UTILIZACAO: R6.C4
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 15-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_IBNR_CONCEITO (PI_CDCIA IN VARCHAR2
                ,PI_CDAGRUPA IN VARCHAR2
                  ,PI_ANO IN VARCHAR2
                  ,PI_TRIMESTRE IN VARCHAR2
                              ,PI_MODALI IN VARCHAR2) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
AUX_MES   MPRELIQR.CDAGRUPA%TYPE;
BEGIN
    AUX_MES:=PI_TRIMESTRE*3;
    IF AUX_MES<10 THEN
        AUX_MES:='0'||AUX_MES;
    ELSE
        AUX_MES:=AUX_MES;
    END IF;
    SELECT SUM(NVL(LIQUIDACAO.PTIMPORT,0)) INTO AUX_VALOR
    FROM
    MPRELIQR LIQUIDACAO
    WHERE
    1=1
    AND LIQUIDACAO.CDCONLIQ IN (202)
    AND TRUNC(LIQUIDACAO.FEPRELIQ)=LAST_DAY(TO_DATE('01-'||AUX_MES||'-'||PI_ANO,'DD-MM-YYYY'))
    AND LIQUIDACAO.CDAGRUPA=PI_CDAGRUPA
        AND LIQUIDACAO.MODALI=PI_MODALI
    AND LIQUIDACAO.CDCIA  =PI_CDCIA ;
    RETURN AUX_VALOR;
EXCEPTION
    WHEN OTHERS THEN RETURN 0;
END GET_IBNR_CONCEITO;
/*
-* NOME      : GET_PROVISAO_CONCEITO
-* OBJECTIVO : RETORNA O VALOR DOS CONCEITOS 201 PARA UM DETERMINADO PERIODO
-* UTILIZACAO: R6.C4
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 15-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PROVISAO_CONCEITO (PI_CDCIA IN VARCHAR2
            ,PI_CDAGRUPA IN VARCHAR2
                  ,PI_ANO IN VARCHAR2
                  ,PI_TRIMESTRE IN VARCHAR2
                              ,PI_MODALI IN VARCHAR2) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
AUX_MES   MPRELIQR.CDAGRUPA%TYPE;
BEGIN
    AUX_MES:=PI_TRIMESTRE*3;
    IF AUX_MES<10 THEN
        AUX_MES:='0'||'-'||AUX_MES;
    ELSE
        AUX_MES:=AUX_MES;
    END IF;
    SELECT SUM(LIQUIDACAO.PTIMPORT) INTO AUX_VALOR
    FROM
    MPRELIQR LIQUIDACAO
    WHERE
    1=1
    AND LIQUIDACAO.CDCONLIQ IN (201)
    AND TRUNC(LIQUIDACAO.FEPRELIQ)=LAST_DAY(TO_DATE('01-'||AUX_MES||'-'||PI_ANO,'DD-MM-YYYY'))
    AND LIQUIDACAO.CDAGRUPA=PI_CDAGRUPA
    AND LIQUIDACAO.MODALI=PI_MODALI
    AND LIQUIDACAO.CDCIA  =PI_CDCIA ;
    RETURN AUX_VALOR;
EXCEPTION
    WHEN OTHERS THEN RETURN 0;
END GET_PROVISAO_CONCEITO;
/*
-* NOME      : GET_PREMIO_RESERVE
-* OBJECTIVO : RETORNA O VALOR DOS CONCEITOS 203 PARA UM DETERMINADO PERIODO
-* UTILIZACAO: R6.C5
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 15-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PREMIO_RESERVE (PI_CDCIA IN VARCHAR2
                  ,PI_ANO IN VARCHAR2
                  ,PI_TRIMESTRE IN VARCHAR2
                              ,PI_MODALI IN VARCHAR2) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
AUX_MES   MPRELIQR.CDAGRUPA%TYPE;
BEGIN
    AUX_MES:=PI_TRIMESTRE*3;
    IF AUX_MES<10 THEN
        AUX_MES:='0'||'-'||AUX_MES;
    ELSE
        AUX_MES:=AUX_MES;
    END IF;
    SELECT SUM(LIQUIDACAO.PTIMPORT) INTO AUX_VALOR
    FROM
    MPRELIQR LIQUIDACAO
    WHERE
    1=1
    AND LIQUIDACAO.CDCONLIQ IN (203)
    AND TRUNC(LIQUIDACAO.FEPRELIQ)=LAST_DAY(TO_DATE('01-'||AUX_MES||'-'||PI_ANO,'DD-MM-YYYY'))
        AND LIQUIDACAO.MODALI=PI_MODALI
    AND LIQUIDACAO.CDCIA  =PI_CDCIA ;
    RETURN AUX_VALOR;
EXCEPTION
    WHEN OTHERS THEN RETURN 0;
END GET_PREMIO_RESERVE;

/*
-* NOME      : GET_PREMIO_RESERVE_TRAT
-* OBJECTIVO : RETORNA O VALOR DOS CONCEITOS 203 PARA UM DETERMINADO PERIODO
-* E TRATADO
-* UTILIZACAO: R6.C5
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 15-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PREMIO_RESERVE_TRAT (PI_CDCIA IN VARCHAR2
                  ,PI_TRATADO IN VARCHAR2
                  ,PI_ANO IN VARCHAR2
                  ,PI_TRIMESTRE IN VARCHAR2
                  ,PI_MODALI IN VARCHAR2
                  ) RETURN NUMBER IS
AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
AUX_MES   MPRELIQR.CDAGRUPA%TYPE;
BEGIN
    AUX_MES:=PI_TRIMESTRE*3;
    IF AUX_MES<10 THEN
        AUX_MES:='0'||'-'||AUX_MES;
    ELSE
        AUX_MES:=AUX_MES;
    END IF;
    SELECT SUM(LIQUIDACAO.PTIMPORT) INTO AUX_VALOR
    FROM
    MPRELIQR LIQUIDACAO
    WHERE
    1=1
    AND LIQUIDACAO.CDCONLIQ IN (203)
    AND TRUNC(LIQUIDACAO.FEPRELIQ)=LAST_DAY(TO_DATE('01-'||AUX_MES||'-'||PI_ANO,'DD-MM-YYYY'))
    AND LIQUIDACAO.CDAGRUPA=PI_TRATADO
    AND LIQUIDACAO.MODALI=PI_MODALI
    AND LIQUIDACAO.CDCIA  =PI_CDCIA ;
    RETURN AUX_VALOR;
EXCEPTION
    WHEN OTHERS THEN RETURN 0;
END GET_PREMIO_RESERVE_TRAT;

/*
-* NOME      : GET_TIPOCONTR_RESSEG
-* OBJECTIVO : RETORNA O TIPO DE CONTRATO DE RESSEGURO
-* UTILIZACAO:
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 11-05-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_TIPOCONTR_RESSEG ( P_CDUNIECO IN NUMBER
                                , P_CDRAMO IN NUMBER
                , P_AAAPERTU IN NUMBER
                , P_STATUS IN VARCHAR2
                , P_NMSINIES IN NUMBER
                                , P_DATA_REF IN DATE) RETURN VARCHAR2 AS
AUX_VALOR TCONTRAT.CDTICONT%TYPE;
BEGIN
SELECT
 TIPO.CDTICONT
INTO AUX_VALOR
FROM
MCONRETR RESS
,TCONTRAT TIPO
WHERE
1=1
AND RESS.CDCONTRE= TIPO.CDCONTRE
AND TRUNC(RESS.FEMOVIMI)=TRUNC(P_DATA_REF)
AND RESS.NMSINIES=P_NMSINIES
AND RESS.STATUS=P_STATUS
AND RESS.AAAPERTU=P_AAAPERTU
AND RESS.CDRAMO=P_CDRAMO
AND RESS.CDUNIECO=P_CDUNIECO
AND ROWNUM=1;
RETURN AUX_VALOR;
EXCEPTION
   WHEN OTHERS THEN RETURN NULL;
END GET_TIPOCONTR_RESSEG ;
/*
-* NOME      : GET_PART_DESPESAS
-* UTILIZACAO: R6.C5
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 15-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PART_DESPESAS (PI_CDCIA IN VARCHAR2
               ,P_ANO_EXERCICIO IN VARCHAR2
               ,P_ANO_SUBSCRICAO IN VARCHAR2) RETURN NUMBER IS
  AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
BEGIN
  SELECT
   SUM(NVL(LIQUIDACAO.PTIMPORT,0))*PKG_RESSEGURO_COSEC.GET_PRCT_DESP_GERAIS(P_ANO_SUBSCRICAO,'QPCREDTO')/100 INTO AUX_VALOR
  FROM
    MPRELIQR LIQUIDACAO
  WHERE
      1=1
  AND LIQUIDACAO.CDCONLIQ IN (120)
  AND NVL(TRUNC((TO_CHAR(LIQUIDACAO.FEPRELIQ,'MM')+2)/3),4)=4
--  AND NVL(PKG_RESSEGURO_COSEC.GET_ANOS_EXERCICIO(P_ANO_EXERCICIO,P_ANO_SUBSCRICAO,TO_CHAR(LIQUIDACAO.FEPRELIQ,'YYYY')),'S')='S'
  AND TO_CHAR(LIQUIDACAO.FEPRELIQ,'yyyy')=P_ANO_EXERCICIO
  AND LIQUIDACAO.MODALI=TO_CHAR(P_ANO_SUBSCRICAO)
  AND DECODE(LIQUIDACAO.CDAGRUPA,'FAC./OL.','N','S')='S'
  AND LIQUIDACAO.CDCIA  =PI_CDCIA ;
  RETURN AUX_VALOR;
EXCEPTION
    WHEN OTHERS THEN RETURN 0;
END GET_PART_DESPESAS;


/*
-* NOME      : GET_PART_DESPESAS_TRAT
-* UTILIZACAO: R6.C5
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 15-02-2005
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PART_DESPESAS_TRAT (PI_CDCIA IN VARCHAR2
         ,P_TRATADO IN VARCHAR2
               ,P_ANO_EXERCICIO IN VARCHAR2
               ,P_ANO_SUBSCRICAO IN VARCHAR2
               ) RETURN NUMBER IS
  AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
BEGIN
  SELECT
   SUM(NVL(LIQUIDACAO.PTIMPORT,0))*PKG_RESSEGURO_COSEC.GET_PRCT_DESP_GERAIS(P_ANO_SUBSCRICAO,P_TRATADO)/100 INTO AUX_VALOR
  FROM
    MPRELIQR LIQUIDACAO
  WHERE
      1=1
  AND LIQUIDACAO.CDCONLIQ IN (120)
  AND NVL(TRUNC((TO_CHAR(LIQUIDACAO.FEPRELIQ,'MM')+2)/3),4)=4
--  AND NVL(PKG_RESSEGURO_COSEC.GET_ANOS_EXERCICIO(P_ANO_EXERCICIO,P_ANO_SUBSCRICAO,TO_CHAR(LIQUIDACAO.FEPRELIQ,'YYYY')),'S')='S'
  AND TO_CHAR(LIQUIDACAO.FEPRELIQ,'yyyy')=P_ANO_EXERCICIO
  AND LIQUIDACAO.MODALI=TO_CHAR(P_ANO_SUBSCRICAO)
  AND LIQUIDACAO.CDAGRUPA=P_TRATADO
  AND LIQUIDACAO.CDCIA  =PI_CDCIA ;
  RETURN AUX_VALOR;
EXCEPTION
    WHEN OTHERS THEN RETURN 0;
END GET_PART_DESPESAS_TRAT;


/*
-* NOME      : GET_PART_ANO
-* UTILIZACAO: R6.C5
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 06-12-2007
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PART_ANO (PI_CDCIA IN VARCHAR2
               ,P_ANO_EXERCICIO IN VARCHAR2
               ,P_ANO_SUBSCRICAO IN VARCHAR2) RETURN NUMBER IS
  AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
BEGIN
  SELECT
   SUM(NVL(LIQUIDACAO.PTIMPORT,0)*decode(liquidacao.cdconliq,311,-1,1)) INTO AUX_VALOR
  FROM
    MPRELIQR LIQUIDACAO
  WHERE
      1=1
  AND LIQUIDACAO.CDCONLIQ IN (308,311)
  AND LIQUIDACAO.MODALI=P_ANO_SUBSCRICAO
  AND FEPRELIQ=TO_DATE('31-12-'||TO_CHAR(TO_NUMBER(P_ANO_EXERCICIO)),'DD-MM-RRRR')
  AND LIQUIDACAO.CDCIA  =PI_CDCIA ;

  RETURN AUX_VALOR;

EXCEPTION
    WHEN OTHERS THEN RETURN 0;
END GET_PART_ANO;



/*
-* NOME      : GET_PART_ANO_TRAT
-* UTILIZACAO: R6.C1
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 06-12-2007
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PART_ANO_TRAT (PI_CDCIA IN VARCHAR2
               ,P_ANO_EXERCICIO IN VARCHAR2
               ,P_ANO_SUBSCRICAO IN VARCHAR2
               ,P_TRATADO IN VARCHAR2) RETURN NUMBER IS
  AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
BEGIN
  SELECT
   SUM(NVL(LIQUIDACAO.PTIMPORT,0)*decode(liquidacao.cdconliq,311,-1,1)) INTO AUX_VALOR
  FROM
    MPRELIQR LIQUIDACAO
  WHERE
      1=1
  AND LIQUIDACAO.CDCONLIQ IN (308,311)
  AND LIQUIDACAO.MODALI=P_ANO_SUBSCRICAO
  AND FEPRELIQ=TO_DATE('31-12-'||TO_CHAR(TO_NUMBER(P_ANO_EXERCICIO)),'DD-MM-RRRR')
  AND LIQUIDACAO.CDCIA  =PI_CDCIA
  AND LIQUIDACAO.CDAGRUPA=P_TRATADO;

  RETURN AUX_VALOR;

EXCEPTION
    WHEN OTHERS THEN RETURN 0;
END GET_PART_ANO_TRAT;

/*
-* NOME      : GET_AJUSTE_COMISSAO
-* UTILIZACAO: R6.C4
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 06-12-2007
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_AJUSTE_COMISSAO (PI_CDCIA IN VARCHAR2
               ,P_CDAGRUPA IN VARCHAR2
               ,P_ANO_EXERCICIO IN VARCHAR2
               ,P_ANO_SUBSCRICAO IN VARCHAR2) RETURN NUMBER IS
  AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
BEGIN
  SELECT
   SUM(NVL(LIQUIDACAO.PTIMPORT,0)) INTO AUX_VALOR
  FROM
    MPRELIQR LIQUIDACAO
  WHERE
      1=1
  AND LIQUIDACAO.CDCONLIQ IN (126)
  AND LIQUIDACAO.MODALI=P_ANO_SUBSCRICAO
  AND LIQUIDACAO.CDAGRUPA=P_CDAGRUPA
  AND FEPRELIQ=TO_DATE('31-12-'||TO_CHAR(TO_NUMBER(P_ANO_EXERCICIO)),'DD-MM-RRRR')
  AND LIQUIDACAO.CDCIA  =PI_CDCIA ;

  RETURN AUX_VALOR;

EXCEPTION
    WHEN OTHERS THEN RETURN 0;
END GET_AJUSTE_COMISSAO;





/*
-* NOME      : GET_CEDENCIA
-* UTILIZACAO: M151
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 11-06-2007
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_CEDENCIA       (PI_CDUNIECO IN NUMBER
                             ,PI_CDRAMO IN NUMBER
                             ,PI_ESTADO IN VARCHAR2
                             ,PI_NMPOLIZA IN NUMBER
                             ) RETURN VARCHAR2 IS
AUX_CEDENCIA VARCHAR2(2);
BEGIN
    SELECT DECODE(ATRIBUTO11,1,'I',4,'I',2,'R',5,'R',3,'V',6,'V',NULL)
        INTO AUX_CEDENCIA
        FROM
    GD_ATRIBUTOS_APOLICE_MV
        WHERE
    1=1
        AND CDUNIECO=PI_CDUNIECO
        AND CDRAMO=PI_CDRAMO
        AND ESTADO=PI_ESTADO
        AND NMPOLIZA=PI_NMPOLIZA ;
RETURN AUX_CEDENCIA;
EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
END GET_CEDENCIA;

/*
-* NOME      : GET_PART_ANO_TRAT_388
-* UTILIZACAO: R6.C1
-* AUTOR     : BRIGIDA RAMOS
-* DATA      : 06-12-2007
-* VERS?O    : 1.0
-*
-* ULTIMAS ALTERAC?ES
-*
-*   DATA       AUTOR           DESCRIC?O
-*   ========== =============== =================================================
-*
-*/
FUNCTION GET_PART_ANO_TRAT_388 (PI_CDCIA IN VARCHAR2
               ,P_ANO_EXERCICIO IN VARCHAR2
               ,P_ANO_SUBSCRICAO IN VARCHAR2
               ,P_TRATADO IN VARCHAR2) RETURN NUMBER IS
  AUX_VALOR MPRELIQR.PTIMPORT%TYPE;
BEGIN
  SELECT
   SUM(NVL(LIQUIDACAO.PTIMPORT,0) )INTO AUX_VALOR
  FROM
    MPRELIQR LIQUIDACAO
  WHERE
      1=1
  AND LIQUIDACAO.CDCONLIQ IN (388)
  AND LIQUIDACAO.MODALI=P_ANO_SUBSCRICAO
  AND FEPRELIQ=TO_DATE('31-12-'||TO_CHAR(TO_NUMBER(P_ANO_EXERCICIO)),'DD-MM-RRRR')
  AND LIQUIDACAO.CDCIA  =PI_CDCIA
  AND LIQUIDACAO.CDAGRUPA=P_TRATADO;

  RETURN AUX_VALOR;

EXCEPTION
    WHEN OTHERS THEN RETURN 0;
END GET_PART_ANO_TRAT_388;

END;
