-- PKG_TESTE_FUNC (owner: SIID_TESTES)


-- ===== SPEC (PACKAGE) =====

package pkg_teste_func
as

FUNCTION FUN_TAXA_CAMBIO (PI_MOEDA_BASE     IN   VARCHAR2
                         ,PI_MODEDA_FINAL   IN   VARCHAR2 DEFAULT NULL
                         ,PI_DATA_CAMBIO    IN   DATE DEFAULT LAST_DAY(ADD_MONTHS(SYSDATE, -1))) RETURN NUMBER;

FUNCTION FUN_PROVISAO_SIN_DATA (PI_CDUNIECO IN NUMBER
                               ,PI_CDRAMO   IN NUMBER
                               ,PI_AAAPERTU IN NUMBER
                               ,PI_NMSINIES IN NUMBER
                               ,PI_DATAINI   IN DATE
                               ,PI_DATAFIM   IN DATE
                               )   RETURN NUMBER;

 FUNCTION GET_PAGAMENTO_LIQ_SIN ( P_CDUNIECO IN NUMBER
                                , P_CDRAMO IN NUMBER
    , P_AAAPERTU IN NUMBER
    , P_STATUS IN VARCHAR2
    , P_NMSINIES IN NUMBER
                                , P_DATA_REF IN DATE) RETURN NUMBER;

 PRAGMA RESTRICT_REFERENCES (GET_PAGAMENTO_LIQ_SIN,WNDS);
 PRAGMA RESTRICT_REFERENCES (FUN_PROVISAO_SIN_DATA,WNDS);
 PRAGMA RESTRICT_REFERENCES (FUN_TAXA_CAMBIO,WNDS);

end pkg_teste_func;


-- ===== BODY (PACKAGE BODY) =====

package body pkg_teste_func
as

FUNCTION FUN_TAXA_CAMBIO (PI_MOEDA_BASE     IN   VARCHAR2
                         ,PI_MODEDA_FINAL   IN   VARCHAR2 DEFAULT NULL
                         ,PI_DATA_CAMBIO    IN   DATE DEFAULT LAST_DAY(ADD_MONTHS(SYSDATE, -1))) RETURN NUMBER
IS
  V_TAXA_CAMBIO    TCAMBIOS.PTCAMBIO%TYPE;
  N_CAMBIO  NUMBER;
BEGIN

  SELECT
    /*+ INDEX(CAMBIO SYS_C008845) */
 PTCAMBIO
  INTO   V_TAXA_CAMBIO
  FROM   TCAMBIOS CAMBIO
  WHERE  CAMBIO.CDMONBAS = PI_MOEDA_BASE
  AND    CAMBIO.CDMONEDA = (SELECT NVL(PI_MODEDA_FINAL, CDEURO) FROM TKRNLPAR)
  AND    CAMBIO.FEVALOR = (
           SELECT MAX(X.FEVALOR)
           FROM   TCAMBIOS X
           WHERE  X.FEVALOR <= PI_DATA_CAMBIO
           AND    X.CDMONBAS = CAMBIO.CDMONBAS
           AND    X.CDMONEDA  = CAMBIO.CDMONEDA);

  RETURN V_TAXA_CAMBIO;

EXCEPTION
  WHEN OTHERS THEN
    IF (PI_MOEDA_BASE=NVL(PI_MODEDA_FINAL,'EUR')) THEN
     RETURN 1;
    ELSE
   RETURN NULL;
    END IF;
END FUN_TAXA_CAMBIO;


FUNCTION FUN_PROVISAO_SIN_DATA (PI_CDUNIECO IN NUMBER
                               ,PI_CDRAMO   IN NUMBER
                               ,PI_AAAPERTU IN NUMBER
                               ,PI_NMSINIES IN NUMBER
                               ,PI_DATAINI   IN DATE
                               ,PI_DATAFIM   IN DATE
                               )   RETURN NUMBER IS
AUX_PROVISAO MSINIVAL.PTPAGOS%TYPE;
BEGIN
      SELECT /*+ RULE */
      SUM(VALORSIN.PTPAGOS*Pkg_Formulas_Cosec.FUN_TAXA_CAMBIO(VALORSIN.CDMONEDA))    INTO AUX_PROVISAO
      FROM
        MSINIVAL  VALORSIN
      WHERE
          VALORSIN.FEMOVIMI BETWEEN NVL(PI_DATAINI,VALORSIN.FEMOVIMI) AND PI_DATAFIM
      AND VALORSIN.CDUNIECO  = PI_CDUNIECO
      AND VALORSIN.CDRAMO    = PI_CDRAMO
      AND VALORSIN.AAAPERTU  = PI_AAAPERTU
      AND VALORSIN.STATUS    = 'M'
      AND VALORSIN.NMSINIES  = PI_NMSINIES;
RETURN AUX_PROVISAO;
EXCEPTION
  WHEN OTHERS THEN RETURN NULL;
END FUN_PROVISAO_SIN_DATA;

FUNCTION GET_PAGAMENTO_LIQ_SIN ( P_CDUNIECO IN NUMBER
                                , P_CDRAMO IN NUMBER
    , P_AAAPERTU IN NUMBER
    , P_STATUS IN VARCHAR2
    , P_NMSINIES IN NUMBER
                                , P_DATA_REF IN DATE) RETURN NUMBER AS
AUX_VALOR MDSPASIN.IMPREFER%TYPE;
BEGIN
 SELECT
   SUM (DETPAG.IMPREFER) INTO AUX_VALOR
 FROM
  MPAGOSIN PAG
 ,MDSPASIN DETPAG
 WHERE
 1=1
 AND DETPAG.NMORDPAG=PAG.NMORDPAG
 AND DETPAG.NMSINIES=PAG.NMSINIES
 AND DETPAG.STATUS=PAG.STATUS
 AND DETPAG.AAAPERTU=PAG.AAAPERTU
 AND DETPAG.CDRAMO=PAG.CDRAMO
 AND DETPAG.CDUNIECO=PAG.CDUNIECO
 AND DECODE(PAG.SWVIGOR,'V',PAG.FECOBRO,DECODE(PAG.FEPREVIS,NULL,PAG.FEAUTORI,PAG.FEPREVIS))<=P_DATA_REF
 AND DECODE(PAG.CDTIPMOV,1,'S',3,'S','N')='S'
 AND PAG.SWVIGOR!='A'
 AND PAG.SWESTADO=3
 AND PAG.NMSINIES=P_NMSINIES
 AND PAG.STATUS=P_STATUS
 AND PAG.AAAPERTU=P_AAAPERTU
 AND PAG.CDRAMO=P_CDRAMO
 AND PAG.CDUNIECO=P_CDUNIECO;
 RETURN AUX_VALOR;
  EXCEPTION
       WHEN OTHERS THEN RETURN NULL;
END GET_PAGAMENTO_LIQ_SIN;

end pkg_teste_func;

