-- PKG_DOCUMENTOS_UTIL (owner: SIID_TESTES)


-- ===== SPEC (PACKAGE) =====

PACKAGE Pkg_Documentos_Util
AS

  FUNCTION Get_Count_Tab(p_TABELA IN VARCHAR2, P_OWNER IN VARCHAR2 DEFAULT USER) RETURN NUMBER;
  PROCEDURE ENABLE_USER_DOC(p_modelo_id VARCHAR2, p_utilizador VARCHAR2 DEFAULT NULL);
  PROCEDURE DISABLE_USER_DOC(p_modelo_id VARCHAR2, p_utilizador VARCHAR2 DEFAULT NULL);
  FUNCTION GET_NEXT_EXTENT(p_extents IN NUMBER, p_initial IN NUMBER, p_increase IN NUMBER) RETURN NUMBER;
  FUNCTION GET_NUM_EXTENT(p_TOTAL IN NUMBER, p_iniTial IN NUMBER, p_increase IN NUMBER) RETURN NUMBER;
  FUNCTION GET_VALOR_CONTA(p_column_name IN VARCHAR2, p_table_name IN VARCHAR2, p_cdperson IN NUMBER, p_tipobalan IN 
VARCHAR2, p_anoref IN VARCHAR) RETURN NUMBER;

  PRAGMA RESTRICT_REFERENCES (Get_Count_Tab,WNDS);
  PRAGMA RESTRICT_REFERENCES (GET_NEXT_EXTENT,WNDS);
  PRAGMA RESTRICT_REFERENCES (GET_NUM_EXTENT,WNDS);
  PRAGMA RESTRICT_REFERENCES (GET_VALOR_CONTA,WNDS);
END;

-- ===== BODY (PACKAGE BODY) =====

PACKAGE BODY Pkg_Documentos_Util
AS

  FUNCTION GET_NUM_EXTENT(p_TOTAL IN NUMBER, p_iniTial IN NUMBER, p_increase IN NUMBER) RETURN NUMBER
  IS
    valor NUMBER := p_initial;
    blocos NUMBER;
  BEGIN
    IF P_TOTAL = P_iniTial THEN
      RETURN 1;
	ELSIF P_TOTAL = 0 THEN
	  RETURN 0;
    ELSE
       BLOCOS:= TRUNC(P_TOTAL/8192/(1+P_INCREASE/100));
       RETURN 1+ GET_NUM_EXTENT(BLOCOS*8192,P_INITIAL, P_INCREASE);
    END IF;
  END;


  FUNCTION GET_NEXT_EXTENT(p_extents IN NUMBER, p_initial IN NUMBER, p_increase IN NUMBER) RETURN NUMBER
  IS
    valor NUMBER := p_initial;
    blocos NUMBER:= CEIL(P_INITIAL/8192);
  BEGIN
    IF P_EXTENTS = 0 THEN
      RETURN BLOCOS*8192;
    ELSIF p_extents = 1 THEN
      blocos:=CEIL(BLOCOS*(1+P_INCREASE/100));
      RETURN BLOCOS*8192;
    ELSE
      BLOCOS :=CEIL(GET_NEXT_EXTENT(p_extents-1, p_initial, p_increase)/8192);
      blocos:=CEIL(BLOCOS*(1+P_INCREASE/100));
      RETURN BLOCOS*8192;
    END IF;
  END;

FUNCTION Get_Count_Tab(p_TABELA IN VARCHAR2, P_OWNER IN VARCHAR2 DEFAULT USER) RETURN NUMBER
IS
  nCount NUMBER:=0;
BEGIN

  EXECUTE IMMEDIATE
    'SELECT COUNT(*) FROM '||P_OWNER||'.'||P_TABELA INTO NCOUNT;

  RETURN NCOUNT;

EXCEPTION
  WHEN OTHERS THEN
     RETURN -1;
END Get_Count_Tab;

FUNCTION GET_VALOR_CONTA(p_column_name IN VARCHAR2, p_table_name IN VARCHAR2, p_cdperson IN NUMBER, p_tipobalan IN VARCHAR2, 
p_anoref IN VARCHAR) RETURN NUMBER
IS
  nvalor NUMBER:=0;
  vsql varchar(1500);
BEGIN

  vsql:= 'SELECT '||p_column_name||' FROM '||p_table_name||' WHERE CDPERSON= '||p_cdperson||' AND TIPOBALAN='''||
p_tipobalan||''' and ANOREF= '|| p_anoref; 
  
  EXECUTE IMMEDIATE VSQL INTO NVALOR;

  RETURN NVALOR;

EXCEPTION
  WHEN OTHERS THEN
     RETURN null;
END GET_VALOR_CONTA;

PROCEDURE ENABLE_USER_DOC(p_modelo_id VARCHAR2, p_utilizador VARCHAR2 DEFAULT NULL) IS
BEGIN
  UPDATE CFG_PERMISSOES_SIID
  SET data_fim = NULL
  WHERE data_fim = TO_DATE('1888-01-01','YYYY-MM-DD')
  AND   modelo_id = p_modelo_id
  AND   username  = NVL(p_utilizador,username);
  COMMIT;
END;

PROCEDURE DISABLE_USER_DOC(p_modelo_id VARCHAR2, p_utilizador VARCHAR2 DEFAULT NULL) IS
BEGIN
  UPDATE CFG_PERMISSOES_SIID
  SET data_fim = TO_DATE('1888-01-01','YYYY-MM-DD')
  WHERE NVL(data_fim,SYSDATE+1) >= SYSDATE
  AND   data_inicio < SYSDATE
  AND   modelo_id = p_modelo_id
  AND   username  = NVL(p_utilizador,username);
  COMMIT;
END;
END;
