-- PKG_ONLINE (owner: SIID_TESTES)


-- ===== SPEC (PACKAGE) =====

PACKAGE "PKG_ONLINE"
AS

  --* CONSTANTES PROPRIAS QUESTIONAR INFORMAC?ES SOBRE VERS?ES
  --*
  --* CRIADO POR  : JOSE VIEGAS
  --* DATA CRIACAO: 11-02-2010
  --* OBSERVACAO  : A) ESTA SECC?O DEVE ESTAR NO INICIO DO PACKAGE SEMPRE
  --*               B) SEMPRE QUE FOR EFECTUADA ALGUMA ALTERAC?O AO PACKAGE
  --*                  DEVEM SER ACTUALIZADAS AS CONSTANTES DO PACKAGE BODY
  --*                  "VERSAO", "DATA_VERSAO"  "AUTOR_VERSAO".
  --*
  INFO_VERSAO          CONSTANT VARCHAR2(100):='VERSAO';
  INFO_DATA_VERSAO     CONSTANT VARCHAR2(100):='DATA_VERSAO';
  INFO_AUTOR_PACKAGE   CONSTANT VARCHAR2(100):='AUTOR_PACKAGE';
  INFO_AUTOR_VERSAO    CONSTANT VARCHAR2(100):='AUTOR_VERSAO';
  INFO_DATA_PACKAGE    CONSTANT VARCHAR2(100):='DATA_PACKAGE';
  INFO_DATA_INSTALACAO CONSTANT VARCHAR2(100):='DATA_INSTALACAO';
  INFO_OWNER           CONSTANT VARCHAR2(100):='OWNER';

  CHAR_RESERV CONSTANT VARCHAR2(1) := '¿';

  /*
  -* NOME      : GET_PACKINFO
  -* OBJECTIVO : MANTER INFORMAC?O SOBRE VERS?O DO PACKAGE
  -* UTILIZACAO: PKG_CFG_UTIL.GET_PACKINFO ( 'VERSAO' );
  -* AUTOR     : Jose Viegas
  -* DATA      : 11-02-2010
  -* VERS?O    : 1.0
  -*
  -* ULTIMAS ALTERAC?ES
  -*
  -*   DATA       VERSAO AUTOR           DESCRIC?O
  -*   ========== ====== =============== =================================================
  -*/
  FUNCTION GET_PACKINFO ( P_TIPO_INFO VARCHAR2 DEFAULT 'COMPLETE' ) RETURN VARCHAR2;


  /*
  -* NOME      : OPEN_GATE
  -* OBJECTIVO : ABRIR ENTRADA PARA CONSULTA ONLINE
  -* UTILIZACAO: KEY:=PKG_ONLINE.OPEN_GATE(USER, PASS, IP, HOST, SO, USER);
  -* AUTOR     : Eng. Jose Viegas
  -* DATA      : 15-04-2010
  -* VERS?O    : 1.0
  -*
  -* ULTIMAS ALTERAC?ES
  -*
  -*   DATA       VERSAO AUTOR           DESCRIC?O
  -*   ========== ====== =============== =================================================
  -*/
  FUNCTION OPEN_GATE( P_USER      IN VARCHAR2 DEFAULT USER
                    , P_PASS      IN VARCHAR2
					, P_AMBIENTE  IN VARCHAR2 DEFAULT NULL
					, P_HOST_IP   IN VARCHAR2 DEFAULT NULL
					, P_HOST_NAME IN VARCHAR2 DEFAULT NULL
					, P_HOST_SO   IN VARCHAR2 DEFAULT NULL
					, P_HOST_USER IN VARCHAR2 DEFAULT NULL) RETURN VARCHAR2;

  /*
  -* NOME      : TEST_KEY
  -* OBJECTIVO : TESTA CHAVE FORNECIDA PARA ENTRAR ONLINE
  -* UTILIZACAO: LOGIN:=PKG_ONLINE.TEST_KEY(KEY, ORIGEM);
  -* AUTOR     : Eng. Jose Viegas
  -* DATA      : 15-04-2010
  -* VERS?O    : 1.0
  -*
  -* ULTIMAS ALTERAC?ES
  -*
  -*   DATA       VERSAO AUTOR           DESCRIC?O
  -*   ========== ====== =============== =================================================
  -*/
  FUNCTION TEST_KEY( P_KEY    IN VARCHAR2
                   , P_ORIGEM IN VARCHAR2 DEFAULT NULL) RETURN VARCHAR2;

  /*
  -* NOME      : VALIDA_UE
  -* OBJECTIVO : TESTA SE MODELO TEM UNIDADE ECONOMICA VALIDA COM O UTILIZADOR
  -* UTILIZACAO: PKG_ONLINE.VALIDA_UE(DOC_ID) = 'S';
  -* AUTOR     : ALDO TITA
  -* DATA      : 02-11-2012
  -* VERS?O    : 1.0
  -*
  -* ULTIMAS ALTERAC?ES
  -*
  -*   DATA       VERSAO AUTOR           DESCRIC?O
  -*   ========== ====== =============== =================================================
  -*/
  FUNCTION VALIDA_UE( P_ID IN SVR_DOCUMENTOS.ID%TYPE, P_REPORT_ID IN SVR_DOCUMENTOS.REPORT_ID%TYPE,
    P_PARAMETRO04  IN SVR_DOCUMENTOS.PARAMETRO04%TYPE,P_PARAMETRO05  IN SVR_DOCUMENTOS.PARAMETRO05%TYPE,
    P_PARAMETRO06  IN SVR_DOCUMENTOS.PARAMETRO06%TYPE,P_PARAMETRO07  IN SVR_DOCUMENTOS.PARAMETRO07%TYPE) RETURN VARCHAR2;

  /*
  -* NOME      : F_INS_ENCRIPT
  -* OBJECTIVO : CODIFICA PASSWORDS
  -* UTILIZACAO: PKG_ONLINE.F_INS_ENCRIPT(PASSWORD,CHAVE) = 'S';
  -* AUTOR     : JOAO RIBEIRO
  -* DATA      : 13-10-2022
  -* VERS?O    : 1.0
  -*
  -* ULTIMAS ALTERAC?ES
  -*
  -*   DATA       VERSAO AUTOR           DESCRIC?O
  -*   ========== ====== =============== =================================================
  -*/
  FUNCTION F_INS_ENCRIPT(P_PASSWORD VARCHAR2, P_STRING VARCHAR2) RETURN VARCHAR2;

END PKG_ONLINE;

-- ===== BODY (PACKAGE BODY) =====

PACKAGE BODY "PKG_ONLINE"
AS
  PACOTE         CONSTANT VARCHAR2(100):='PKG_ONLINE';
  V_PACOTE       CONSTANT VARCHAR2(100):='0.1';
    /*
  -*
  -* ULTIMAS ALTERAC?ES AO PACKAGE
  -*
  -*   DATA       VERSAO AUTOR           DESCRIC?O
  -*   ========== ====== =============== ===================================================
  -*   11-02-2010    1.0 Jose Viegas     Criacao do package
  */
  VERSAO         CONSTANT VARCHAR2(100):= '2010.01.01';
  DATA_VERSAO    CONSTANT DATE:= TO_DATE('15-04-2010 11:26:03','DD-MM-YYYY HH24:MI:SS');
  AUTOR_PACKAGE  CONSTANT VARCHAR2(100):='JOSE VIEGAS';
  AUTOR_VERSAO   CONSTANT VARCHAR2(100):='01.01';

  /*
  -* NOME      : GET_PACKINFO
  -* OBJECTIVO : MANTER INFORMAC?O SOBRE VERS?O DO PACKAGE
  -* UTILIZACAO: PKG_CFG_UTIL.GET_PACKINFO ( 'VERSAO' );
  -* AUTOR     : Eng. Jose Viegas
  -* DATA      : 25-11-2004
  -* VERS??O    : 1.0
  -*
  -* ULTIMAS ALTERAC?ES
  -*
  -*   DATA       VERSAO AUTOR           DESCRIC?O
  -*   ========== ====== =============== =================================================
  -*/
  FUNCTION GET_PACKINFO ( P_TIPO_INFO VARCHAR2 DEFAULT 'COMPLETE' ) RETURN VARCHAR2 IS
    AUX VARCHAR2(200);
  BEGIN
    IF P_TIPO_INFO = INFO_VERSAO THEN  /* DEVOLVE VERS?O DO PACKAGE */
      RETURN 'v'||TO_CHAR(VERSAO);
    ELSIF P_TIPO_INFO = INFO_DATA_VERSAO THEN
      RETURN TO_CHAR(DATA_VERSAO,'YYYY-MM-DD HH24:MI');
    ELSIF P_TIPO_INFO = INFO_AUTOR_PACKAGE THEN
      RETURN AUTOR_PACKAGE;
    ELSIF P_TIPO_INFO = INFO_AUTOR_VERSAO THEN
      RETURN AUTOR_VERSAO;
    ELSIF P_TIPO_INFO = INFO_DATA_PACKAGE THEN
      BEGIN
        SELECT
          TO_CHAR(CREATED,'YYYY-MM-DD HH24:MI')
        INTO
          AUX
        FROM
          ALL_OBJECTS
        WHERE
            OBJECT_NAME=PACOTE
        AND OBJECT_TYPE='PACKAGE BODY'
        AND OWNER = (SELECT USERNAME FROM USER_USERS);
        RETURN AUX;
      EXCEPTION
        WHEN OTHERS THEN
         RETURN PACOTE||' v'||VERSAO||'('||TO_CHAR(DATA_VERSAO,'YYMMDDHH24MI')||')';
      END;
    ELSIF P_TIPO_INFO = INFO_DATA_INSTALACAO THEN
      BEGIN
        SELECT
          TO_CHAR(LAST_DDL_TIME,'YYYY-MM-DD HH24:MI')
        INTO
          AUX
        FROM
          ALL_OBJECTS
        WHERE
            OBJECT_NAME=PACOTE
        AND OBJECT_TYPE='PACKAGE BODY'
        AND OWNER = (SELECT USERNAME FROM USER_USERS);
        RETURN AUX;
      EXCEPTION
        WHEN OTHERS THEN
         RETURN PACOTE||' v'||VERSAO||'('||TO_CHAR(DATA_VERSAO,'YYMMDDHH24MI')||')';
      END;
    ELSIF P_TIPO_INFO = INFO_OWNER THEN
      SELECT USERNAME INTO AUX FROM USER_USERS;
      RETURN AUX;
    ELSE
      RETURN PACOTE||' v'||VERSAO||'('||TO_CHAR(DATA_VERSAO,'YYMMDDHH24MI')||')';
    END IF;
  END GET_PACKINFO;


  /*
  -* NOME      : OPEN_GATE
  -* OBJECTIVO : ABRIR ENTRADA PARA CONSULTA ONLINE
  -* UTILIZACAO: KEY:=PKG_ONLINE.OPEN_GATE(USER, PASS, IP, HOST, SO, USER);
  -* AUTOR     : Eng. Jose Viegas
  -* DATA      : 15-04-2010
  -* VERS?O    : 1.0
  -*
  -* ULTIMAS ALTERAC?ES
  -*
  -*   DATA       VERSAO AUTOR           DESCRIC?O
  -*   ========== ====== =============== =================================================
  -*/
  FUNCTION OPEN_GATE( P_USER      IN VARCHAR2 DEFAULT USER
                    , P_PASS      IN VARCHAR2
					, P_AMBIENTE  IN VARCHAR2 DEFAULT NULL
					, P_HOST_IP   IN VARCHAR2 DEFAULT NULL
					, P_HOST_NAME IN VARCHAR2 DEFAULT NULL
					, P_HOST_SO   IN VARCHAR2 DEFAULT NULL
					, P_HOST_USER IN VARCHAR2 DEFAULT NULL) RETURN VARCHAR2
  IS

    pragma autonomous_transaction;

    L_KEY RAW(16):= SYS_GUID();
	L_AMBIENTE VARCHAR2(30):=P_AMBIENTE;
	L_VALIDADE NUMBER;
	L_ENCRYPTED_PASS VARCHAR(1000);
	L_AMB_KEY VARCHAR(100);

  BEGIN

    IF P_PASS IS NULL THEN
	  ROLLBACK;
	  RETURN NULL;
	END IF;

	IF L_AMBIENTE IS NULL THEN
	  SELECT
	    USERNAME
	  INTO
	    L_AMBIENTE
	  FROM
	    USER_USERS;
    END IF;

	BEGIN
	  SELECT
  	    VALOR
  	  INTO
        L_VALIDADE
	  FROM
        S$PARAMETROS
	  WHERE
	    ID = 'VALIDADE_KEY';
	EXCEPTION
	  WHEN OTHERS THEN
	    L_VALIDADE:=30;
	END;

	L_ENCRYPTED_PASS := USER_SECURITY.encrypt(P_PASS);

	DBMS_OUTPUT.PUT_LINE(L_AMBIENTE||' -> '||P_USER||'!');

    INSERT
     INTO S$ONLINE
    (
      ID
    , USER_ID
    , PASSWORD
    , AMBIENTE
    , ENTRADA
    , VALIDADE
    , ORIGEM_IP
    , ORIGEM_HOST
    , ORIGEM_SO
    , ORIGEM_USER
    )
    VALUES
    (
      L_KEY
    , P_USER
    , L_ENCRYPTED_PASS
    , L_AMBIENTE
    , SYSDATE
    , L_VALIDADE
    , P_HOST_IP
    , P_HOST_NAME
    , P_HOST_SO
    , P_HOST_USER
    );

	IF L_AMBIENTE = 'COSEC' THEN
		L_AMB_KEY := rawtohex(L_KEY);
		L_AMB_KEY := '?id=' || L_AMB_KEY || '&' || 'amb=P';
	ELSE
		L_AMB_KEY := rawtohex(L_KEY);
		L_AMB_KEY := '?id=' || L_AMB_KEY || '&' || 'amb=T';
    END IF;

	COMMIT;

    RETURN L_AMB_KEY;

  EXCEPTION
    WHEN OTHERS THEN
	  ROLLBACK;
	  RETURN NULL;
  END OPEN_GATE;

  /*
  -* NOME      : TEST_KEY
  -* OBJECTIVO : TESTA CHAVE FORNECIDA PARA ENTRAR ONLINE
  -* UTILIZACAO: LOGIN:=PKG_ONLINE.TEST_KEY(KEY, ORIGEM);
  -* AUTOR     : Eng. Jose Viegas
  -* DATA      : 15-04-2010
  -* VERS?O    : 1.0
  -*
  -* ULTIMAS ALTERAC?ES
  -*
  -*   DATA       VERSAO AUTOR           DESCRIC?O
  -*   ========== ====== =============== =================================================
  -*/
  FUNCTION TEST_KEY( P_KEY    IN VARCHAR2
                   , P_ORIGEM IN VARCHAR2 DEFAULT NULL) RETURN VARCHAR2
  IS
    pragma autonomous_transaction;

    L_LOGIN VARCHAR2(200);
  BEGIN
    IF  P_KEY IS NULL
	 OR NVL(P_ORIGEM,'') = '' THEN
	  ROLLBACK;
	  RETURN '0';
	END IF;

	SELECT
	  USER_ID||'/'||USER_SECURITY.decrypt(PASSWORD)||'/'||AMBIENTE
	INTO
	  L_LOGIN
	FROM
	  S$ONLINE
	WHERE
	    ID = hextoraw(P_KEY)
--	AND ORIGEM_IP = P_ORIGEM
	AND USADO_BN = 'N'
	AND ENTRADA+VALIDADE/(24*60*60) >= SYSDATE
	FOR UPDATE;

	UPDATE
	  S$ONLINE
	SET
	  USADO_BN = 'S'
	WHERE
	  ID = hextoraw(P_KEY);

	COMMIT;

	RETURN L_LOGIN;

  EXCEPTION
    WHEN OTHERS THEN
	  ROLLBACK;
	  RETURN '0';
  END TEST_KEY;

  /*
  -* NOME      : VALIDA_UE
  -* OBJECTIVO : TESTA SE MODELO TEM UNIDADE ECONOMICA VALIDA COM O UTILIZADOR
  -* UTILIZACAO: PKG_ONLINE.VALIDA_UE(DOC_ID) = 'S';
  -* AUTOR     : ALDO TITA
  -* DATA      : 02-11-2012
  -* VERS?O    : 1.0
  -*
  -* ULTIMAS ALTERAC?ES
  -*
  -*   DATA       VERSAO AUTOR           DESCRIC?O
  -*   ========== ====== =============== =================================================
  -*/

FUNCTION VALIDA_UE( P_ID IN SVR_DOCUMENTOS.ID%TYPE, P_REPORT_ID IN SVR_DOCUMENTOS.REPORT_ID%TYPE,
  P_PARAMETRO04  IN SVR_DOCUMENTOS.PARAMETRO04%TYPE,P_PARAMETRO05  IN SVR_DOCUMENTOS.PARAMETRO05%TYPE,
  P_PARAMETRO06  IN SVR_DOCUMENTOS.PARAMETRO06%TYPE,P_PARAMETRO07  IN SVR_DOCUMENTOS.PARAMETRO07%TYPE) RETURN VARCHAR2
  IS
  V_PARAMETRO VARCHAR(100);
  V_VALOR_UE  NUMBER;
  V_SQL       VARCHAR(4000);
  V_RETURN    NUMBER;
  BEGIN

      /*verificar qual o parametro que diz respeito a unidade economica*/
      SELECT
        N_PARAMETRO
      INTO
        V_PARAMETRO
      FROM
        SVR_PARAMETROS_REPORT PARAMETROS
      WHERE 1=1
      AND P_REPORT_ID = PARAMETROS.REPORT_ID
      AND UPPER(PARAMETROS.NOME) ='P_CDUNIECO'
      AND PARAMETROS.VALIDO='S';

      IF V_PARAMETRO=4 THEN
        V_VALOR_UE := P_PARAMETRO04;
      ELSIF V_PARAMETRO=5 THEN
        V_VALOR_UE := P_PARAMETRO05;
      ELSIF V_PARAMETRO=6 THEN
        V_VALOR_UE := P_PARAMETRO06;
      ELSE
        V_VALOR_UE := P_PARAMETRO07;
      END IF;

      /* VALIDAR SE O UTILIZADOR TEM ACESSO AO DOCUMENTO */
      V_SQL :=
     'SELECT '||
     '  ''S'' '||
     'FROM '||
     ' R_UNIDAUSR     UNI '||
     'WHERE '||
     '    UNI.CDUNIECO ='''||V_VALOR_UE||''' '||
     'AND UNI.CDIDUSR= user ';

      BEGIN
        EXECUTE IMMEDIATE V_SQL INTO V_RETURN;

      EXCEPTION
        WHEN NO_DATA_FOUND THEN
            V_RETURN:= 'N';
      END;

      RETURN V_RETURN;

  EXCEPTION
    WHEN OTHERS THEN
        RETURN 'S';
  END VALIDA_UE;

  FUNCTION F_INS_ENCRIPT(P_PASSWORD VARCHAR2, P_STRING VARCHAR2) RETURN VARCHAR2 IS
    L_RETURN_STRING  VARCHAR2(1000);
	BEGIN

	dbms_obfuscation_toolkit.DESEncrypt(input_string=>RPAD(P_STRING,32,CHAR_RESERV),
                                         key_string=>RPAD(P_PASSWORD,32,CHAR_RESERV),
                                         encrypted_string=>L_RETURN_STRING);

	RETURN L_RETURN_STRING;

  EXCEPTION
    WHEN OTHERS THEN
        --PCK_GEN.P_PUT_ERROR;
        RAISE;
  END F_INS_ENCRIPT;

END PKG_ONLINE;
