-- SET_SAFTDOC (owner: SIID_TESTES)


-- ===== FUNCTION =====

FUNCTION SET_SAFTDOC( P_CDUNIECO IN VARCHAR2, P_DOCNO IN VARCHAR2, P_CDPERSON IN NUMBER, P_NOME IN VARCHAR2, P_MORADA IN VARCHAR2, P_LOCALIDADE IN VARCHAR2, P_CODPOST IN VARCHAR2, P_CDPAIS IN VARCHAR2) RETURN VARCHAR2
IS
  cResult NUMBER;
BEGIN

	SELECT nmrecibo
	INTO cResult
	FROM CO_SAFTDOC
	WHERE DOCNO = P_DOCNO
	AND CDUNIECO = P_CDUNIECO;
	
	IF cResult IS NOT NULL THEN

		UPDATE
			CO_SAFTDOC
		SET
			CDPERSON = P_CDPERSON
			,NOME = P_NOME
			,MORADA = P_MORADA
			,LOCALIDADE = P_LOCALIDADE
			,CODPOST = P_CODPOST
			,CDPAIS = P_CDPAIS
		WHERE
		CDUNIECO = P_CDUNIECO
		AND DOCNO = P_DOCNO;

		COMMIT;
		
		return '1';

	END IF;

  return '0';

EXCEPTION
  WHEN OTHERS THEN
    RETURN '-1';
END SET_SAFTDOC;
