-- TESTE_MOVIMENTOS (owner: SIID_TESTES)


-- ===== SPEC (PACKAGE) =====

PACKAGE Teste_Movimentos
AS
  FUNCTION FUN_N_COMUNIC_MORA (PI_CDUNIECO IN NUMBER
		 					,PI_CDRAMO   IN VARCHAR2
							,PI_NMPOLIZA IN NUMBER
							,PI_DT IN DATE) RETURN NUMBER;
  FUNCTION GET_DT_ANULACAO_APOLICE (PI_CDUNIECO IN NUMBER, PI_CDRAMO IN NUMBER,PI_NMPOLIZA IN NUMBER) RETURN DATE;
  FUNCTION GET_VALOR_COMISSAO(P_CDUNIECO IN NUMBER, P_NMRECIBO IN NUMBER) RETURN NUMBER;
  FUNCTION GET_TIPO_COMISSAO(P_CDUNIECO IN NUMBER, P_NMRECIBO IN NUMBER) RETURN VARCHAR2;
  FUNCTION FUN_N_AV ( PI_numhisto IN NUMBER
		 		   ,PI_cdunieco IN NUMBER
				   ,PI_cdramo   IN NUMBER
				   ,PI_aaapertu IN NUMBER
				   ,PI_status   IN VARCHAR2
				   ,PI_nmsinies IN NUMBER) RETURN NUMBER;
  
  PRAGMA RESTRICT_REFERENCES (FUN_N_COMUNIC_MORA,WNDS);
  PRAGMA RESTRICT_REFERENCES (GET_DT_ANULACAO_APOLICE,WNDS);
  PRAGMA RESTRICT_REFERENCES (GET_VALOR_COMISSAO,WNDS);
  PRAGMA RESTRICT_REFERENCES (GET_TIPO_COMISSAO,WNDS);
  PRAGMA RESTRICT_REFERENCES (FUN_N_AV,WNDS);
END;


-- ===== BODY (PACKAGE BODY) =====

PACKAGE  BODY Teste_Movimentos
AS
FUNCTION FUN_N_COMUNIC_MORA (PI_CDUNIECO IN NUMBER
		 					,PI_CDRAMO   IN VARCHAR2
							,PI_NMPOLIZA IN NUMBER
							,PI_DT IN DATE) RETURN NUMBER
IS
AUX_N NUMBER;
AUX_PROV NUMBER;
BEGIN
		SELECT COUNT(*) INTO AUX_N
		FROM CO_COAME COMUNICACAO
		WHERE
		1=1
		AND COMUNICACAO.FECOMUNI<PI_DT
		AND COMUNICACAO.FECIERRE IS NULL
		AND COMUNICACAO.NMPOLIZA = PI_NMPOLIZA
		AND COMUNICACAO.CDRAMO   = PI_CDRAMO
		AND COMUNICACAO.CDUNIECO = PI_CDUNIECO;

		SELECT COUNT(*) INTO AUX_PROV 
		FROM (
		SELECT DISTINCT COMUNIC.NMCOMAME,COMUNIC.NMPROAME,COMUNIC.CDTIPORA,COMUNIC.CDRAMO 
		FROM MSINIEST SINISTRO, CO_COAME COMUNIC, MSINIVAL PROV 
		WHERE 
		1=1 
		AND PROV.PTPAGOS<>0 
		AND PROV.NMSINIES=SINISTRO.NMSINIES 
		AND PROV.STATUS=SINISTRO.STATUS 
		AND PROV.AAAPERTU=SINISTRO.AAAPERTU 
		AND PROV.CDRAMO=SINISTRO.CDRAMO 
		AND PROV.CDUNIECO=SINISTRO.CDUNIECO 
		AND SINISTRO.CDUNIECO=COMUNIC.CDUNIECO 
		AND SINISTRO.CDRAMO=COMUNIC.CDRAMO 
		AND SINISTRO.CDTIPORA=COMUNIC.CDTIPORA 
		AND SINISTRO.NMCOMAME=COMUNIC.NMCOMAME 
		AND SINISTRO.NMPROAME=COMUNIC.NMPROAME 
		AND COMUNIC.FECOMUNI<PI_DT
		AND COMUNIC.FECIERRE IS NULL
		AND COMUNIC.NMPOLIZA = PI_NMPOLIZA
		AND COMUNIC.CDRAMO   = PI_CDRAMO
		AND COMUNIC.CDUNIECO = PI_CDUNIECO);

RETURN AUX_N-AUX_PROV;
EXCEPTION
		 WHEN OTHERS THEN
		 	  RETURN NULL;
END FUN_N_COMUNIC_MORA;
  FUNCTION GET_DT_ANULACAO_APOLICE (PI_CDUNIECO IN NUMBER, PI_CDRAMO IN NUMBER,PI_NMPOLIZA IN NUMBER) RETURN DATE
  IS
  AUX_TIPOSUP TDESCSUP.CDTIPSUP%TYPE;
  AUX_DT_ANULACAO MSUPLEME.FEINIVAL%TYPE;

  BEGIN
  SELECT
	SUPLOGIC.CDTIPSUP
	,SUPLEMENTO.FEINIVAL
	INTO AUX_TIPOSUP, AUX_DT_ANULACAO
	FROM
 	 TDESCSUP SUPLOGIC
	,MSUPLEME SUPLEMENTO
	WHERE
	2=2
	AND SUPLEMENTO.SWANULA  IS NOT NULL
	AND SUPLEMENTO.NSUPLOGI = SUPLOGIC.NSUPLOGI
	AND SUPLEMENTO.NMPOLIZA = PI_NMPOLIZA
	AND SUPLEMENTO.ESTADO   = SUPLOGIC.ESTADO
	AND SUPLEMENTO.CDRAMO   = PI_CDRAMO
	AND SUPLEMENTO.CDUNIECO = PI_CDUNIECO
	AND SUPLOGIC.NSUPLOGI= (
						   	SELECT MAX(X.NSUPLOGI)
							FROM
							TDESCSUP X
							WHERE
							2=2
							AND X.NMPOLIZA = PI_NMPOLIZA
							AND X.ESTADO='M'
							AND X.CDRAMO   = PI_CDRAMO
							AND X.CDUNIECO = PI_CDUNIECO
							)
	AND SUPLOGIC.NMPOLIZA = PI_NMPOLIZA
	AND SUPLOGIC.ESTADO='M'
	AND SUPLOGIC.CDRAMO   = PI_CDRAMO
	AND SUPLOGIC.CDUNIECO = PI_CDUNIECO;

	IF (AUX_TIPOSUP='52') THEN
	   RETURN AUX_DT_ANULACAO;
	ELSE
	   RETURN NULL;
	END IF;

	EXCEPTION
    WHEN OTHERS THEN
      RETURN NULL;
 END GET_DT_ANULACAO_APOLICE;


  FUNCTION GET_VALOR_COMISSAO(P_CDUNIECO IN NUMBER, P_NMRECIBO IN NUMBER) RETURN NUMBER
  IS
    V_COM NUMBER;
  BEGIN
    SELECT
            SUM(COMISSAO.PTIMPORT)
    INTO
      V_COM
    FROM
      TRECCOM COMISSAO
    WHERE
	2=2
	AND  DECODE(COMISSAO.CDTIPCOM,'N','S','R','S','N')='S'
	AND  COMISSAO.NMRECIBO=P_NMRECIBO
	AND  COMISSAO.CDUNIECO=P_CDUNIECO ;
    RETURN V_COM;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN NULL;
  END;
  FUNCTION GET_TIPO_COMISSAO(P_CDUNIECO IN NUMBER, P_NMRECIBO IN NUMBER) RETURN VARCHAR2
  IS
    T_COM TRECCOM.CDTIPCOM%TYPE;
  BEGIN
    SELECT
            MAX(COMISSAO.CDTIPCOM)
    INTO
      T_COM
    FROM
      TRECCOM COMISSAO
    WHERE
    2=2
   	AND  DECODE(COMISSAO.CDTIPCOM,'N','S','R','S','N')='S'
	AND  COMISSAO.NMRECIBO=P_NMRECIBO
	AND  COMISSAO.CDUNIECO=P_CDUNIECO ;
    RETURN T_COM;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN NULL;
  END;

FUNCTION FUN_N_AV ( PI_numhisto IN NUMBER
		 		   ,PI_cdunieco IN NUMBER
				   ,PI_cdramo   IN NUMBER
				   ,PI_aaapertu IN NUMBER
				   ,PI_status   IN VARCHAR2
				   ,PI_nmsinies IN NUMBER) RETURN NUMBER IS
AUX_COUNT NUMBER;
BEGIN
SELECT COUNT(*) INTO AUX_COUNT 
FROM 
HSINIPER
WHERE
1=1
AND CDROL='AV'
AND NUMHISTO=PI_NUMHISTO
AND CDUNIECO=PI_CDUNIECO
AND CDRAMO=PI_CDRAMO
AND AAAPERTU=PI_AAAPERTU
AND STATUS= PI_STATUS
AND NMSINIES=PI_NMSINIES;

RETURN AUX_COUNT;

END FUN_N_AV;				   
END Teste_Movimentos;


